#+title: microtonal guitar
* [[file:20210319143836-microtonal_chapman_stick.org][microtonal Chapman Stick]]
* [[file:20210423201225-fret_markers_my_preferred_system_of.org][fret markers, my preferred system of]]
* some many-stringed guitars
** the Jackson SLAT8
   https://www.jacksonguitars.com/gear/shape/soloist/x-series-soloist-archtop-slat8-ms/2916767503
** the Schecter Reaper-7
   https://www.schecterguitars.com/guitars/reaper-7-multiscale-satin-inferno-burst-detail
* TODO ask about Metatonal and neck standards
** first check the website
** almost sent Facebook group
I read about replacing necks on guitars. It often requires reducing the size of the joint on the neck so it fits in the socket on the guitar. I don't have equipment for that, and I don't know any competent luthiers around here.

Are there brands of guitars that reliably use "standard" sockets for the neck? Are replacement necks from Metatonal Music that size?

If I buy a replacement neck from Metatonal Music, is there a

[Related: https://www.facebook.com/groups/497105067092502/permalink/2086475328155460]
* things that can work as movable fretwire
** violin marking tape
   Supposedly easier than zipties.
   https://www.ebay.co.uk/itm/Desktop-Positioning-Tape-Whiteboard-Violin-Fingering-Marking-Tape-Pinstripe-Arts-/363175705221?_trksid=p2349624.m46890.l49292
** zipties
*** advice from others
   Use needlenose pliers to crimp the tie at the corners where it bends around the fretboard.
   Use them also to tighten.
   Trimming the fret-like portion of the ziptie on the bridge side with scissors can help. (Don't trim the side that you fret because that would change the intonation.)
*** TODO How to make them grip better?
    Score the back of the neck?
    Put grip liner under them?
* TODO how to remove frets
** with a razor, score around where the fret joins the fretboard
   both on the face and on the sides of the neck
** use masking tape to protect the neck around the fret
   when heating with soldering iron
** clean the fret slots once the frets are out
* [[file:20210223093816-how_i_used_zipties_to_turn_a_12_edo_guitar_into_a_24_edo_one.org][How I used zipties to turn a 12-edo guitar into a 24-edo one]]
* [[file:20210223205954-removing_frets_contacting_luthiers_in_bogota_about.org][removing frets: contacting luthiers in Bogota about]]
