#+title: spaced repetition
#+ROAM_ALIAS: internalize memory remember
* TODO remember
** keeping JACK happy
*** Killing SC before the GHCI process makes Jack err.
*** don't leave Spotify open (even if not playing) when turning Qjackctl
    not sure but maybe bad
** git and big text moves
*** before moving a complicated thing in a git repo
    consider whether I can move its definition to its own file.
    If so, do that, and then just move the reference to the new file.
    That way the diff is more readable.
*** if I can't, push my changes just before and just after any such move
    Otherwise, checking the diff is a nightmare.
    I'll have forgotten what I was doing,
    *and* once I realize I'm looking at a move,
    I have to search for each moved line.
** Does meta awareness stop pointless behaviors?
* TODO I have a few notes like this; join them.
  search for "internalize", "spaced repetition", maybe "to learn", "remember"
* unreviewed
** how to estimate (e.g. duration)
   Estimation (e.g. of duration) is best done via indepedent chunks, rather than a wholistic intuition. (per Daniel Kahneman)
   Then subdivide a different way and estimate again. (per some guy quoted by Steve Levitt in his podcast interview with DK in 2021).
** The special international status of the US dollar is not important to the US.
   https://mail.google.com/mail/u/0/#inbox/FMfcgzGkXctVmLFSxwJThvtnzflnqFML
*** maybe the biggest benefit
    The dollars held outside the US do represent a 0-interest loan, which in times of high interest rates can be meaningful -- about 0.25% of GDP.
*** some non-existent benefits
**** The US current account deficit is less than Britain's or Australia's.
**** The US borrows at a higher interest rate than Britain or Japan.
**** The British pound, which was only overtaken by the US dollar in 1955 and not special at all by 1975, has only increased in value against the dollar since.
** (Aspirational) mimicry can substitute for rationality.
   It's in SmSn, at id
   BSPkZvDjoUqhzm0Z
** [[file:../tech/20210419132152-microsoft_teams_shortcuts.org][Microsoft Teams shortcuts]]
** LCR invites
   Make sure I know who's coming before responding.
** learning, technical
*** re. choosing type names
make sure they are sufficiently complete.
For instance, Action turned out to be a worse name than ScAction,
and renaming took me like 15 minutes.
*** why to format notes-to-learn as flashcards
That way I can hide the answer when reviewing,
which lets me know when to discard the flashcard.
*** when I receive something from someone, do what?
Write it down,
because I might need to know that they can provide that.
*** In python, what's a terse way to repeat a list?
[1]*3 = [1,1,1]
*** git hygiene
**** what is fragile?
     an unindexed file
It's dangerous to leave files I want in a clone of a git repo without adding them to the repo.
 That's because I might copy a file of the same name into the folder from elsewhere.
**** make git diffs readable by what?
 Include empty lines where appropriate.
  Because when you change one paragraph, the changes will not bleed into changes of the next paragraph; the unchanged empty line continues to separate them.
*** [[id:a24e17db-7c46-45c7-a4b9-ca053559e65f][org-roam: notes with nothing but a title can be important]]
** Countries might not give the widest coverage as units of news analysis.
   There's something repetitive about "this country's got a tyrant ... and this other country's got a tyrant ... and here's what the tyrant over there's doing ..."
* reviewed, still no insight
** befuddling: links in knowledge graphs
*** link labels vs. link contexts
    [[id:46b695c5-617e-47a8-b699-ef2b7ec29e81][the context of a link matters]]
*** [[id:3305442a-e435-4f84-a403-9509963497b7][Note titles should be complete sentences.]]
*** [[id:edca15b1-37f9-46ec-bb32-8a3090242b0d][? Use backlinks to define notes extrinsically]]
* likely internalized
** leaving Qjackctl on seems to work
 I left it open, not running, for days and I can play the synth with it today.
