#+title: tech and AI (my mini-course for Colegio Andino)
tech = technology
* day 1
** profits
*** profit = revenue - costs
*** top companies by proit
    https://asian-links.com/gdp/most-profitable-companies
*** Uber's profit/loss history
    https://1z1euk35x7oy36s8we4dr6lo-wpengine.netdna-ssl.com/wp-content/uploads/2017/08/Uber-revenue-profit.png
** the growth-first strategy.
*** Pets.com
     http://www.uky.edu/~dsianita/695ec/failure.html
     "During its lifetime Pets.com spent more than $70 million on marketing and an average of $400 to acquire each new customer (Bucholtz, 2000)."
*** medley of Pets.com commercials
    https://www.youtube.com/watch?v=sICSyC9u5iI
*** So, was Pets.com they stupid?
*** Amazon.com
**** Profits stayed pretty flat two decades.
     https://www.statista.com/chart/14887/amazon-quarterly-profit/
**** but revenue, hence scale, have grown exponentially the whole time.
     https://www.statista.com/statistics/266282/annual-net-revenue-of-amazoncom/#:~:text=The%20time%20series%20shows%20the,billion%20US%20dollars%20in%202017.
**** They got big first, made money later.
*** "Growth first" is going out of style.
    https://www.theguardian.com/media-network/media-network-blog/2013/aug/06/growth-profits-social-media-platforms
** barrier to entry
   => Nobody can compete.
*** material monopoly
    Being the only one with access to raw materials -- e.g. diamonds.
*** information monopoly: methods for products (or services) that nobody else has.
    chemical formulas (Pfizer)
    data (Google)
    software (can be a weak barrier)
*** laws and regulations.
**** Licenses
***** Doctors
      Helps doctors & consumers.
***** Hair dressers?
      Helps already-licensed hair dressers.
      Hurts people who want to be hair dressers.
      Hurts some consumers, who would face lower prices if there were more hair dressers.
**** Section 230 of the 1996 US Communications Decency Act
     Platforms mostly cannot be held accountable (i.e. get in trouble) for their users' posts.
***** Freedom of speech does not apply.
      You have the right to speak, but not to speak on my website.
***** Craigslist shut down its personal ads.
      The " Allow States and Victims to Fight Online Sex Trafficking Act" (FOSTA)
      states that websites can now be punished for "facilitating" prostitution and sex trafficking.
      https://www.bbc.com/news/technology-43514645
***** Size & cost of filtering bad posts.
      Facebook, Youtube	: can afford it.
	(They use machines and humans to do that.)
      Startups		: can't.
****** startup = a small new company
*** scale (size) & network effects
**** network effects
     more people use it => it becomes more useful => more people use it => ...
***** amazon, uber, facebook, ebay, instagram
***** Why Google offers so many free services.
      Information => better ads.
***** Why Facebook bought Instagram and Whatsapp.
      Monopoly: Facebook can charge advertisers more if nobody else is like Facebook.
**** Google, Amazon, Facebook, Walmart : scale (size) protects them.
     Amazon ~ Mercado Libre.
     Walmart ~ Exito.
**** Uber (Didi, InDriver)             : not very protected by scale..
**** Facebook moderators and PTSD (post traumatic stress disorder)
     The term "PTSD" was first used in the vietnam war.
     Moderator = someone who vets posts, takes some of them down.
     52 million USD, 11,250 moderators
     https://www.theverge.com/2020/5/12/21255870/facebook-content-moderator-settlement-scola-ptsd-mental-health
** tech is weird
*** AI does not exist.
    https://lacker.io/ai/2020/07/06/giving-gpt-3-a-turing-test.html
**** machines are better at
     Arithmetic, memory, simple games.
       Chess. Memory. Poker (but only very recently).
     Anything you can program a perfect solution to.
**** humans are better at
     Recognizing pictures.
     Talking.
     Science.
     Cooking.
     Sports.
     Picking strawberries.
     Navigation (e.g. driving).
*** open-source software ("even freer" than free software)
    Free: you can use it, "have" it, but you don't get to see how it works.
    Open-source: you can see the source code, see how it works, modify it, share those modifications, etc.
**** example: Go (programming language) by Google
***** can't sell it
      There are too many other free languages already available.
***** want people to use it
      Google will hire some of them.
***** want to be famous, respected for helping others
***** want people to develop it
      Free labor!
*** If it's free, you are the product
    Users are the product.
    The customer is the advertiser.
    https://www.forbes.com/sites/marketshare/2012/03/05/if-youre-not-paying-for-it-you-become-the-product/?sh=15967bea5d6e
**** Facebook, Google receive most of their money from advertisers.
**** Lots of small websites used to, but much less now.
     Since Facebook and Google can target users more precisely,
     it's cheaper for advertisers to use them.
     Smaller websites are less attractive to advertisers,
     because it costs more money to reach interested people,
     because they have to spam lots of uninterested people,
     because the website does not know very much about its users.
*** squishy assets
    Hard to quantify. Impossible to touch.
    Some easy to copy, some very much not.
**** Standard Oil: company in the US
     "antitrust law" : breaks monopolies and oligopolies
**** data
**** algorithms
**** popularity
     Facebook has it, and is protected by it.
     Uber has it, but is not very protected by it.
* day 2
** reading
*** technological unemployment is not new
**** the Luddite rebellion
     https://www.history.com/news/who-were-the-luddites
**** optional: if you enjoyed that story, here are many more:
     https://www.blog.askwonder.com/blog/technological-unemployment
*** the 2017 Equifax hack
    https://en.wikipedia.org/wiki/2017_Equifax_data_breach#Criticism
    Read the introduction and the "criticisms" section. (And anything else you want, of course :)
*** Venezuelan money and art
    https://www.aljazeera.com/economy/2019/12/24/venezuelas-currency-worth-more-as-craft-paper-than-as-money
*** the dangers of unexplainable machine learning
    https://www.vox.com/future-perfect/2020/8/22/21374872/uk-united-kingdom-formula-predict-student-test-scores-exams
*** optional: how cryptocurrency works
    https://blog.revolut.com/how-cryptocurrency-works/
** Does tech destroy jobs?
*** Jobs that disappeared
**** The printing press (1440) replaced scribes.
**** Powered looms (1784) replaced weavers.
**** Tractors (1892) replaced farmers.
     Most humans lived on farms before 1900.
**** Trains (1804) replaced log operators
     Beyond rivers.
**** Ice-making machines (1854) replaced Ice cutters.
**** Email (1972) replaced copy boys.
     Beyond the office.
*** long-term, "unemployment" does not rise.
**** German unemployment since 1900
     Only obvious change is that it's more stable now.
     https://www.researchgate.net/figure/Unemployment-Rate-1900-1998_fig1_5051954
**** Colombian unemployment since 1980
     https://www.researchgate.net/figure/Behavior-of-unemployment-in-Colombia-Source-DANE_fig1_228559730
     https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.ceicdata.com%2Fdatapage%2Fcharts%2Fipc_colombia_unemployment-rate.svg&imgrefurl=https%3A%2F%2Fwww.ceicdata.com%2Fen%2Findicator%2Fcolombia%2Funemployment-rate&tbnid=3YYje6iBcZMm7M&vet=12ahUKEwjYi6nD5a3tAhVU21kKHbTNCCgQMygEegUIARCaAQ..i&docid=BjBBuj1SrjXV7M&w=1200&h=500&q=colombia%20unemployment%20since%201980&ved=2ahUKEwjYi6nD5a3tAhVU21kKHbTNCCgQMygEegUIARCaAQ
*** New tech => more wealth, new "distribution".
*** Humane approach: Train the displaced workers.
** the Equifax hack
*** Equifax is a "credit bureau".
*** the information revealed
    on more than 150 million people
    first and last names, Social Security numbers, birth dates, addresses and, in some instances, driver's license numbers for an estimated 143 million Americans,
    Credit card numbers for approximately 209,000 U.S. consumers, and certain dispute documents with personal identifying information for approximately 182,000 U.S. consumers were also accessed.[20][10]
*** the problem: sloppy security
    Basically they were cheap.
**** Slow to download and use security patches.
**** Bad data segmentation.
*** the personal information "externality"
    lost personal information ~ pollution
*** around half a billion dollars in fines
**** Net income (profit) in 2017 was about the same, half a billion dollars.
     https://investor.equifax.com/news-and-events/press-releases/2018/03-01-2018-213648628#:~:text=For%20the%20full%20year%202017,to%20the%20full%20year%202016.
*** was Equifax hurt?
**** Equifax stock price
     https://www.google.com/search?q=equifax+stock+price&oq=equifax+stock+price&aqs=chrome..69i57.5111j0j1&sourceid=chrome&ie=UTF-8
**** Experian stock price
     https://www.google.com/search?q=experian+stock+price&oq=experian+stock+price&aqs=chrome..69i57.5559j0j1&sourceid=chrome&ie=UTF-8
**** fines as a cost of business
*** "insider trading"
**** at Equifax
     three Equifax executives sold almost $1.8 million of their personal holdings of company shares days after Equifax discovered the breach but more than a month before the breach was made public.[59] The company said the executives, including the chief financial officer John Gamble,[60][34] "had no knowledge that an intrusion had occurred at the time they sold their shares".
**** what it is
     Trading of a firm's stock, or derivatives based on it, based on nonpublic information about it.
**** why that's illegal
*** they set up a website to check whether your info was stolen
**** that tried to remove visitors' right to participate in any "class action" lawsuit
     "The Trusted ID Premier website contained terms of use, dated September 6, 2017 (the day before Equifax announced the security breach) which included an arbitration clause with a class action waiver"
** privacy
*** Some kinds of private info online.
**** Income
**** Health problems
**** Sexual orientation, habits
*** Who has your information?
    The two biggest examples:
**** Facebook knows
***** who you know
***** what you like and dislike
**** Google knows
***** your search history
*** What is privacy?
**** a "negative freedom"
**** a "human right"
     Why?
****** The freedom to make mistakes.
       Without that, we stay stupid.
****** Just because we like it.
*** bargaining power and the GDPR
**** "bargaining power"
     = A negotiation in which one party is somehow special, and can therefore dictate the terms.
***** monopoly vs. consumers
***** firm vs. employees
***** many similar buyers and sellers
***** Putin and Trump
***** Facebook buying Whatsapp and Instagram
      maintain monopoly on social network data
****** can charge advertisers more
****** can give users a worse experience
       e.g. less data protection
**** some common bargaining power correctives
     laws and regulations
***** "antitrust law"
      to prevent monopoly
***** "class action lawsuits"
***** "labor union"
**** the "GDPR"
     The EU's "General Data Protection Regulation"
     https://gdpr.eu/what-is-gdpr/?cn-reloaded=1
***** principles
****** transparent
****** purpose-limitated
       Only collected for the purposes initially specified.
****** minimal
****** accurate, up to date
****** security
***** reaches beyond the EU
      "if you process the personal data of EU citizens or residents, or you offer goods or services to such people, then the GDPR applies to you even if you’re not in the EU."
** money and crypto
*** purpose
**** facilitate exchange
     Barter is inefficient -- see, e.g., Venezuela.
**** store value
     Doesn't always work -- see, e.g., Venezuela.
***** "inflation"
**** measure value
     Quantify anythinig -- chicken feathers, movies, injuries ...
*** Once, it was all metals and gems
    Useless and heavy! Who wants that?
*** Now, it is printed on paper by central authorities
**** Still useless, but more convenient.
**** First: China, 770 BC.
**** Countries make it difficult (and sometimes illegal) to use foreign currencies for domestic transactions.
     => central bank (government) can print more money, knowing it will be valued
*** "cryptocurrency"
**** decentralized
     No central authority prints money.
     Every miner has the ledger, processes transactions.
**** "volatility"
**** "private" and "public"
***** Address, amount, history: public.
***** Identity: private, kind of.
**** transaction speed
     Takes minutes.
     Consider Visa: takes seconds.
**** transaction costs
     Fluctuates, from 300 to 30,000 pesos, usually 3,000-ish.
     Compare: credit cards cost at least 1%.
***** "Fixed cost" v. "variable cost".
** "machine learning" (ML) and "explainability"
*** "neural networks"
**** are the most popular ML tool
***** powerful: can fit very complex data
***** flexible: can solve a wide variety of problems
**** are "trained" on data
**** guesses without explanation
*** ways they are used
**** predicting exam results during a pandemic
     https://www.vox.com/future-perfect/2020/8/22/21374872/uk-united-kingdom-formula-predict-student-test-scores-exams
**** "credit scores", loans
**** recidivism scores, "parole"
*** "garbage in, garbage out"
**** Why correlate on race, neighborhood, income, etc?
     Tables are easy to process automatically.
     Stories are not.
** some cool privacy technology research
*** "pseudonimity"
    Pseudonymous data => can't identify individuals.
**** examples
     "This neighborhood is rich."
     "People who listen to Bob Marley are less likely to vote."
*** the holy grail of electronic elections
    Private yet verifiable.
* quiz
** What is the purpose of money?
   Money is a store of value.
   Money facilitates exchange.
   Money is a unit of measure.
   Money is all of these things.
** What does a credit bureau like Equifax do?
   It lends money.
   It issues credit cards.
   It judges peoples' credit-worthiness.
   It measures the economy.
** Which of the following is an example of bargaining power?
   I have a nice truck, so I can sell it for a lot of money.
   Nuclear scientists can only work for the government, so the government does not need to pay them well.
   Voters control what a Senator does, because they can threaten to take away the Senator's job.
   I'm in a boat on a river, so I have no choice -- I must follow the river.
** Which of the following statements about technological advancement is FALSE?
   New technologies make some jobs disappear.
   New technologies make new jobs possible.
   New technologies do not change the total amount of wealth.
   New technologies change how wealth is distributed.
** In which of the following ways is Bitcoin better than cash?
   Bitcoin is easier to use.
   Bitcoin's value is more stable.
   Bitcoin is anonymous.
   Bitcoin cannot be inflated.
** Insider trading is unfair to
   the company whose stocks or derivatives are being traded
   other companies
   the insider doing the trading
   other traders
