#+title: wsgi and mod_wsgi
* some terms defined
** wsgi is a Python web interface
** mod_wsgi is an Apache module
 which can host any Python WSGI application, including Django.
* refs
** Configuring wsgi
https://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html#delegation-to-daemon-process
** asking here
 https://forum.djangoproject.com/t/do-i-need-apache-if-so-im-lost-configuring-it/4791
* TODO ? configure apache from /etc/apache2/mods-*/
  rather than its parent folder
* TODO ? HACK: set all relevant permissions to 777
This is overkill but it's the only thing I've gotten to work.
** adduser www-data www-data
This creates a user called "www-data",
and adds them to a similarly named group.
** chown -R www-data:www-data /var/www
** chmod -R g+rw /var/www
** cd <all my code & data> && chmod 777 -R .
In my case this was my learning-git repo.
* TODO ? configure WSGIDaemonProcess and WSGIProcessGroup
** I got wsgi to serve files without setting them.
** But a pssage that says to do so.
Here:
  https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/

I am told to "add the following options":
  WSGIDaemonProcess example.com python-home=/path/to/venv python-path=/path/to/mysite.com
  WSGIProcessGroup example.com

but not told *where* to add them.
** TODO remaining quesitons
*** Where to insert the passage's code?
 It looks like apache2.conf code, so that's where I'm trying it first.
*** How to replace example.com?
*** Should I just ignore the `python-home=/path/to/venv` part?
  since I don't use a virtual environment.
