#+title: 22-edo guitar (shopping)
* builders
pullsed from exactly the first page of Google search results
** can do it backward
*** Skervesen: can, but skeptical
 https://mail.google.com/mail/u/0/#inbox/FMfcgxwKjBPvFVnQMCRPbttssqgZXWxH
 can do "the lefty issue"; did not mention 22-edo
*** Overload guitars (see Facebook Messenger)
 Can do everything -- even 22-edo.
 At least 2K Euro.

 What would the price be for all that -- reversed fan, 22-edo, 25"-29" -- for a 7-string Raijin? 8-string Raijin? 7-string headless? 8-string headless?
** incomplete response
*** Kiesel
Can they backward? 22? Didn't say.
*** Mayones: can't, but didn't say which aspect (22 or backward)
*** Balaguer: can't, but didn't say which aspect (22 or backward)
*** Ormsby: won't reverse, but maybe 22 (still awaiting response)
** asked, no answer yet
*** Lichty
*** VanderMeij
* HANDY: What I'm asking
Multiscale guitar with long side of neck farther from face
----
Hi,

I'd like a multiscale guitar with the long side farther from the player's face. I've described why in detail here:

https://www.reddit.com/r/guitars/comments/jgyowj/multiscale_guitars_would_be_more_ergonomic_if_the/

I see three advantages. (1) The fretting hand does not have to twist when playing barre chords near the nut. (2) The path of the strumming hand aligns better with the bridge (assuming the bridge is slanted too, not just the nut). (3) A more extreme difference in scale length will still be playable.

I'll have to learn to play differently, but I don't think it will be hard, since the shapes won't change, just their orientation.

Could I buy a guitar like that from you? I'm not sure what model to ask for, you offer a lot of them! I just want something simple and solid, nothing fancy -- except that I'd like to have at least 7 strings.

And if you could give it 22 frets to the octave instead of 12, that would be fantastic -- but if not, no worries, I'll just ask the folks at Metatonal Music to make another neck.

Thank you,
Jeff
* Schecter Reaper-7 Multiscale
$950
https://www.sweetwater.com/store/detail/Reap7MSCB--schecter-reaper-7-multiscale-satin-charcoal-burst?utm_source=gearank.com&utm_medium=7-string-guitar&utm_campaign=hitsquad2017&utm_content=top_table
* asking about backward multiscale on Reddit
https://www.reddit.com/r/guitars/comments/jgyowj/multiscale_guitars_would_be_more_ergonomic_if_the/
