#+title: Apache and mod_wsgi: Using Them with Django
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/
* PITFALL: sites can clobber each other
"""
Warning

If multiple Django sites are run in a single mod_wsgi process, all of them will
use the settings of whichever one happens to run first. This can be solved by
changing:

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{ project_name }}.settings")

in wsgi.py, to:

os.environ["DJANGO_SETTINGS_MODULE"] = "{{ project_name }}.settings"

or by using mod_wsgi daemon mode and ensuring that each site runs in its
own daemon process.
"""
* PITFALL: Django recommend separate Apache instances
for Django and other work, if I need Apache outside of the Django context too
(because I'm hosting multiple sites in the same domain).
** quote from the docs
"""
  If, however, you have no option but to serve media files on the same Apache
  VirtualHost as Django, you can set up Apache to serve some URLs as static
  media, and others using the mod_wsgi interface to Django.
"""
** I can for some reason ignore the VirtualHost mentioned in that passage.
according to
https://forum.djangoproject.com/t/do-i-need-apache-if-so-im-lost-configuring-it/4791/2
* TODO first [[file:20201014163254-wsgi.org][configure wsgi]]
* TODO BLOCKED: asking
https://forum.djangoproject.com/t/do-i-need-apache-if-so-im-lost-configuring-it/4791
* TODO configure Apache to serve some of the site
See "Serving files" here:
  https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/
