#+title: wsgi and mod_wsgi
* some terms defined
** wsgi is a Python web interface
** mod_wsgi is an Apache module
 which can host any Python WSGI application, including Django.
* refs
** Configuring wsgi
https://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html#delegation-to-daemon-process
** asking here
 https://forum.djangoproject.com/t/do-i-need-apache-if-so-im-lost-configuring-it/4791
* TODO | PITFALL ? configure apache from /etc/apache2/mods-*/
  rather than its parent folder
* permissions are tricky
The Docker image deals with them, as of version
    ofiscal/tax.co:2020-10-16.apache-access
* TODO ? configure WSGIDaemonProcess and WSGIProcessGroup
** wsgi is working without them.
** But a pssage that says to do so.
Here:
  https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/

I am told to "add the following options":
  WSGIDaemonProcess example.com python-home=/path/to/venv python-path=/path/to/mysite.com
  WSGIProcessGroup example.com

but not told *where* to add them.
** TODO remaining quesitons
*** Where to insert the passage's code?
 It looks like apache2.conf code, so that's where I'm trying it first.
*** How to replace example.com?
*** Should I just ignore the `python-home=/path/to/venv` part?
  since I don't use a virtual environment.
