:PROPERTIES:
:ID:       6502419e-c0f2-480d-9a69-ba1fbedb37d1
:END:
#+title: Andrew Fenlon on using r/wallstreetbets
 you can look at what stocks are being hyped on WSB. These are generally stocks I would avoid, as calls will already have risen in value. there are a lot of different software projects following the main "daily moves" feed, my personal favorite is here http://dayminer.herokuapp.com/. you can click on the different ticker symbols and read the mentions, etc. so to be clear, I personally think you'd be a fool to put money into palantir, gme or sundial growers, those ships have certainly sailed. but also, if there is hype and you ALREADY own the stock that's being hyped you can know when to sell. and if you insist on buying in and riding the hype train OTM calls are a good way
As for the DD section, some of the posts are excellent. I'm still a bit new to options trading but today I bought an OTM call of RKT. I've done well with most of the DD posts in the past, but I've also been careful. consider it a gamble and once it goes green -- get out
