:PROPERTIES:
:ID:       b2a88e6f-6481-4b4d-9645-fe3376345f01
:END:
#+title: Claro-hogar-internet
* paying Claro
** the website
   https://portalpagos.claro.com.co/
** TODO is the "Cuenta o Ref. de Pago" always this?
   60155948
** PITFALL: The service can hang
   If I click Boton Bancolombia, it will wait for a not-forthcoming response from Bancolombia, and meanwhile won't let me attempt any other payment method. I'll have to wait for it to timeout.
** PITFALL: Never click Boton Bancolombia
* TODO canceling claro for 402 Urapanes
** DONE
   I'm 99% sure I did this -- someone came and picked it up --
   and 95% sure they then called me to ask if it had happened,
   and I said yes. That may have been January, or before.
   It's March 6 2021 today.
** take the modem to a service center
** call gauntlet
   2 2 1 9
** #s de radicado
first one:               80 67 85 689
next, a few weeks later: 810 696 295
** hablé con Shirley Tovar, Oct 26 2020
** probably obsolete
*** things to press, in order
**** 2 for internet
**** 1 for bullshit
**** 3 to cancel
*** silence means I win ("silencio positivo")
