#+title: ctrlf (Emacs package)
* commands
** to enter it
*** C-s: ctrlf-forward-literal
*** C-r: ctrlf-backward-literal
*** C-M-s: ctrlf-forward-regexp
*** C-M-r: ctrlf-backward-regexp
*** M-s _: ctrlf-forward-symbol
    Does not match if the search string is part of a bigger symbol.
*** M-s .: ctrlf-forward-symbol-at-point
** change search method
*** M-c and M-s c: Toggle case sensitivity.
    By default, search is case-sensitive only if your search contains uppercase letters, like in Isearch (following the logic in isearch-no-upper-case-p).
*** M-s s: Cycle search style among
    literal, regexp, symbol, fuzzy, fuzzy-regexp
*** M-r and M-s r: Toggle between regexp and literal search style.
*** M-s _: Toggle between symbol and literal search style.
** change input
*** M-s .: Change the search input to the symbol at point, and change the search style to symbol.
*** M-n at start of session: search for symbol at point.
** jump between matches
*** C-s: next match
    With prefix argument, also convert a regexp search back to a literal search.
    If there is no search query, insert the previous one, as if you had typed M-p.
*** C-r: prev match
    With prefix argument, also convert a regexp search back to a literal search.
    If there is no search query, insert the previous one, as if you had typed M-p.

*** C-M-s: Move to next match and convert a literal search to a regexp search.
*** C-M-r: Move to previous match and convert a literal search to a regexp search.
*** M-<: first match.
*** M->: last match.
*** C-v: down page-ish
    Move to first match that appears below the currently visible part of the buffer.
*** M-v: up page-ish
    Move to first match that appears above the currently visible part of the buffer.
** exit
*** RET: Finish search, leaving point at the currently selected match.
*** C-g: Abort search, returning point to its original location.
** misc
*** M-s o: Open an Occur buffer with the existing search input.
*** C-l: Bounce center (as usual)
* faces can be customized
* the match number is displayed
** always in the minibuffer
** if desired, at the end of the matched line
  If ctrlf-show-match-count-at-eol is non-nil (the default), then this information is also shown at the end of the current line in the buffer being searched, which alleviates the problem of needing to look back and forth between the minibuffer and the buffer being searched.
* by default the cursor goes to the end of a match
  If ctrlf-go-to-end-of-match is nil, then the cursor will move to the beginning of the match instead of the end.
* some of the search styles
** fuzzy:        change " " to ".*"
   Split the query string on spaces and search for an occurrence of all the sub-parts separated by arbitrary text. To include a literal space, or more than one, simply add an additional space. For example, foo $42 baz quux is turned into foo.*\$42.*baz quux.
** fuzzy-regexp: change " " to ".*"
