:PROPERTIES:
:ID:       b1825284-2eca-45f9-b66f-5861089c8905
:END:
#+title: 2022 Easter: Sandy and I visit Popayan
  We just got back from Popayan, a little town (300K people?) in the southwest of Colombia, between Cali and Ecuador. It's coca country, so there are lots of soldiers and cops, and very distant police helicopter sirens sometimes which were surprisingly soothing. We stayed on a "finca", which is a plot of land that would have been used for farming until recently, and still is in a half-assed way but they make more money from the little store they run on the corner and renting out the space on AirBnB. It's almost always cloudy, and near a big volcano which Sandy was happy not to be able to see. Sunday we went to some volcanic hot springs. They actually pipe the volcanic water down the mountain into some stone pools, where it's mixed with cold mountain water so it doesn't burn you. It was dark green; I protected myself from the sun by spending a lot of time a couple feet underwater where the sun hardly reached.

  The next day my friend Bran pointed out that they probably didn't test for radioactivity. It felt healthy at the time and I feel fine now; I'll let you know if I sprout more arms. (I've always wanted more of those.)

  Popayan is extremely Catholic. They've got a lot of wooden relics from the 1500s and onwards of Jesus and Mary and Joseph or whatever, people looking serious or bleeding on a cross. Every Easter they parade them a few kilometers through the town. Eight guys the same height stand under each float; each of them bears a load of around 50 kg, from maybe 8 pm until 1 am. They don't bear it the whole time; when they're standing still they rest the float on sticks. A huge drum beats every four seconds or so, and they take a step. There are also other people in various costumes, including some priest-looking guys with crosses. No dancing, no smiles, moving at a fraction of a kph. In recent memory one of the lifters died of a heart attack. People fight (not literally) and pay (literal money) for the honor of being in the parade.

  Also tried out a couple different VR headsets at the arcade at the mall, and didn't get sick, so now I plan on getting an Oculus so I can have fun exercising without my left leg, which is recovering from a torn meniscus. (Warm up before stretching if it's cold! And if your spine is vertical, it's a bad idea to bend your knee as far as it can go in the horizontal plane, despite what yogis may suggest.)
