:PROPERTIES:
:ID:       bf95504f-ab6d-4868-b9d0-285f2b57cfe5
:END:
#+title: 2022 06 20, I announced probably Covid to family (esp. Ellen) and Josh
I got sick last Saturday, 9 days ago. It felt like a normal cold. I asked a doctor to test me for Covid anyway, just in case. They came to my place, asked me questions, measured various things, and told me it was just a normal cold. I asked to get a real covid test so I could be sure, and they were like no.

Sandy explained to me later that those tests cost a lot of money and the government had decided to cut back.

Sandy herself eventually seemed to get whatever I have. She was pretty sick for a day, and within two after that she seemed basically normal.

I got to LA yesterday around 11 am yesterday, and spent the day with my dear, sweet, unvaccinated mother. We got Indian food, went home, I slept, she slept, we hung out doing nothing in particular. This morning she took me to the airport. I tried to wear a mask when we were in a car together, and to only hug where there was a breeze. She kept saying she's not scared. I definitely let my guard down a few times. We spent a while in her room talking about something before I remembered to open the windows.

Today I got to my friends Bran and Jamie in Portland, at whose house I'm staying at. They had a couple of at-home covid tests. I took one. It seemed to say I had Covid, but we weren't sure because the top line was faint. (The instructions didn't say how to interpret that possibility.) So I took a different kind. It said, unambiguously, that I have Covid.

I think I'm supposed to quarantine for fitteen days from the onset of symptoms, i.e. from Sunday the 12th.

I'm willing to hang out with anyone outside. Any other kind of social activity seems like a bad idea.
