:PROPERTIES:
:ID:       4d15b8f9-ec38-4e2f-9733-187fbc27f86d
:END:
#+title: 2023 05 06, birthday weekend in Cachipay with Sandy, as narrative
Our tour guide said the town we stayed in -- Villeta, I think? which is near but not equal to Cachipay, and whose name I have forgotten -- was economically thriving until the train died due to federal neglect. Prior to that people would stop there because it's halfway up the mountain to Bogota, in order to adjust to the altitude. Now it's very sleepy. A maybe 24-seater bus comes by every 20 minutes to take people to Cachipay, the bigger town, from which you can take a bus to the capital.

The hotel is *really* nice. Sandy blew like 20% of her month's pay on the trip. It has a number of small (probably artificial, but using natural streams) waterfalls. The biggest has a lot of hammocks nearby where we took a nap that was mostly delicious except for the screaming woo girls who woke me maybe four times. Going near a waterfall is apparently terrifying, even after the fifth time. Some other vacationing Colombians, I think a on a girls' party before a wedding (what are those called?) and their love of bass speakers almost ruined the night for me, but fortunately we had the foresight to ask for a room far from any likely loud activity. I could hear the bass but not the rest of the music, and managed to sleep well despite it.

Colombians love to sing while drunk.

There was a sauna, a jacuzzi, a steam room. We used them, and in the process got to know a little bit the family and their giant poodle that took *exactly* the same trip we had, from Bogota onto one bus onto another to the hotel overnight then onto another bus and finally to the fourth bus. Even once we were in the terminal in Bogota we ended up walking a long ways together. Some people think Jesus rode into Jerusalem on a donkey because he knew the prophecies said that the savior would do that. This wasn't like that; we genuinely happened to have to go to the same place. I wasn't allergic to their dog, but that's likely because because I wore masks on the bus and we kept the windows open. (I wear masks for pollution now, and they very obviously help. Short of some crazy mutation I'm not scare of Covid any more. I also breathe deeply in anticipation of diesel-powered traffic so that I can hold my breath when I need to.)

We played ping pong. We're very evenly matched.

We played chess on an oversized (like 5 feet to a side) chess table at night while we waited for the music to stop, until I decided it wouldn't.

We played with a cool old-fashioned wire bingo machine. I studied the intervals of 58-edo (31-edo is so 2020), listened to The Economist, ignored the small torrent of electronic birthday messages (notably smaller now that I've stopped saying happy birthday to people I barely remember on Facebook)

I played marimba for the first time in my life, because there was one. It's an interesting instrument. You've only got two octaves of the white notes of a piano. The lack of harmonic potential means you've got to focus on things like rhythm and cadence (cadence being, e.g., the way you wrap up a verse when it feels like it's time), which I found a surprisingly fun exercise.

I *really* enjoyed the wildlife we saw. It wasn't even that much -- some weird bugs, butterflies, small dagger-shaped birds, and some bizzarre plants. My favorite were these things that look like giant (up to three feet across) coconus sprouting leaves, hanging in the air. They evolved to grow on other trees, but they'll grow on signposts or whatever too. Also some kind of tree that resembles bamboo but has leaves that curl into a tube spaced regularly along its trunk, which fill in and turn into actual branches as you look further up the tree.

70 tourists (the guide counted), a tour guide, Sandy and I hiked to a waterfall called Salto de los Monjes (which means "Monks' Jump", but so named because "monje" is also used as a name of a local species of bee) on the second day. At least ten of the other vacationers took their dogs, and at least eight more that live in the town came with us. Two were strays. The tour guide knew them all. They didn't get food out of it; they just like the hike, and him. At one point they tried to harass a horse. It didn't care.

The hike starts out steeply downhill, sometimes flattens out but stays pretty steep most of the time, and then you get near the waterfall and it becomes extremely steep and full of stone and plant obstacles. Right before that, we hung back from the others so that I could pee. Once they were gone I walked down a sidepath, straight into some barbed wire that neither of us had seen. Didn't break the skin, thank goodness. Might have needed another tetanus shot.

The waterfall has a few pools you can hang out in -- which I *knew*, because we'd been there a few years ago during the pandemic with Diana, Sofi and Diego, but I had forgotten. So I hung out in the crowded first pool under the waterfall, having forgotten the other pool existed. Sandy didn't want to get wet. Some guys showed up on mountain bikes after we did. I imagine they had to walk those bikes a lot.

Hiking back was, predictably, murder. Somehow after that we dragged ourselves to a restaurant, ate, and schlepped back to Bogotá. Sandy had to go to work today, as she's been doing every day for the last few weeks. They officially transferred her to education, I think, or at least now she has an ID that says that's where she works. I was able to work from home, and you can bet I did.
