:PROPERTIES:
:ID:       28fea50f-0af8-4300-b04d-eb29b1345959
:END:
#+title: <2025-03-24 Mon> saw Anora with friends. It was good.
* I wrote, sent
** The initial abrupt early termination of a good song when she left work seemd perfect -- it reflected both the story of the marriage and the disconnect between experiences of the clients and the employees in a strip club.
** Ivan does not seem to have been lying to Anora when he proposed and when they married. That kind of premeditation would require Ivan to be cold, calculating, and good at hiding his feelings -- none of which he was. Ivan learned he needed his parents more than love. When he ran away he probably intended to find some way to continue resisting. While away he realized it was hopeless, that he could not stay married to Anora because he would have nothing, so he gave up on the marriage. But he does not seem to have taken advantage of Anora.
** Anora received an offer she was not looking for, which seems to have been genuine, and she took it like any reasonable person would have. Ivan seemed cool, and the lifestyle was way better than stripping.
** Anora was belligerent in a fun way.
** I did not see the negative stereotypes Lu was so hostile to. Anora was not looking to be rescued, did not take advantage of Ivan, and was generally heroic, in a realistically traumatized way.
** The parents' henchmen did not like their job.
** Igor genuinely seems to have cared about Anora.
** Ivan's dad was amused, which was hilarious.
** The only unrealistic-seeming person was Ivan's mother, who seemed to delight in threatening Anora.
** The amount of sex seemed appropriate. It was probably a lesser fraction of the movie than it would have been of the marriage. It's not clear to me why to minimize that time.
* Ana and I discussed
** Ana - Buena defensa btw, algo mas.  Las instituciones y la ley estan en crisis (salvo cuando no pudieron anular el matrimonio en NYC) de resto los poderosos pueden pasar por encima de todo.
** Me - También importante -- pero pues en la pelicula eso se pudó decir solamente de los ricos con voluntad de usar violencia. Si no hubiera por las amenazas de la mamá, podría haber sido muy diferente.
* Natalia and I discussed
** Her: [audio, says she'd add that it was a more realistic description of (prostitution, I think she said), in contrast to Pretty Woman]
** Me - No puedo opinar fuertemente sobre la realidad de la vida de un stripper pero sospecho que sí, lo que vimos fue realista. He escuchado historias de personas en esa industria que salen demasiado dañadas, otras que lo soportan como un trabajo duro y ya, y otras que en realidad les gusta. Pero el ambiente laboral rutinario probablemente no está lleno de los extremos emocionales, sino de lo que cualquier entorno laboral contiene -- cámara, peleas y camello.
