:PROPERTIES:
:ID:       7dd9c689-51f9-45da-bbd1-d3068615917a
:END:
#+title: 34-edo
* harmonic theory
** 15\34 - 19/14 < 1 cent
   Because 34-edo's best 19/16 and 7/4
   are both 15 cents flat.
   (They therefore play horribly with the other harmonics.)
* layouts
** TODO 3\34r x 8\34d (11\34dr): a bit skew, incredibly compact
   The only harmonic it sacrifices is 7, which good!
*** layout

    1 17  9  -  -  - 23  - 13  7  -  -  -  - 19  5  -  -  3  -  -
   19  5  -  -  3  -  -  -  -  -  -  -  - 21 11  -  -  -  - 15  1
   11  -  -  -  - 15  1 17  9  -  -  - 23  - 13  7  -  -  -  - 19
   13  7 xx  -  -  - 19  5  -  -  3  -  -  -  -  -  -  -  - 21 11
    -  -  -  -  - 21 11  -  -  -  - 15  1 17  9  -  -  - 23  - 13
    9  -  -  - 23  - 13  7  - xx  -  - 19  5  -  -  3  -  -  -  -
    -  -  3  -  -  -  -  -  -  -  - 21 11  -  -  -  - 15  1 17  9
    -  -  - 15  1 17  9  -  -  - 23  - 13  7  -  - xx  - 19  5  -
    -  -  -  - 19  5  -  -  3  -  -  -  -  -  -  -  - 21 11  -  -
    -  -  - 21 11  -  -  -  - 15  1 17  9  -  -  - 23  - 13  7  -
    -  - 23  - 13  7  -  -  -  - 19  5  -  -  3  -  -  -  -  -  -
               xx = some keys separated by Bosanquet octaves

** TODO 4\34 x 7\34dr = 3\34d: *very* flat, Bosanquet octaves
*** (*) its biggest jump
    from (6,0) to (-2,2) = right one and down four
*** layout
**** as 4\34 x 7\34dr
     6 steps;  9 % 8; string -2; fret 2
     0 steps;  1 % 1; string  0; fret 0
    11 steps;  5 % 4; string  1; fret 1
    16 steps; 11 % 8; string  4; fret 0
    20 steps;  3 % 2; string  5; fret 0
    27 steps;  7 % 4; string  5; fret 1
    24 steps; 13 % 8; string  6; fret 0
    31 steps; 15 % 8; string  6; fret 1
    34 steps;  2 % 1; string  5; fret 2
**** as 4\34 x 3\34d
***** in text
      00 steps; 1  % 1;  string 0; fret 0
      03 steps; 17 % 16; string 0; fret 1
      06 steps; 9  % 8;  string 0; fret 2
      11 steps; 5  % 4;  string 2; fret 1
      18 steps; 23 % 16; string 3; fret 2
      20 steps; 3  % 2;  string 5; fret 0
      24 steps; 13 % 8;  string 6; fret 0
      31 steps; 15 % 8;  string 7; fret 1
      34 steps; 2  % 1;  string 7; fret 2
***** picture

      15 -  -  -  21 -  -  -  -  -  17 -  5  -  -  -  7  15
      1  -  19 -  11 3  13 -  -  -  9  -  -  23 -  -  -  2
      17 -  5  -  -  -  7  15 -  -  -  21 -  -  -  -  -  17
      9  -  -  23 -  -  -  1  -  19 -  11 3  13 -  -  -  9
      -  21 -  -  -  -  -  17 -  5  -  -  -  7  15 -  -  -
      -  11 3  13 -  -  -  9  -  -  23 -  -  -  1  -  19 -
      -  -  -  7  15 -  -  -  21 -  -  -  -  -  17 -  5  -
      23 -  -  -  1  -  19 -  11 3  13 -  -  -  9  -  -  23
      -  -  -  -  17 -  5  -  -  -  7  15 -  -  -  21 -  -

** 4\34 x 1\34u: octave 8-2, fret height 4
*** layout
**** numbers
     00 steps; 1  % 1; string 0; fret 0
     06 steps; 9  % 8; string 1; fret 2
     11 steps; 5  % 4; string 3; fret -1
     16 steps; 11 % 8; string 4; fret 0
     20 steps; 3  % 2; string 5; fret 0
     24 steps; 13 % 8; string 6; fret 0
     27 steps; 7  % 4; string 6; fret 3
     31 steps; 15 % 8; string 7; fret 3
     34 steps; 2  % 1; string 8; fret 2
**** picture

     -  17 -  5  -  -  -  7  15 -  -  -  21 -  -  -
     1  -  19 -  11 3  13 -  -  -  9  -  -  23 -  -
     -  -  -  21 -  -  -  -  -  17 -  5  -  -  -  7
     -  9  -  -  23 -  -  -  1  -  19 -  11 3  13 -
     17 -  5  -  -  -  7  15 -  -  -  21 -  -  -  -
     -  19 -  11 3  13 -  -  -  9  -  -  23 -  -  -
     -  -  21 -  -  -  -  -  17 -  5  -  -  -  7  1
     9  -  -  23 -  -  -  2  -  19 -  11 3  13 -  -
     5  -  -  -  -  7  15 -  -  -  21 -  -  -  -  -

** TODO 8\34 x -3\34: flat, weird (3:2 at (4,4)), Bosanquet octaves
*** PITFALL: This layout includes manual mods.
    bestLayout' gives some very vertical positions.
    I put flatter ones.
     [ 0  steps; 1  % 1; string 0; fret  0
     , 6  steps; 9  % 8; string 0; fret -2
     , 11 steps; 5  % 4; string 1; fret -1
     , 20 steps; 3  % 2; string 1; fret -4
                         string 4; fret  4
     , 16 steps; 11 % 8; string 2; fret  0
     , 24 steps; 13 % 8; string 3; fret  0
     , 27 steps; 7  % 4; string 3; fret -1
     , 31 steps; 15 % 8; string 2; fret -5
                         string 5; fret  3
     , 34 steps; 2  % 1; string 2; fret -6
                         string 5; fret  2
** DONE 7\34r x 3\34dr: flat*, 15-lim in 4x4, good on Lumatone
*** equal to 7\34r x 4\34u
*** (*) its biggest jump
    (2,-1) to (1,3) = downright 3 and left 1
*** layout
**** numbers
     6  steps;  9 % 8; string 0; fret 2
     16 steps; 11 % 8; string 1; fret 3
     11 steps;  5 % 4; string 2; fret -1
     20 steps;  3 % 2; string 2; fret 2
     24 steps; 13 % 8; string 3; fret 1
     28 steps; 16 % 9; string 4; fret 0
     31 steps; 15 % 8; string 4; fret 1
     34 steps;  2 % 1; string 4; fret 2
**** picture

    19 -  -  -  -  -  -
    -  5  23 -  -  -  -
    1  -  -  -  -  -  -
    -  17 -  -  13 15 -
    -  -  9  21 3  7  2  x
    -  -  -  -  11 -  -
    x = where the octave would be
    if the layout were Bosanquet

*** why I'm including 16%9
    It is the sharp approximation to 7%4.
    The flat, more accurate 7%4
    plays badly with the others.
** TODO 2\34 x 9\34: 2 at 4:-1, beatuiful 4:5:6:7:8, good for guitar
   but Kite seems better without crazy many strings
*** layout in numbers
    0  steps;  1 % 1; string 0; fret 0
    6  steps;  9 % 8; string 0; fret 3
    11 steps;  5 % 4; string 1; fret 1
    16 steps; 11 % 8; string 2; fret -1
    20 steps;  3 % 2; string 2; fret 1
    24 steps; 13 % 8; string 2; fret 3
    27 steps;  7 % 4; string 3; fret 0
      # Try not to use this -- it's very flat,
      # and plays badly with the others.
      # Rather use the sharper 7%4,
      # at 28 steps, (4,-3) or (2,6)
    31 steps; 15 % 8; string 3; fret 2
    34 steps;  2 % 1; string 4; fret -1
*** layout as a picture

          headstock on this side
             - 15  9  - 13  -
            13  - 19  -  -  -
             -  -  -  -  - 17
             - 17  -  -  -  -
             -  -  -  -  -  -
    bass     -  - 11  -  1  -  treble
    side     -  - 23  7  -  5  side
             -  5  3  -  - 21
             - 21  - 15  9  -
             9  - 13  - 19  -
            19  -  -  -  -  -
           bridge on this side

** 5\34 x 2\34u: octave 8-3, fret height 4
   00 steps; 1  % 1; string 0; fret 0
   06 steps; 9  % 8; string 2; fret -2
   11 steps; 5  % 4; string 3; fret -2
   16 steps; 11 % 8; string 4; fret -2
   20 steps; 3  % 2; string 4; fret 0
   24 steps; 13 % 8; string 6; fret -3
   27 steps; 7  % 4; string 7; fret -4
   31 steps; 15 % 8; string 7; fret -2
   34 steps; 2  % 1; string 8; fret -3
** 5\34 x 1\34u: octave 7-1, fret height 4, everything but 7:4 near-linear
   00 steps; 1  % 1; string 0; fret 0
   06 steps; 9  % 8; string 1; fret 1
   11 steps; 5  % 4; string 2; fret 1
   16 steps; 11 % 8; string 3; fret 1
   20 steps; 3  % 2; string 4; fret 0
   24 steps; 13 % 8; string 5; fret -1
   27 steps; 7  % 4; string 6; fret -3
   31 steps; 15 % 8; string 6; fret 1
   34 steps; 2  % 1; string 7; fret -1
** 7\34 x 1\34
   00 steps;  1 % 1; string 0; fret 0
   06 steps;  9 % 8; string 1; fret -1
   11 steps;  5 % 4; string 1; fret 4
   16 steps; 11 % 8; string 2; fret 2
   20 steps;  3 % 2; string 3; fret -1 (2,6)
   24 steps; 13 % 8; string 3; fret 3
   27 steps;  7 % 4; string 4; fret -1 (3,6)
   31 steps; 15 % 8; string 4; fret 3
   34 steps;  2 % 1; string 5; fret -1 (4,6)
