:PROPERTIES:
:ID:       7dd9c689-51f9-45da-bbd1-d3068615917a
:END:
#+title: 34-edo
* TODO 4\34 x 7\34: flat*, Bosanquet octaves
** (*) its biggest jump
   from (6,0) to (-2,2) = right one and down four
** layout
    6 steps;  9 % 8; string -2; fret 2
    0 steps;  1 % 1; string  0; fret 0
   11 steps;  5 % 4; string  1; fret 1
   16 steps; 11 % 8; string  4; fret 0
   20 steps;  3 % 2; string  5; fret 0
   27 steps;  7 % 4; string  5; fret 1
   34 steps;  2 % 1; string  5; fret 2
   24 steps; 13 % 8; string  6; fret 0
   31 steps; 15 % 8; string  6; fret 1
* TODO 8\34 x -3\34: flat, weird (3:2 at (4,4)), Bosanquet octaves
** PITFALL: This layout includes manual mods.
   bestLayout' gives some very vertical positions.
   I put flatter ones.
    [ 0  steps; 1  % 1; string 0; fret  0
    , 6  steps; 9  % 8; string 0; fret -2
    , 11 steps; 5  % 4; string 1; fret -1
    , 20 steps; 3  % 2; string 1; fret -4
                        string 4; fret  4
    , 16 steps; 11 % 8; string 2; fret  0
    , 24 steps; 13 % 8; string 3; fret  0
    , 27 steps; 7  % 4; string 3; fret -1
    , 31 steps; 15 % 8; string 2; fret -5
                        string 5; fret  3
    , 34 steps; 2  % 1; string 2; fret -6
                        string 5; fret  2
* DONE 7\34 x 3\34: flat*, 15-lim in 4x4, good on Lumatone
** (*) its biggest jump
   (2,-1) to (1,3) = downright 3 and left 1
** layout
   6  steps;  9 % 8; string 0; fret 2
   16 steps; 11 % 8; string 1; fret 3
   11 steps;  5 % 4; string 2; fret -1
   20 steps;  3 % 2; string 2; fret 2
   24 steps; 13 % 8; string 3; fret 1
   28 steps; 16 % 9; string 4; fret 0
   31 steps; 15 % 8; string 4; fret 1
   34 steps;  2 % 1; string 4; fret 2
** why I'm including 16%9
   It is the sharp approximation to 7%4.
   The flat, more accurate 7%4
   plays badly with the others.
* TODO 2\34 x 9\34: 2 at 4:-1, good for guitar
  but Kite seems better without crazy many strings
** layout
   0  steps;  1 % 1; string 0; fret 0
   6  steps;  9 % 8; string 0; fret 3
   11 steps;  5 % 4; string 1; fret 1
   16 steps; 11 % 8; string 2; fret -1
   20 steps;  3 % 2; string 2; fret 1
   24 steps; 13 % 8; string 2; fret 3
   27 steps;  7 % 4; string 3; fret 0
     # Try not to use this -- it's very flat,
     # and plays badly with the others.
     # Rather use the sharper 7%4,
     # at 28 steps, (4,-3) or (2,6)
   31 steps; 15 % 8; string 3; fret 2
   34 steps;  2 % 1; string 4; fret -1
* 7\34 x 1\34
  00 steps;  1 % 1; string 0; fret 0
  06 steps;  9 % 8; string 1; fret -1
  11 steps;  5 % 4; string 1; fret 4
  16 steps; 11 % 8; string 2; fret 2
  20 steps;  3 % 2; string 3; fret -1 (2,6)
  24 steps; 13 % 8; string 3; fret 3
  27 steps;  7 % 4; string 4; fret -1 (3,6)
  31 steps; 15 % 8; string 4; fret 3
  34 steps;  2 % 1; string 5; fret -1 (4,6)
