:PROPERTIES:
:ID:       7e14ddd3-673c-4938-adb8-29696ab2ff96
:END:
#+title: 46-edo
* [[id:7dcff6ba-7086-4c81-bf95-6dc12e8ae897][46-edo is fat-finger friendly with 92-edo.]]
* layouts
** TODO 5\46 x 2\46: Lumatone-good, 15-lim in 8x4
*** layout
    00 steps; 01 %  1; string 0; fret 0
    04 steps; 17 % 16; string 0; fret 2
    08 steps; 09 %  8; string 0; fret 4 | string 2; fret -1
    11 steps; 19 % 16; string 1; fret 3
    15 steps; 05 %  4; string 3; fret 0
    18 steps; 21 % 16; string 2; fret 4 | string 4; fret -1
    21 steps; 11 %  8; string 3; fret 3 | string 5; fret -2
    24 steps; 23 % 16; string 4; fret 2
    27 steps; 03 %  2; string 5; fret 1
    30 steps; 25 % 16; string 6; fret 0
    32 steps; 13 %  8; string 6; fret 1
    35 steps; 27 % 16; string 7; fret 0
    37 steps; 07 %  4; string 7; fret 1
    39 steps; 29 % 16; string 7; fret 2
    42 steps; 15 %  8; string 8; fret 1
    44 steps; 31 % 16; string 8; fret 2
    46 steps; 02 %  1; string 8; fret 3
*** comparison: very similar to [[id:a291f843-ee45-40e9-923e-badfe65654a7][6\58 x 5\58]]
    On average they both move up 127c each horizontal step.
    The 46-edo layout has much more convenient 5:4, 3:2 and 9:8.
    Their 11:8s and 2:1s are very slightly different.
    Every other harmonic is in the same place.
    46-edo will require far less transposition, if any.
    Both are equally horizontal.
** 9\46 x 1\46: My benchmark, 13- and 31-lim both in 5x7
   0  steps;  1 % 1;  string 0; fret 0
   46 steps;  2 % 1;  string 5; fret 1
   27 steps;  3 % 2;  string 3; fret 0
   15 steps;  5 % 4;  string 1; fret 6
   37 steps;  7 % 4;  string 4; fret 1
   8  steps;  9 % 8;  string 1; fret -1
   21 steps; 11 % 8;  string 2; fret 3
   32 steps; 13 % 8;  string 3; fret 5
   42 steps; 15 % 8;  string 4; fret 6
   4  steps; 17 % 16; string 0; fret 4
   11 steps; 19 % 16; string 1; fret 2
   18 steps; 21 % 16; string 2; fret 0
   24 steps; 23 % 16; string 2; fret 6
   30 steps; 25 % 16; string 3; fret 3
   35 steps; 27 % 16; string 4; fret -1
   39 steps; 29 % 16; string 4; fret 3
   44 steps; 31 % 16; string 5; fret -1
** 6\46 x 1\46
   0  steps;  1 % 1; string 0; fret 0
   8  steps;  9 % 8; string 1; fret 2
   15 steps;  5 % 4; string 2; fret 3
   21 steps; 11 % 8; string 3; fret 3
   27 steps;  3 % 2; string 4; fret 3
   32 steps; 13 % 8; string 5; fret 2
   37 steps;  7 % 4; string 6; fret 1
   42 steps; 15 % 8; string 7; fret 0
   46 steps;  2 % 1; string 7; fret 4
** TODO 7\46 x 2\46: Lumatone-feasible
   0  steps;  1 % 1; string 0; fret 0
   8  steps;  9 % 8; string 0; fret 4
   15 steps;  5 % 4; string 1; fret 4
   21 steps; 11 % 8; string 3; fret 0
   27 steps;  3 % 2; string 3; fret 3
   32 steps; 13 % 8; string 4; fret 2
   37 steps;  7 % 4; string 5; fret 1
   42 steps; 15 % 8; string 6; fret 0
   46 steps;  2 % 1; string 6; fret 2
** TODO 9\46 x 2\46: 31-lim in 4x7, octave (5,0.5), guitar-feas
*** the layout
    0  steps;  1 % 1;  string 0; fret 0
    46 steps;  2 % 1;  string 4; fret 5
    27 steps;  3 % 2;  string 3; fret 0
    15 steps;  5 % 4;  string 1; fret 3
    37 steps;  7 % 4;  string 3; fret 5
    8  steps;  9 % 8;  string 0; fret 4
    21 steps; 11 % 8;  string 1; fret 6
    32 steps; 13 % 8;  string 2; fret 7
    42 steps; 15 % 8;  string 4; fret 3
    4  steps; 17 % 16; string 0; fret 2
    11 steps; 19 % 16; string 1; fret 1
    18 steps; 21 % 16; string 2; fret 0
    24 steps; 23 % 16; string 2; fret 3
    30 steps; 25 % 16; string 2; fret 6
    35 steps; 27 % 16; string 3; fret 4
    39 steps; 29 % 16; string 3; fret 6
    44 steps; 31 % 16; string 4; fret 4
** TODO 8\46 x 3\46: Bosanquet, 13-lim in 6x5, 31-lim in 7x6
*** the layout
    0  steps;  1 % 1;  string 0; fret 0
    46 steps;  2 % 1;  string 5; fret 2
    27 steps;  3 % 2;  string 3; fret 1
    15 steps;  5 % 4;  string 3; fret -3
    37 steps;  7 % 4;  string 5; fret -1
    8  steps;  9 % 8;  string 1; fret 0
    21 steps; 11 % 8;  string 3; fret -1
    32 steps; 13 % 8;  string 4; fret 0
    42 steps; 15 % 8;  string 6; fret -2
    4  steps; 17 % 16; string 2; fret -4
    11 steps; 19 % 16; string 1; fret 1
    18 steps; 21 % 16; string 3; fret -2
    24 steps; 23 % 16; string 3; fret 0
    30 steps; 25 % 16; string 3; fret 2
    35 steps; 27 % 16; string 4; fret 1
    39 steps; 29 % 16; string 6; fret -3
    44 steps; 31 % 16; string 7; fret -4
*** downsides
    Minor thirds are a little harder.
    It's more confusing than 9\46 x 1\46.
** TODO 46 5 9: 31-lim in 6x7, 17-lim in 4x6, octave 4-2, frets like 9-edo
   :PROPERTIES:
   :ID:       d3e9851f-5276-4a8f-9cd8-e9c5417d5940
   :END:
  0  steps; 1  % 1 ;  string 0 ;   fret 0
  46 steps; 2  % 1 ;  string 4 ;   fret 2
  27 steps; 3  % 2 ;  string 3 ;   fret 0
  15 steps; 5  % 4 ;  string 0 ;   fret 3
  37 steps; 7  % 4 ;  string 3 ;   fret 2
  8  steps; 9  % 8 ;  string 2 ;   fret - 2
  21 steps; 11 % 8 ;  string 4 ;   fret - 3
  32 steps; 13 % 8 ;  string 3 ;   fret 1
  42 steps; 15 % 8 ;  string 3 ;   fret 3
  4  steps; 17 % 16 ; string 1 ;   fret - 1
  11 steps; 19 % 16 ; string - 1 ; fret 4
  18 steps; 21 % 16 ; string 2 ;   fret 0
  24 steps; 23 % 16 ; string 1 ;   fret 3
  30 steps; 25 % 16 ; string 5 ;   fret - 3
  35 steps; 27 % 16 ; string 5 ;   fret - 2
  39 steps; 29 % 16 ; string 6 ;   fret - 3
  44 steps; 31 % 16 ; string 6 ;   fret - 2
** 46 2 17: a stretch but guitar-feasible
   The 7%4 looks bad,
   but 10 frets in 23-edo is only just over 5 frets of 12-edo.
   [ 0  steps; 1  % 1 ; string 0 ; fret 0
   , 46 steps; 2  % 1 ; string 2 ; fret 6
   , 27 steps; 3  % 2 ; string 1 ; fret 5
   , 15 steps; 5  % 4 ; string 1 ; fret - 1
   , 37 steps; 7  % 4 ; string 1 ; fret 10
   , 8  steps; 9  % 8 ; string 0 ; fret 4
   , 21 steps; 11 % 8 ; string 1 ; fret 2
   , 32 steps; 13 % 8 ; string 2 ; fret - 1
   , 42 steps; 15 % 8 ; string 2 ; fret 4
