:PROPERTIES:
:ID:       ee622f95-a99f-4a4b-bb5d-18d48c16b15b
:END:
#+title: 58-edo scales, chords and harmonies
* see also
** [[id:bfe139e1-14a4-4538-82d4-ea11f142e0ce][just intonation]]
** [[id:97e78830-11c4-4736-afc3-4669fd94ee2e][microtonality]]
* TODO [[id:dd723b43-7f25-4071-a987-de6782fd59b0][When improvising, try pedals in the base and treble. That is, hold either hand fixed while changing the harmonies radically and the other hand]]
* nice sept min maj7 : 0 13 34 52
  maybe because 52 + 19 = 13'
* wide uniform chord : [0,26,52,20',46',14"..]
* a nice cluster: 0 8 21
  Has minor and major sept thirds.
* harmonic phrygian #7
  0 8 15 22 34 39 52
  This is what you get if you play all the harmonics
  but replace the 10:9 with 7:6,
  and start on 5:4 rather than the root.
* a sweet septimal scale near 0 2 4.3 6 7 8 11 \ 12
  0 11 21 30 34 38 52
  Origin: Think of 11 as the root, and it becomes
    0  10 19 23 27 41 47
* TODO try a neutral aug-ish scale
** idea
   repeat [0, x] every 17\58
     for some value of x
** code
:{
filter (< 58) $ -- or maybe 2*58, or even 3*58,
                -- if the repeating shape is wide
  take 12 $ -- no scale needs more than 12 notes
  concat [ fmap (+x) $
           [0,4] | x <- [0,17..] ]
:}
* maybe the ringiest dim7
  0 15 28 49
  That's 6/5 + 7/6 + 9/7
* a nicer interval from 9\12 to 13\12 -ish
  uses 933 cents for the 9\12,
  and reaches up 5:4 to 6'\58
* symmetric-ish scales
** [0,13] x [0,27,..]
*** alternates between 13\58 and 14\58
*** I'm cutting it off after 2 octaves
*** code
 :{
 L.sort $
 map (flip mod 58) $
 filter (< (floor $ 2*58)) $
   take 20 $ -- way more than enough
   concat [ fmap (+x) $
            [0,13] | x <- [0,27..] ]
 :}
** [0,29] x [0,7,14,21]
   The most evenly spaced 8-note scale.
** [0,29] x [0,8,16,24]
   Start on the last degree,
   and the result has a perfect fifth
   and both septimal thirds.
* whole-tone scales
** the most harmonious
   [0, 28] x [0, 10, 19]
   That is, two clusters of [0,10,19]\58.
   offset by 28\58.
** 7 tones, ends at 54\58
   9\58 (182 cent) intervals all the way up.
   Includes the [[id:f5663e9e-0959-42df-8ca2-6290bad6c41b][4-note aug chord that includes 54\58]]
** septimal: 6 tones, ends at 53\58
*** definition
    diffs  : - 11 - 10 - 11 - 10 - 11 - 5
    values : 0,  11,  21,  32,  42,  53
*** why it's good
    it has two 7:8:9 triads (0 11 21 \ 58)
    and a 15:8 (53)
* 9-tone dim scales
  Repeat 0 8 13 or 0 5 13.
** Starting with 8 => it includes 34\58.
** Both scales include 52\58.
** Both are uniform except where 5\58 and 6\58 meet.
* subharmonic series
** 1/[8..13,15] = 5-limit phrygian* but         16/13
   with 16/9, not 9/5
** 1/[8..14   ] = 5-limit phrygian* but 8/7 and 16/13
   with 16/9, not 9/5
* [[id:998b725f-56bd-4d64-93d6-4f9119dbcf10][58-edo chords]]
* 10-tone scale with P4 and P5
  notes             P4    P5
  pitch - 0 6 12 18 24 29 34 40 46 52
  diff  -  6 6  6  6  5  5  6  6  6
* Two-octave 11-tone whole-tone scale
  Alternate 10\58 and 11\58.
  Repeats every 2 octaves.
  11 tones total.
* 7:4 + 9:7 = 13:8 + 11:8 = 9:4
  47  + 21  = 41   + 27   = 10'
* 3 x 7:6 = 11:8 + 4:3
