:PROPERTIES:
:ID:       beabbc24-aa01-49c4-a4e2-7f610ff2e44f
:END:
#+title: 6\58 x 5\58
* on the Lumatone
** minimal harmonic rectangles
   23-lim minus 11,19 in 8x3
   23-lim minus 19    in 8x4
   29-lim minus 25    in 8x5
** It's already drawn in lumatone-isomorphic.
   It's called 58edo.6right.11downright.ltn.
   (PITFALL: 6+5 = 11 gives the downright step size.)
* smart height 4.36
* layout
  00 steps; 01 % 01; string  0;  fret  0
                     string -5;  fret -6  -- nearly vertical on Lumatone
  05 steps; 17 % 16; string  0;  fret  1
  10 steps; 09 % 08; string  0;  fret  2
  19 steps; 05 % 04; string  4;  fret -1
  23 steps; 21 % 16; string  3;  fret  1
  27 steps; 11 % 08; string  2;  fret  3
  30 steps; 23 % 16; string  5;  fret  0
  34 steps; 03 % 02; string  4;  fret  2
  41 steps; 13 % 08; string  6;  fret  1
  47 steps; 07 % 04; string  7;  fret  1
  53 steps; 15 % 08; string  8;  fret  1
  58 steps; 02 % 01; string  8;  fret  2

  14 steps; 19 % 16; string -1;  fret 4
  37 steps; 25 % 16; string  2;  fret 5
  44 steps; 27 % 16; string  4;  fret 4
  50 steps; 29 % 16; string  5;  fret 4
  55 steps; 31 % 16; string  5;  fret 5

  Since the octave is at (8,2),
  harmonics 27, 29 and 31 are easier to reach than they appear.
  (And harmonic 29 blends great with the 17-limit.)
* TODO how I would map it to the Lumatone
  Strings obviously increase going rightward horizontal-ish.
  Frets could either increase going down, or going left-up.
  If frets increase going down, octaves are nearly perfectly horizontal.
  Otherwise they are very diagonal, but maybe still playable.
* pictures
  See my Lumatone notes for how to shear these pictures.
** picture: all 31-limit harmonics

   ·· ·· ·· ·· ·· ·· ·· ·· ·· 19 ·· ·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· 15_·· ·· ·· 5· ·· ·· 25 ·· ·· ·· ·· ·· ··
  		                         !
   ·· ·· ·· ·· ·· 1· ·· ·· ·· ·· 23 ·· ·· ·· ·· ·· ·· 19'·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· 17 ·· ·· 21 ·· ·· 13 7· 15 ·· ·· ·· 5' ·· ·· 25'·· ·· 31'
  					                         !
   ·· ·· ·· ·· ·· 9· ·· ·· ·· 3· ·· ·· ·· 2· ·· ·· ·· ·· 23'·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· ·· ·· 11 ·· ·· ·· ·· ·· 17 ·· ·· 21'·· ·· 13'7' 15'·· ··

   ·· ·· ·· ·· 19 ·· ·· ·· ·· 27 29 ·· ·· 9' ·· ·· ·· 3' ·· ·· ·· 4· ·· ··

   15_·· ·· ·· 5· ·· ·· 25 ·· ·· 31 ·· ·· ·· ·· 11'·· ·· ·· ·· ·· ·· ·· ··
			!
   1· ·· ·· ·· ·· 23 ·· ·· ·· ·· ·· ·· 19'·· ·· ·· ·· 27'29' ·· ·· ·· ·· ··

   17 ·· ·· 21 ·· ·· 13 7· 15 ·· ·· ·· 5' ·· ·· 25'·· ·· 31'
						!
   9· ·· ·· ·· 3· ·· ·· ·· 2· ·· ·· ·· ·· 23'·· ·· ·· ·· ··

   ·· ·· 11 ·· ·· ·· ·· ·· 17'·· ·· 21'·· ·· 13'7' 15'·· ··

   ·· ·· ·· ·· 27 29 ·· ·· 9' ·· ·· ·· 3' ·· ·· ·· 4· ·· ··

   ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 11'·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 27'29' ·· ·· ·· ·· ··

** picture: the most useful harmonics

   ·· ·· ·· ·· ·· 15_·· ·· ·· 5· ·· ·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· 1· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· 17 ·· ·· 21 ·· ·· 13 7· 15 ·· ·· ·· 5' ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· 9· ·· ·· ·· 3· ·· ·· ·· 2· ·· ·· ·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· ·· ·· 11 ·· ·· ·· ·· ·· 17 ·· ·· 21'·· ·· 13'7' 15'·· ··

   ·· ·· ·· ·· ·· ·· ·· ·· ·· 27 29 ·· ·· 9' ·· ·· ·· 3' ·· ·· ·· 4· ·· ··

   15_·· ·· ·· 5· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 11'·· ·· ·· ·· ·· ·· ·· ··

   1· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 27'29' ·· ·· ·· ·· ··

   17 ·· ·· 21 ·· ·· 13 7· 15 ·· ·· ·· 5' ·· ·· ·· ·· ·· ··

   9· ·· ·· ·· 3· ·· ·· ·· 2· ·· ·· ·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· 11 ·· ·· ·· ·· ·· 17'·· ·· 21'·· ·· 13'7' 15'·· ··

   ·· ·· ·· ·· 27 29 ·· ·· 9' ·· ·· ·· 3' ·· ·· ·· 4· ·· ··

   ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 11'·· ·· ·· ·· ·· ·· ·· ··

   ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· ·· 27'29' ·· ·· ·· ·· ··

* dumb link
   :PROPERTIES:
   :ID:       a291f843-ee45-40e9-923e-badfe65654a7
   :END:
