:PROPERTIES:
:ID:       210f2535-4468-45ad-9f0b-0ac22d8a9f56
:END:
#+title: 94-edo
* [[id:da3996ba-9f17-4eff-b53d-7096a491aacb][94-edo is surprisingly similar to 135-edo]]
* tuning coverings
** (16\94 x 7\94 = Bosanquet) and (19\94 x 9\94) complement each other well
   (This analysis only goes up to the 23rd harmonic.)
   19\94 x 9\94 => easy harmonics 17, 23, unlike Bosanquet
   19\94 x 9\94 => hard harmonics 11, 19, unlike Bosanquet
* TODO 16\94 x 7\94 = Bosanquet
  [ 0 steps; 1 % 1 ; string 0 ; fret 0
  , 94 steps; 2 % 1 ; string 5 ; fret 2
  , 55 steps; 3 % 2 ; string 3 ; fret 1
  , 30 steps; 5 % 4 ; string 1 ; fret 2
  , 76 steps; 7 % 4 ; string 3 ; fret 4
  , 16 steps; 9 % 8 ; string 1 ; fret 0
  , 43 steps; 11 % 8 ; string 4 ; fret - 3
  , 66 steps; 13 % 8 ; string 5 ; fret - 2
  , 85 steps; 15 % 8 ; string 4 ; fret 3
  , 8 steps; 17 % 16 ; string 4 ; fret - 8
  , 23 steps; 19 % 16 ; string 1 ; fret 1
  , 37 steps; 21 % 16 ; string 1 ; fret 3
  , 49 steps; 23 % 16 ; string 0 ; fret 7
  , 61 steps; 25 % 16 ; string 6 ; fret - 5
  , 71 steps; 27 % 16 ; string 4 ; fret 1
  , 81 steps; 29 % 16 ; string 2 ; fret 7
  , 90 steps; 31 % 16 ; string 3 ; fret 6
* TODO 19\94 x 9\94
** the layout
   [ 0 steps; 1 % 1 ; string 0 ; fret 0
   , 94 steps; 2 % 1 ; string 4 ; fret 2
   , 55 steps; 3 % 2 ; string 1 ; fret 4
   , 30 steps; 5 % 4 ; string 3 ; fret - 3
   , 76 steps; 7 % 4 ; string 4 ; fret 0
   , 16 steps; 9 % 8 ; string - 2 ; fret 6
   # , 43 steps; 11 % 8 ; string - 2 ; fret 9
   , 66 steps; 13 % 8 ; string 3 ; fret 1
   , 85 steps; 15 % 8 ; string 4 ; fret 1
   , 8 steps; 17 % 16 ; string - 1 ; fret 3
   # , 23 steps; 19 % 16 ; string - 4 ; fret 11
   , 37 steps; 21 % 16 ; string 1 ; fret 2
   , 49 steps; 23 % 16 ; string 4 ; fret - 3
   # , 61 steps; 25 % 16 ; string - 2 ; fret 11
   # , 71 steps; 27 % 16 ; string - 1 ; fret 10
   # , 81 steps; 29 % 16 ; string 0 ; fret 9
   # , 90 steps; 31 % 16 ; string 0 ; fret 10
** Pr.pPrint $ bestLayout' 94 19 9
* TODO 94 7 16: 15-lim +19.21.27 0-area 5x7, 8ve (5,2), no near unisons.
  :PROPERTIES:
  :ID:       3583c5e5-48b3-4b38-8999-c8693d8bbb59
  :END:
  Bosanquet
** few unisons, octaves
   You'd have to go 7 strings up and 16 frets down to get to the same note.
   That's only feasible for the higher notes of the lowest string of a 7-string guitar.
   You can go 5 strings and 2 frets up to get to the octave,
   so unless there are at least 11 strings,
   some middle strings contain entirely unique notes.
** layout
  94 steps; 2  % 1 ;  string 5 ; fret 2
  55 steps; 3  % 2 ;  string 3 ; fret 1
  30 steps; 5  % 4 ;  string 1 ; fret 2
  76 steps; 7  % 4 ;  string 3 ; fret 4
  16 steps; 9  % 8 ;  string 1 ; fret 0
  43 steps; 11 % 8 ;  string 4 ; fret - 3
  66 steps; 13 % 8 ;  string 5 ; fret - 2
  85 steps; 15 % 8 ;  string 4 ; fret 3
  8  steps; 17 % 16 ; string 4 ; fret - 8
  23 steps; 19 % 16 ; string 1 ; fret 1
  37 steps; 21 % 16 ; string 1 ; fret 3
  49 steps; 23 % 16 ; string 0 ; fret 7
  61 steps; 25 % 16 ; string 6 ; fret - 5
  71 steps; 27 % 16 ; string 4 ; fret 1
  81 steps; 29 % 16 ; string 2 ; fret 7
  90 steps; 31 % 16 ; string 3 ; fret 6
** same layout as [[id:f5f00095-e006-45c5-9b0a-c6a9507a9dd5][135 10 23]]
    but the layout for 94 is strictly easier,
    and [[id:ea979f88-41a4-42a5-88e2-d21b207dbc84][For SSE, 94 dominates 135 in the 13-limit.]]
* TODO 13\94 x 1\94: max span 9 frets, octave at (7,3), nice 4:5:6:8
 8 steps = 17 % 16: string 1 fret -5 | string 0 fret 8
23 steps = 19 % 16: string 2 fret -3
30 steps = 5 % 4:   string 2 fret 4
43 steps = 11 % 8:  string 3 fret 4
49 steps = 23 % 16: string 4 fret -3
55 steps = 3 % 2:   string 4 fret 3
66 steps = 13 % 8:  string 5 fret 1
76 steps = 7 % 4:   string 6 fret -2
81 steps = 29 % 16: string 6 fret 3
90 steps = 31 % 16: string 7 fret -1
94 steps = 2 % 1:   string 7 fret 3
* 12\94 x 1\94: max span 9 frets, octave at (8,-2)
8 steps = 17 % 16:  string 1 fret -4 | string 0 fret 8
23 steps = 19 % 16: string 2 fret -1
30 steps = 5 % 4:   string 3 fret -6
43 steps = 11 % 8:  string 4 fret -5
49 steps = 23 % 16: string 4 fret  1
55 steps = 3 % 2:   string 5 fret -5
66 steps = 13 % 8:  string 6 fret -6
76 steps = 7 % 4:   string 7 fret -8
81 steps = 29 % 16: string 7 fret -3 | string 6 fret  9
90 steps = 31 % 16: string 8 fret -6 | string 7 fret 6
94 steps = 2 % 1:   string 8 fret -2
* TODO 94 3 13
       [ 94 steps = 2 % 1 : string 7 fret 1
       , 55 steps = 3 % 2 : string 4 fret 1
       , 30 steps = 5 % 4 : string 3 fret - 3
       , 76 steps = 7 % 4 : string 7 fret - 5
       , 43 steps = 11 % 8 : string 4 fret - 3
       , 66 steps = 13 % 8 : string 6 fret - 4
       , 8 steps = 17 % 16 : string - 1 fret 7
       , 23 steps = 19 % 16 : string 2 fret - 1
       , 49 steps = 23 % 16 : string 4 fret - 1
       , 81 steps = 29 % 16 : string 6 fret 1
       , 90 steps = 31 % 16 : string 6 fret 4
* TODO 94 2 17: fret span of 8 in the 29-limit, octave (6,-4)
       [ 94 steps = 2 % 1 : string 6 fret - 4
       , 55 steps = 3 % 2 : string 3 fret 2
       , 30 steps = 5 % 4 : string 2 fret - 2
       , 76 steps = 7 % 4 : string 4 fret 4
       , 43 steps = 11 % 8 : string 3 fret - 4
       , 66 steps = 13 % 8 : string 4 fret - 1
       , 8 steps = 17 % 16 : string 0 fret 4
       , 23 steps = 19 % 16 : string 1 fret 3
       , 49 steps = 23 % 16 : string 3 fret - 1
       , 81 steps = 29 % 16 : string 5 fret - 2
       , 90 steps = 31 % 16 : string 4 fret 11
* TODO 94 4 17
  octave at (2,15)
       [ 94 steps = 2 % 1 : string 6 fret - 2
       , 55 steps = 3 % 2 : string 3 fret 1
       , 30 steps = 5 % 4 : string 2 fret - 1
       , 76 steps = 7 % 4 : string 4 fret 2
       , 43 steps = 11 % 8 : string 3 fret - 2
       , 66 steps = 13 % 8 : string 2 fret 8
       , 8 steps = 17 % 16 : string 0 fret 2
       , 23 steps = 19 % 16 : string - 1 fret 10
       , 49 steps = 23 % 16 : string 1 fret 8
       , 81 steps = 29 % 16 : string 5 fret - 1
       , 90 steps = 31 % 16 : string 6 fret - 3
* TODO 94 9 16
       [ 94 steps = 2 % 1 : string 7 fret - 2
       , 55 steps = 3 % 2 : string 4 fret - 1
       , 30 steps = 5 % 4 : string 3 fret - 2
       , 76 steps = 7 % 4 : string 7 fret - 4
       , 43 steps = 11 % 8 : string 1 fret 3
       , 66 steps = 13 % 8 : string 3 fret 2
       , 8 steps = 17 % 16 : string - 13 fret 24
       , 23 steps = 19 % 16 : string 2 fret - 1
       , 49 steps = 23 % 16 : string - 2 fret 9
       , 81 steps = 29 % 16 : string 0 fret 9
       , 90 steps = 31 % 16 : string 0 fret 10
* 94 7 23: 15-lim 5x8, octave (5,-3), seems < 94 7 16
  :PROPERTIES:
  :ID:       45cf6fd8-8ceb-4f6e-8184-09249a556063
  :END:
      , etrTuning = Edo 94 ; StringGap 23 ; FretGap 7
      , etrArea = 56
      , etrLayout =
          [ 0 steps; 1 % 1 ; string 0 ; fret 0
          , 94 steps; 2 % 1 ; string 5 ; fret - 3
          , 55 steps; 3 % 2 ; string 3 ; fret - 2
          , 30 steps; 5 % 4 ; string 1 ; fret 1
          , 76 steps; 7 % 4 ; string 3 ; fret 1
          , 16 steps; 9 % 8 ; string 1 ; fret - 1
          , 43 steps; 11 % 8 ; string 4 ; fret - 7
          , 66 steps; 13 % 8 ; string 5 ; fret - 7
          , 85 steps; 15 % 8 ; string 4 ; fret - 1
