:PROPERTIES:
:ID:       4a68de20-5a78-4360-94a1-ba01e090df19
:END:
#+title: a few causes important to me
Que tratemos mejor a los animales. Que paramos de convertir tierra con mucha biodiversidad en campo. (Yo soy carnívoro pero intento coomer vegetariano cada vez que puedo. Acabo la semana pasada de donar a Legal Impact for Chickens.)

Que aprendamos como sociedad ser escépiticos de la provenencia de audio, video y fotos, ya que la IA puede inventarlas. (Dile a tus padres que si reciben un mensaje de ti pidiendo dinero, aunque sea un mensaje de voz, que te llamen y te hablen para verificar que fuiste tu!)

Que como consumidores de noticias aprendamos que si no pagamos a los medios, los medios van a ser malos. O que tratemos al periodismo como un bien público y lo subsidemos de los ingresos tributarios. (Pero ese segundo me da miedo del control político.)

Tal vez la causa más divertida que me gusta es un ONG llamado ALFED (Alliance to Feed the Earth in Disasters) que está creando champiñones (qque  no necesitan luz para crecer) de alta proteina, y bacteria que convierte papel o madera en azúcar, para que tengamos algo que comer en el caso de un invierno nuclear.

No es una lista completa pero son las cosas en que más estoy pensando estos días.
