:PROPERTIES:
:ID:       f9ee18e9-68f2-4f10-b10d-c91186b797e3
:ROAM_ALIASES: Agora
:END:
#+title: Agora (shared knowledge base (protocol))
* org-roam user @doubleloop (Neil) cross-publishes to Agora
  :PROPERTIES:
  :ID:       4822cf1d-6e75-422e-81b2-c0a38f5aaa83
  :END:
  He said so here:
  https://org-roam.discourse.group/t/rg-roam-minimal-org-roam-with-zero-config-no-sql-depends-only-on-ripgrep/3803/16
* <2024-10-06 Sun> trying with Flancian's Dockerfile
  This seems to show how to launch:
  https://github.com/flancian/agora/blob/master/Agora%20architecture.md
* <2022-03-28 Mon> my latest problem
** refs
*** my NixOS experiments on github
    https://github.com/JeffreyBenjaminBrown/nixos-experiments/tree/agora-problems/agora-problems
*** asking on the NixOS Discourse
    https://discourse.nixos.org/t/errors-maybe-uwsgi-related-while-pip-installing-in-virtualenv/18347
*** asking Flancian on Twitter
    https://twitter.com/carelogic/status/1507186676078153729
* refs
** [[id:4d3b3efd-41a9-49a9-be5a-740d83b15ac9][Flancian, the guy who made Agora]]
** the Git issue I filed
   :PROPERTIES:
   :ID:       304e3d3e-f05f-424d-8eab-34fcfda408c9
   :END:
   https://github.com/flancian/agora/issues/5
** Github: https://github.com/flancian/agora
** The introductory node: https://anagora.org/node/agora
** YC: https://news.ycombinator.com/item?id=25573523
** [[id:22b7c16d-b4c1-4524-81c7-e42c9266880e][Asking NixOS Discourse about libmemcached]]
* PITFALLs
** [[id:ba84b51c-77a1-4c7b-a958-22e9183c3522][Prevent git credential validators from popping up whenever I deal with a remote on GitHub over HTTP.]]
* TODO try it in Docker
** [[id:304e3d3e-f05f-424d-8eab-34fcfda408c9][the Git issue I filed]]
** things that didn't work
*** connect 8888:8888 rather than 5000:5000
    8888:8888 is what tax.co.web does, and that works when I connect to port 8000.
    Doing this in Agora still led `pip3 install requirements.txt` in `agora-server` to report `invalid command 'bidist_wheel'`.
    And still I can't connect.
*** trying :: pip3 install --upgrade "--all"
    `--all` is not actually an option.
    Instead there's this:
      pip3 freeze --local |sed -rn 's/^([^=# \t\\][^ \t=]*)=.*/echo; echo Processing \1 ...; pip3 install -U \1/p' |sh
    from here:
      https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip
    (I tried some earlier things on that page, which didn't seem to work.)
*** pip3 install --upgrade wheel
    It did upgrade that,
    but had no effect when installing requirements.txt
*** `pip3 install wheel`
    I don't see `wheel` in agora-server's `requirements.txt`.
    But when I try this nothing changes; I see "requirement already satisfied."
*** Installing wheel via the older pip.
    Ran these commands:
      apt install -y python-pip # not python3-pip, which is already installed
      pip install wheel
    It reports after the second that the wheel req is already satisfied.
*** adding appuser to sudo and wheel didn't work
**** I can run these as root, but they make no difference.
     addgroup wheel
     usermod -a -G wheel appuser
     usermod -a -G sudo appuser
**** If I run them in the Dockerfile it doesn't build.
     I get this error:
       groupadd: Permission denied.
       groupadd: cannot lock /etc/group; try again later.
** things I never tried, because they seem unlikely to work
*** pip3 install each of the packages that fails
    when installing requirements.txt into the venv
** TODO ? add user to wheel and sudo before apt-installing python-wheel
* Don't run from root; run from home
  Otherwise it tries to create stuff in root.
* TODO report
** had to create an empty config.json file
* BLOCKED libmemcached error when building natively
  :PROPERTIES:
  :ID:       22b7c16d-b4c1-4524-81c7-e42c9266880e
  :END:
  Asking on Discourse:
  https://discourse.nixos.org/t/gcc-not-finding-libmemcached-after-installing-both-via-nixos-rebuild/13681
