:PROPERTIES:
:ID:       f927cc31-1266-4352-978a-b0e00fb806a8
:END:
#+title: amazing music
* Maria Schneider
  epic classical/jazz
* later Tool
  Lateralus
* Jamael Dean
* [[id:7bde5646-14eb-4dce-a2d1-0d44804b737a][OpenAI Jukebox]]
* John Beasley (jazz)
* a mix of (un-12) Palestinian music with a techno beat
  Who are the artists?
** https://m.youtube.com/watch?t=319&v=bP5Zj4V7gi4&feature=youtu.be
* Hans-André Stamm
  microtonal
* Norokusi
  microtonal
* [[id:339f3f3a-49c2-4dfd-a66c-de482ccec92a][my introductory microtonal music recommendations]]
* Tarek Yamani: Maqam piano jazz
* Amir ElSaffar: Maqam trumpet jazz
* Fabio Costa: 19- and 31-edo orchestral
* Deerhoof: Soul Coughing + Devo + female Japanese vocalist
* Andy Akiho, classical percussion
  https://www.youtube.com/watch?v=02MmzWHfZgs
  https://www.youtube.com/watch?v=02MmzWHfZgs
* Ghost Shark!
  https://twitter.com/mannfishh
* Seeking Clarity in the Moment
  Chris Vaisvil, 17-edo guitar + effects
  https://alonetone.com/vaisvil/tracks/seeking-clarity-in-the-moment?fbclid=IwAR1vQ-aLB8miLlZCneg2bl5aSq7DIBkyOlQ518rarleX_HDgNw-0Fc8Rm1o
* tennisers
  https://soundcloud.com/ihave5arms/immolation-celebration?ref=clipboard&p=a&c=0&utm_campaign=social_sharing&utm_medium=text&utm_source=clipboard
* Jim Sansing
  https://www.youtube.com/watch?v=gEbGEVWGnX4
* Nick The NRG (microtonal, beats)
  https://nick-the-nrg.bandcamp.com/
* gexahedrop
  at least their album "micros"
  https://gexahedrop.bandcamp.com/album/micros
* *STAFFcirc*: a collaborative album group, some of whom I found
  Stands for "sexy toads and frogs friends circle".
** awesome artists not on Spotify
   Jaq (on Spotify)
   Petet (on Spotify)
     also on Soundcloud: https://soundcloud.com/symphonynth
   Emelia K (on Spotify)
   0x70457465 (nowhere)
   STC_100n (nowhere)
     for n in [1..4]
   Abd al-Mahdi (nowhere)
** awesome on the record but mostly not awesome on spotify
   vince kaichan
   hunter van brocklin
   tancla
   themnotyou
* Ordinate
* Gaia Complex (Aidan Lochran)
Xen, electronic, beats.
https://gaiacomplex.bandcamp.com/album/how-to-spread-fractals-on-toast/
* Methods Body
https://methodsbody.bandcamp.com/album/methods-body
* Claudi Meneghin
https://www.youtube.com/watch?v=3bvlz6RgKng&feature=youtu.be
* Makeunder
The Great Headless Blank
* Alois Hába: famous classical micorotnal
* Wyschnegradsky: "melodic" microtonal classical
a neighbor of Ives
* Easley Blackwood's microtonal album
https://www.youtube.com/watch?v=HbuFPpiJL1o
* Taylor Brook
https://www.youtube.com/watch?v=kpHSC8eWWL8
* John Starrett
https://soundcloud.com/user-963307730/my-newt-waltz-slow
* Yet to fully explore: microtonalists like Prokofiev, Debussy
https://www.facebook.com/groups/xenharmonic2/permalink/3310548138965465/
* Tom Price
https://soundcloud.com/tomprice719
* Piers Hudson
https://soundcloud.com/piershudsoncomposer
* Antoine Beaudet
https://soundcloud.com/jollybard
* Stephen Weigel's emoji-titled album
"Postmodern EDM". Unbelievably awesome.
https://xenharmonicgod.bandcamp.com/album/
* H.Wakabayashi Microtonal
is a youtube channel, maybe more
* Rami Olsen
* syzygwa (Jon Lervold)
https://syzygywa.bandcamp.com
jonlervold.com
* Chico Buarque (artist), Construção (song)
funky Brazillian film music
* Cryptic Ruse - Chains of Smoke
  microtonal metal album
* Jute Gyte - Ovini
microtonal metal album
* Zach Curley 333, on bandcamp
just-intoed and odd-edo guitar music
https://zachcurley333.bandcamp.com/
* Microwave 64, on bandcamp
https://microwave64.bandcamp.com/album/microwave?fbclid=IwAR2QZwmXgX0TTDTlIvLiSGlD-CIF412jDsxeAN8-kOZC_Vq6y4CoFcDs4oM
* Elaine Walker / ZIA
https://ziaspace.bandcamp.com/
* Zhea Erose
https://zheaerosemusic.bandcamp.com/track/sola
* Adam Hochstatter, film music
* Aaron Krister Johnson
** Setiesque (46 edo)
   https://aaronkristerjohnson.bandcamp.com/track/satiesque
* Big Brazillian Disaster
https://selonetlabel.bandcamp.com/album/the-big-brazilian-disaster?fbclid=IwAR0OtfmJ4yEn1lDoFcXYVPYxSGNLz6OBQ8U70idLmLo4b3pqSC657UdqJnM
