:PROPERTIES:
:ID:       61e0e604-502b-4177-912b-eee9ab2543d8
:ROAM_ALIASES: AWS
:END:
#+title: Amazon Web Services
* TODO refs | URLs
** related docs
*** [[id:6d02b17d-a43e-43e2-9e75-91622bd08c38][AWS vocabulary]]
*** [[id:390298ec-b752-4e01-8962-1da401c2d3b7][AWS IAM (Identity Access Management)]]
*** [[id:7a0f92a2-486b-40d5-97c6-9e4908b14138][AWS S3]]
*** [[id:c5d25204-1e5e-41bc-974d-80aa2d67c870][AWS S3 CLI]]
*** [[id:4aecfac3-98c5-40b7-8a3c-ae44a8d85c8a][AfWS Git]]
*** [[id:275e4978-231c-474b-8bdf-9cd80104ff50][Django in AWS (esp. AWS EB)]]
*** [[id:19029d09-5a57-4d81-99f2-56465c8e2586][the internet]]
*** [[id:da25bd69-a967-4393-bfa7-817f4c7eaa47][EC2]], esp. how to launch a virtual machine
    EC2 is the raw virtual machine system. One can use it alone, or via one of the higher-level systems it underpins, like Lightsail.
*** [[id:47c8e8e5-7dca-4869-9597-cfb95f003ff3][AWS static website hosting]]
*** [[id:44da28be-3419-46e8-a07b-e46111a183f2][AWS Lightsail]]
** all lessons
   https://aws.amazon.com/getting-started/use-cases
** PITFALL: don't visit
*** AWS services overview
    https://www.aws.training/Details/Video?id=16206&trk=gs_card
    It's a slow video lecture series.
** TODO ? next
*** RESUME AT (?)
    Deploy Your Site with the EB CLI
*** messaging
    There are even more tutorials on the same theme.
**** Send messages between distributed apps
     https://aws.amazon.com/getting-started/tutorials/send-messages-distributed-applications/?trk=gs_card
**** Fanout event notifications
     https://aws.amazon.com/getting-started/tutorials/send-fanout-event-notifications/?trk=gs_card
*** Build a LAMP (linux, apache http, mysql, and a language) web app
    https://aws.amazon.com/getting-started/projects/launch-lamp-web-app/
    https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-tutorial-launching-and-configuring-lamp
*** Build a serverless app
    https://aws.amazon.com/getting-started/projects/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/?trk=gs_card
* for saving money
** "requester pays" is an S3 option
* TODO AWS services I might want to learn
** AWS storage gateway
   Someone describes it as a dropbox client but for S3.
   AWS seems to suggest it does lots of other stuff.
* PITFALL web endpoint formatting depends on region
  A website's endpoint takes one of two almost identical forms,
  depending on the region:
    bucket-name.s3-website-region.amazonaws.com
    bucket-name.s3-website.region.amazonaws.com
                          ^
                    the difference
  In my case it's these:
        jefbrown.net.s3-website-us-east-1.amazonaws.com
  under.jefbrown.net.s3-website-us-east-1.amazonaws.com
