:PROPERTIES:
:ID:       7b1955b6-78d0-4912-8347-3eb653b7a1de
:ROAM_ALIASES: "shell programming" "Bash"
:END:
#+title: bash (shell)
* [[id:41078ddd-4ec0-45fe-a799-3f8d00aa81d8][NuShell]]
* Shell script best practices
** https://sharats.me/posts/shell-script-best-practices/
* [[id:e6dc1949-5024-4fee-b031-7af412353a5e][diff (shell programming concept)]]
* [[id:65fa661f-8304-4a1b-b11c-0b927fca356f][how to change the Bash prompt]]
* pipe stdout and stderr to the same file
  command >out 2>&1
* `cd`, change default target directory
  I don't know,
  but the first line below comes extremely close,
  and without clobbering the real `cd` command:

  jeff@jbb-dell:mtv$ cd="cd $(pwd)"
  jeff@jbb-dell:mtv$ echo $cd
  cd /home/jeff/mtv
  jeff@jbb-dell:mtv$ cd
  jeff@jbb-dell:~$ $cd
  jeff@jbb-dell:mtv$
* [[id:784c0660-a998-4bbf-bc80-c0b46a89a632][make (build utility)]]
* to set an environment variable from a script
** Call the script using "." (rather than, say, "bash").
   This runs the script "in the current environment".
** demo
   jeff@jbb-dell:quant$ echo $NONSENSE_WORD # It's not defined.

   jeff@jbb-dell:quant$ cat test-export.sh
   export NONSENSE_WORD="HTUIOGSHLSDGA:"
   jeff@jbb-dell:quant$ . test-export.sh
   jeff@jbb-dell:quant$ echo $NONSENSE_WORD # Now it is.
   HTUIOGSHLSDGA:
   jeff@jbb-dell:quant$
* view a readable diff of two csv files
  csv-diff file file2 --key="field-name"
  (This is installed in the Docker image.)
** or, within python
   This is buggy, because it uses multiple keys.
   Instead must create a single composite key.
     in tax.co, see python/hand_test/composite_index.py

   from csv_diff import load_csv, compare
   diff = compare(
     load_csv("data/recip-10/people_3_income_taxish.detail.2018.csv",
              key=["household","household-member"] ),
     load_csv("no-dep-exempt/people_3_income_taxish.detail.2018.csv",
              key=["household","household-member"] ) )
* create tar.gz archive
  tar -czvf tarball-of-zipfiles.tar.gz individual-zipfiles/
* create pdf from markdown
  pandoc -o bugs.pdf bugs.md
  To render beamer-style, add the option `-t beamer`.
  PITFALL: New sections must be preceded by a blank line.
* search
** [[id:ee83ddd1-aeaa-46e9-a6a7-d180ac16471f][grep (command line search utility)]]
** find, show all file extensions in filetree
   find . -type f | sed 's/.*\.//' | grep -v "/" | sort | uniq -c
** find: exclude a type of file
   use the ! symbol to negate the next option
   for example, this:
     find . -type d ! -name "__pycache__"
   excludes anything called __pycache__
** `find -exec`: do something to every found result
*** example: copy a file into every folder found
    find . -type d -exec cp __init__.py {} \;
** to find all numbers in code
   In tmux, run
     egrep "[0-9]+" -r build -r common -r draw -r regime *.py -C 5 --exclude="*test*"
   and then read that screen. (Dumping it to a file would mean losing the colors,
   which makes the reading process much slower.)
* [[id:743baaa9-2e98-4bd8-8b7e-ae27c4b0f241][moving and copying files]]
* [[id:5fabbe1c-91a2-4bca-95e4-6a38a2037e1f][mount or unmount a drive from the command line]]
* [[id:09d7af48-b851-4f73-b29c-82cd08449437][kill (bash command)]]
* get the absolute path to a file
  realpath <file>
* change a user's password
  sudo passwd <user name>
* user and group IDs in Linux
  :PROPERTIES:
  :ID:       00691b2a-7ecd-4675-aab5-2462243a54f8
  :END:
** get a group's id
   cut -d: -f3 < <(getent group groupname)
** get a user's id
   id -u username
* [[id:4f619fa5-d89d-45ea-b742-1834a120c635][shred (Bash command) : delete data for real]]
* [[id:f202975d-f1f0-4aa7-bcca-f9e6dd26230c][PITFALL: sudo can cause cp (copying) to fail.]]
