:PROPERTIES:
:ID:       8c5c4e64-a684-4f32-bf1f-cdf974d51666
:END:
#+title: Bhutan is weird!
It has been a hereditary monarchy since 1907. The king *imposed* democracy on the country, in 2008. It's the only country that became democratic in peacetime.

People there speak English well. Recently -- triggered by the pandemic, says the article, but I don't remember why -- 9% of the *entire population*, most of them young people, have left the country.

The main industries are tourism and hydropower export. Constitutionally 60% of the country must be preserved in its natural state. It is investing now in a new city with a different economic model, but no skyscrapers allowed, which seems spectacularly dumb to me. If you want to preserve most of the country as nature, skyscrapers are the way to do it -- and density is a surefire way to increase productivity.

Its prime minister is called Tobgay (which is funny because it sounds like "top guy").

https://www.cbsnews.com/news/bhutan-emigration-crisis-60-minutes/
