:PROPERTIES:
:ID:       67465b81-c736-4430-bdbd-822106520f1b
:END:
#+title: Bosanquet layout for 41-edo
* an [[id:dc6e53e5-a82f-4b7c-a8cc-7ff8ede7cc6f][online Bosanquet 41-edo keyboard]]
* just 1 row more compact than my usual 8\41 x 1\41 layout
* layout
  0  steps;  1 % 1  ; string 0 ; fret 0
  7  steps;  9 % 8  ; string 1 ; fret 0
  13 steps;  5 % 4  ; string 1 ; fret 2
  19 steps; 11 % 8  ; string 1 ; fret 4
                      string 4 ; fret -3
  29 steps; 13 % 8  ; string 2 ; fret 5
                      string 5 ; fret -2
		      string 0 ; fret -4 + octave
  24 steps;  3 % 2  ; string 3 ; fret 1
  33 steps;  7 % 4  ; string 3 ; fret 4
                      string 1 ; fret -5 + octave
  37 steps; 15 % 8  ; string 4 ; fret 3
  41 steps;  2 % 1  ; string 5 ; fret 2
* How to map it to the Lumatone
** for full 15-limit
   Map horizontal ("string" selector) to horizontal-ish.
   Map vertical ("fret" selector) to the 45-degree axis.
   To instead map vertical to vertical would make it too tall.
** for 2.3.5.15
   Map horizontal ("string" selector) to horizontal-ish.
   Map vertical ("fret" selector) to the vertical-ish.
   This puts the other harmonics far away,
   but shortens the octave,
   and makes feasible in one hand
   chords like a root position maj7.
