:PROPERTIES:
:ID:       d424dc9d-aaa6-4d26-accb-4ac85e160c21
:END:
#+title: cognitive dissonance and commitment (romantic)
* seems fine, to an extent
  I can see a certain amount of willful cognitive dissonance being healthy. In the time between leaving one's family and getting married -- the most formative years of a person's personality -- one becomes accustomed to making all of one's decisions without any need for compromise. Then it stops being that way. We get married because we think we're better off married, and we're usually right, but it doesn't mean we're better off in every way.

  And having kids raises the bar for divorce pretty high. I imagine the cognitive dissonance that parents are willing to put up with crushes anything I've experienced.
* things like Tinder make it less necessary
  Thanks to new mass-reconnoisance technologies like Tinder, I think the aptness of romantic pairings is rising. There's clearly something much more romantic about finding your partner in church or through mutual friends or whatever, but the fact is the tech works, and I'm glad.
* [[id:d279d0ba-51f5-4877-adc4-bf41b1c0bd54][Jamie, Cliff, myself and cognitive dissonance in romantic commitment]]
