:PROPERTIES:
:ID:       4de638f4-5126-4b4d-9754-25a3f76cf24d
:END:
#+title: personalized, emergently crowd-sourced curricula
* The internet is full of disconnected islands of teaching.
  Some of these might be as simple as a single
  "_ because _" statement.
* If that data were represented in a sufficiently structured way, curricula would almost fall out of it.
** the emergent crowd-sourcing
   For instance, statements regarding physics could be ordered by the amount of prior knowledge one needs in order to understand it. The least of these are where to start.
   The query or queries that build a curriculum like this do not require the people who contributed the content to have intended to put together a curriculum. It is in that sense "emergently" crowd-sourced -- it comes from a crowd, but without requiring them to try to much coordinate (beyond allowing their data to be represented in a hypergraph structure).
** the personalization
   The sequence through the material need not be fixed,
   but should instead depend on what a reader has already read
   (and, optionally, marked "understood").
* No one source contains all the evidence for most true claims.
  Sometimes a reader wants more. In a book, this is a problem. But if the study material is generated by a query, then getting more evidence for a claim could be as easy as reading further results in the query that generated the first evidence.
