:PROPERTIES:
:ID:       27ec44e3-e227-489e-8437-36c9f3807fda
:END:
#+title: Error: "Unit window-manager not found"
* ref (my question on the NixOS Discourse)
  https://discourse.nixos.org/t/fresh-minimal-kde-install-gives-error-unit-window-manager-service-not-found/23093
* the solution
** quoting my comment on that thread:
   Solved. It’s not a NixOS-specific issue. The problem was that my graphics card on this system is integrated, and the solution is to use the latest kernel rather than the default LTS. It’s as simple as adding this line to configuration.nix:

boot.kernelPackages = pkgs.linuxPackages_latest
Thanks to user K900 (bcachefs when) on the #nix channel at Matrix.org 1.
* my OP
  I installed NixOS 22.05 on a new machine using the latest (as of Friday, 2022-11-04) Plasma .iso. Plasma didn’t load in the installer, so I installed from the command line. When I boot, Plasma still doesn’t load.

  Apeing some instructions in the NixOS manual, I log into this bare-shell system and attempt to start KDE manually. I have the following interaction:

  [jeff@gobbledygook]$ systemctl start display-manager
  ==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
  Authenticating as: jeff # I typed this in
  Password:               # I typed this in, too, though you can't see it
  ==== AUTHENTICATION COMPLETE ====

  [jeff@gobbledygook]$ systemctl start window-manager
  ==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
  Authenticating as: jeff # I typed this in
  Password:               # I typed this in, too, though you can't see it
  ==== AUTHENTICATION COMPLETE ====
  Failed to start window-manager.service: Unit window-manager.service not found.
  The last line of that is the error in the title of this post.

  My configuration on this system is extremely basic. (I always start new systems that way.) I haven’t run any channel-related commands except sudo nix-channel --list, which reports that I’m on nixos-22.05.
