#+TITLE: 31 tone equal temperament
* TODO misfiled: this is about EDOs more generally
* what's great about 37-edo
** Composing without perfect fifths seems like a useful exercise
It's never occurred to me before but I wonder whether I use that interval as a kind of crutch. It's almost always present in my music, and my deviations from it are very 12-et: basically aug, dim and dom7 b5.
** Leaving out factors of 3, 37-edo will give me all the intervals I want, in exactly one form
wide min 2nd (14:13)
neutral 2nd (11:10)
wide maj 2nd (8:7)
min 3rd (13:11)
neutral 3rd (16:13)
the familiar major third (5:4)
wide major third (14:11)
super-narrow fourth (13:10, 454 cents)
super-wide fourth (11:8)
the familiar septimal tritone (7:5)
* scale concepts
** two stacks of fifths
* nice chords
** dim 7 using 7/6 and 11/8 at 1/1, then just dom 7 at 4/3
*** In 46-edo
0: 0 10 21 37
19: 0 15 27 37
** (1/1: 1, 3/2) + (2*9/7: 1, 3/2, 16/9)
That is, concurrently
*** In 46-edo
(0: 0 27) + (17: 0 17 38)
** in 31-et
*** 0 18 5' 14'
*** 0 25 40
*** wide whole tone: 0 6 11 17 22 28
 subset: 0 11 17 28
*** 17_ 23_ 0 8 14
 This is symmetric -- -14 -8 0 8 14.
*** using 0 11 22 as an extension
 0 18 25+[0,11,22] = [0,18,25,5',16']
   In 12ET that would be a 7#11.
   Works with a 3rd of 7 (m3) or 10 (M3).
*** (0 18 25) + (7' + (0 8 18 28))
 The second chord is a min major 7th starting at 7,
 that is a short minor 3rd above the octave of the power-7 chord below.
 (where a power-7 chord is 0 18 25, i.e. it's got harmonics 3 and 7).
*** maj 7 under a min 7
 in 12et it would be:
   (0 7  11)  (3 7  10)'
 In 31et:
   (0 18 28)  (7 18 25)'
*** (0 11 18 5')
 creates a 25 relationship from 11 to 5'
* mystery scales
** too many: 0 2 6 10 14 18 20 24 27
How to remember: it includes two stacks of four, 
  one starting at 2, the other at 20.
It's weird because it sounds like a familiar scale with an extra note
  between the root and fifth, and another between the fifth and the octave,
  but it's not clear which one is extra,
  because they're all pretty evenly spaced.
  (The intervals that aren't evenly spaced are from 0-2 and from 18-20,
  but for both pairs, the second clearly represents a distinct degree
  from the first, because 0 and 18 are such salient notes.)
** 9 notes, evenly spaced and harmonic: 0 4 7 11 14 18 21 25 28
* nice changes
** two minor chords, descending 4/31 from one to the other
but holding the fifth degree (18/31) from the first,
and between them play the dominant (major starting at 18) chord of the first.

