:PROPERTIES:
:ID:       1c1415bc-64d2-4cb3-9c65-b9b617d0777e
:END:
#+title: feature wishlist for an information-sharing technology
* automatic parsing from NL to graph
  When you input a statement,
  Hode should parse it automatically into elements,
  display the elements with IDs next to each one,
  and let you easily add more relationships between them.
* automatic translation
* personal internet crawling
  This poses a coordination problem. For many people to redundantly scour the same websites would waste their effort and potentially cripple the websites.
  It also poses a trust problem. Someone might claim to have scoured information for me, but not done so, because they don't want me to know it.
** more, maybe redundant
   Distributed, AI-assisted crawling, indexing.
   Some kind of hub would share what people are indexing
   (to the extent that they make it public),
   to avoid duplication of effort.
* Any kind of question about the data available to a user should be easy to state, to parse, and to contribute answers to.
* Feed algorithms users can make and share.
