:PROPERTIES:
:ID:       468a4341-ce88-4797-8123-cd16e210cd48
:END:
#+title: Fighting with foam rods is surprisingly fun.
* Diverse games work.
  People of widely different age, size, strength and skill can have fun playing against each other, as long as they're not too competitive.
* It's safe.
  If you stab rather than swat, and wear goggles, and don't run into or trip over anything, I suspect it's impossible to get hurt.
  Even if you swat like crazy it's safe, although it can leave a welt. Simple armor -- like, jeans and a sweater -- seem like they could solve that problem, although I haven't tested that.
* It's a good aerobic workout.
  Yes, so are most sports, but there's somethign about the immediate need to fend off an attack in the next 200 miliseconds that keeps me, at least, more consntantly on my toes than tennis or basketball doe.
* It's good reflex training.
  Its adversarial nature offers something that solo non-electric sports can't. (Virtual reality games can train your reflexes, but the haptic feedback from actual reality is probably still a lot better.)
* we played with some
  Manchego, Hugo's friend whose house includes a boxing ring and gym, had some.
