:PROPERTIES:
:ID:       f0fbcf23-a73e-4f0f-a08b-a0925d01c6ba
:ROAM_ALIASES: "marijuana industry in the US, Freakonomics on"
:END:
#+title: Freakonomics on the marijuana industry in the US
* ref
The Freakonomics podcast recently (today is <2024-11-19 Tue>) did four episodes on the marijuana industry.

The first episode was mostly medical, esp. comparing it to alcohol. The second is about the business. Each is something like half an hour.
* notes
** recently became more popular than alcohol
There are more (they said "far more" at least once, but I think most times they just said "more") daily marijuana users in the US than daily drinkers now, and the median age of a user is 35 ("no longer a young person's drug").
** doing it legally is crazy expensive
Anyone who sells cannabis can't deduct business expenses for tax purposes, so the effective *federal only* tax rate is around 70%!

Only 25% of legal dispensaries make a profit! The cost advantage of illegal operations goes way beyond the 70%+ tax advantage -- it also includes things like social security payments to employees and compliance with the Americans with Disabilities Act. ("They're making me put wheelchair ramps all over my farm!")
** illegal marijuana
*** It looks like legal marijuana.
Illegal vendors are impossible to distinguish from legal ones unless you ask to see their license. Cops have given up on shutting them down for some reason.
*** It is dangerous.
**** It is not tested.
Legal vendors have to test the shit out of their marijuana -- someone said it cost him hundreds of thousands of dollars a year. It can get ruined by, say, neighboring farms spraying pesticides into the wind.
**** There are legal incentives to make it bad.
Some law makes specifically delta-9-thc the illegal one. So breeders found ways to make delta-10, delta-8, or other compounds in abundance, the health effects of which are unknown.
