:PROPERTIES:
:ID:       fb83f180-cb75-4180-ab9c-eb555f8ecc1b
:ROAM_ALIASES: "relationships for Hode" "Hode relationships"
:END:
#+title: relationships worth recording
* an incomplete list
  surely incomplete
** that someone's edits on a topic were accepted by another for their version of that topic
** [author] would like to know _
** [subject] <does|did|will do> [verb] (opt: to [argument]) under [condition]
   The three tenses could be unified,
   reducing three kinds of relationships to one,
   by making the tense (time) a mandatory condition,
   whereas others would be optional.
** conditionals & cause:
*** [statement] if [statement]
*** [statement] because [statement]
** argument and inference
*** [statement] <supports | helps explain | proves | contradicts | implies ...> [statement]
** understanding people and their projects
*** [agent | project] stands to benefit if [statement]
*** [agent] believes [statement]
*** [person] wrote [statement]
** logic
*** maybe [statement]
    Implicitly, by writing "maybe x", one is saying
    "the possibility of x is worth considering".
*** not [statement]
*** it seems [statement]
    Implicitly, any such statement is an "it seems _ to [author]" statement.
** [statement] explains [argument]
** [statement] follows [statement] in [explanation, story, etc.]
** [statement] is part of [statement]
   "[_statement follows _statement] is part of [_statement]"
   can be used to represent multi-step arguments, recipes, stories
** [member] is in [category]
** [category] is subset of [bigger category]
** [action] results in [condition]
** [agent] wants [condition]
   agents and authors will likely overlap
* some observations on the list
** "is true" and "is false" are better unbundled.
   "_ is true" is really a bundle of
   "[author] believes [statement]"
   and some set of "[evidence] supports [statement]" statements.
** "[author x] suspects ([author y] believes [statement])"
   is just a nesting of two relationships,
   but could be particularly useful.
