:PROPERTIES:
:ID:       f34fb596-71fa-4327-97d8-c49302bd40b0
:END:
#+title: Genome , book by Matt Ridley
* The Congo River divides chimpanzees from their sister species, the bonobos.
* A lot of genetic disorders arise from genes that are helpful if you only have one of them.
** For instance, the gene which if you have two of it causes often fatal sickle cell anemia, has few side effects and protects you from malaria if you only have one of it.
* The Y chromosome collects genes that are helpful to males and harmful to females, and the X does the reverse.
* Chimpanzees can chase away leopards with sticks
* Arteries have shorter telomeres than veins, probably because they are subject to more pressure and need more repair. This, conjectures the author, is why we die of hardened arteries and not of hardened veins.
* Aboriginals and native Americans never needed to develop whatever gives you an easy time to adjusting alcohol, because they lived at such low population densities that they could drink untreated water. Today, they are very susceptible to alcoholism.
