:PROPERTIES:
:ID:       f53d79b9-6b3b-4d25-b747-f69344a14808
:END:
#+title: guitar intonation setup
* my question about it on Facebook (and many answers)
  https://www.facebook.com/groups/497105067092502/posts/2881188662017452/
* Chris Viasvil shared a fret calculator
  https://www.ekips.org/tools/guitar/fretfind2d/?fbclid=IwAR2mkWMZWxY3oDBoegz5ZVcrntsU_TnTiClDdl5ivvFoWz_HMHQ5PEDqngE
* Dave Keenan just puts a fixed setforth of 0.5mm on the zero fret
* Dave Keenan recommends this procedure
  https://www.proguitar.com/academy/guitar/intonation/byers-classical
* tension measurements bu D'Addario, via Dave Keenan
  https://www.daddario.com/globalassets/pdfs/accessories/tension_chart_13934.pdf?fbclid=IwAR2CJrlyWY7S3xgXQOjcEiemr8gt2hoHMVu6lKG-TQgb5-SZlH45LZXOHlg
* string tension calculator, via Paul Ehrlich
  https://wahiduddin.net/calc/calc_guitar_tension_from_size.htm?fbclid=IwAR0nWddUSYPtMfJrWuBe8MUxXqZ89UMkhBLc4_gS62T413cf5Hh0EvRjbtk
* something I found about "nut setforth"
  http://www.byersguitars.com/Research/Research.html
* individual floating saddles?
  Ehrlich to Battaglia:
  "I was going to tag you to check my work. Thanks for bringing up floating bridges, they always bugged me because bending one string temporarily flattens the others, so devices like the TremSetter are great -- and guitarists like Steve Vai use such devices but they never come stock on "signature" instruments.
I guess a Taylor series? Not sure how that would work but the idea is that we successively eliminate most of, and then even more of, the discrepancies between naive theoretical fret placement and intended pitches. I was thinking of another example where one must create a uniform magnetic field in an MRI using very clever placement of a small number of coil elements (each of which surrounds the patient at a different point along their length lying in the machine)."
