:PROPERTIES:
:ID:       2391129a-aec3-4f3d-b1f5-bb86a6d46aa8
:END:
#+title: Guns, Germs and Steel - book by Jared Diamond
* The peas we domesticated descend from the few mutants whose pods didn't explode.
  Other plants are like that, too.
* transferred from LI, recursively reversed
** An outrigger canoe is way better.
*** They just lash a couple logs to the sides of the canoe, so that it can't tip
** Linguistic evidence can be used to determine whether a culture had sheep.
*** If we know that a bunch of groups descended from a certain group had a certain date and place, and all those descendants have similar words for a thing, then it's probably because that thing was something the original group knew about
** Australia was similarly balkanized, because the few lush places were separated from each other by big deserts
** 1,000 of the world's 6,000 languages are in New guinea, an area just slightly bigger than texas. And of those, roughly half are spoken by no more than 500 people. The landscape of New Guinea forces incredible fragmentation. Most people don't travel more than 10 miles from where they are born, because movement is so difficult. The entire population was never more than a million people before Europeans arrived, whereas china, the mesoamericas, and Europe had pools of tens of millions to draw on, who spoke far fewer languages
** External threats Force Nations to join into a state. This happened to the cherokee, and it happens to the United States when it faced britain.
** Japan had the best guns in the world in 1600 or thereabouts, but abandoned the practice almost all together, until the US ship showed up in 1853.
** Longer lives raise the returns to invention
** The first writing systems were all accountancy, the demand for which is much much higher in a diverse agricultural economy then in a hunter-gatherer one. Not just the demand, but the supply is more favorable in a large agricultural society, because scribes require an agricultural surplus
** Human mothers in the New Guinea Highlands often nurse piglets
** Epidemic diseases need big, not everywhere densely connected populations, so they can burn in an area, then go dormant, then burn again. They therefore can't evolve in small tribes
** Female horses have a strict order of dominance, and walk in that order.
** When she does reproduce, several Brothers will chase a female for days, if I remember right. And that seems to be necessary to get the female to become sexually receptive.
** Some native American tribe was famous in the 19th century for being skilled hunters or warriors on horseback, but they only gained access to horses in the 17th century. Early and late centuries, respectively, so that's like a hundred years to learn
** It's likely not a coincidence that in New guinea, where the native plants were extremely low in protein, for instance 1% in tarot versus 22% in wheat, that cannibalism was practiced. Children in the highlands they're even today have the swollen bellies characteristic of a low protein diet.
** The fertile Crescent is special
*** The altitude of the region varies a lot over short distances, which allows farmers to plant at different altitudes and harvest at different times of year, rather than being overwhelmed by a momentary harvest everywhere
*** It is by far the largest Mediterranean climate, which gives it a diversity of Mediterranean species not found anywhere else, especially Australia, where the Mediterranean region is tiny
** Protecting an area with a net was an important development as we tried to domesticate plants. Otherwise, for instance, thrushes would poop on the places we regarding, and deposit seeds from the strawberries they like, which are very different from the ones that we like
*** Squirrels are probably the cutest case. They are burying acorns everywhere, and when they forget to eat one, it can grow into a tree. We can hardly compete.
** There's not a bright line between hunter-gathering and farming
*** Farmers were less healthy and worked harder, as a fraction of the day.
*** And of course a population could do both.
*** Hunter-gatherers traded with farmers in the Americas and Africa. In many cases they chose to continue hunter-gathering even though they understood farming
*** Hunter-gatherers would clear competing plants to allow the ones they wanted to grow to grow, and take only the part of the plant that let it live, so that it could keep growing, and aerate the soil when they took something out of it. At least some hunter-gatherers did all of these things. The only thing left that they would need to do in order to qualify as farmers is to transplant the seeds intentionally
** Other kinds of specialization also require that kind of food surplus. Scribes, in particular, enhanced productivity enormously by preserving more information than would otherwise be possible
** Classes of political elites seem only to exist where there is the capacity to store food, that is, in agricultural societies. Which are also much more dense
** Hunter-gatherers reproduce around every 4 years, whereas people in farming societies do it about every two years. This is likely because hunter-gatherers have to be able to carry their children, so they can only afford to have one tiny child at a time.
** In Australia all the megafauna went extinct right around when humans arrived, so there was nothing to domesticate.
