* how to upgrade RAM
Some of this only applies to the Dell Inspiron (2017, i5)
that I did it to (January 2020).
** PITFALL: 2 slots of different sizes?
*** in short
It seems to be:
The output from dmidecode shows the size of the installed RAM correctly.
But if a slot is empty, it shows it as DIMM when in fact it should be SODIMM.
To know for sure one ought to look at the motherboard schematics.
But I just gambled that they'd both be the same, SODIMM (the laptop size),
so I bought that, and it worked.
*** asked Reddit
are there two slots of different size, onne SODIMM and one DIMM?

[jeff@jbb-dell:~]$ sudo dmidecode --type 17
[sudo] password for jeff:
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x003B, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x003A
        Error Information Handle: Not Provided
        Total Width: Unknown
        Data Width: Unknown
        Size: No Module Installed
        Form Factor: DIMM
        Set: None
        Locator: ChannelA-DIMM0
        Bank Locator: BANK 0
        Type: Unknown
        Type Detail: None
        Speed: Unknown
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown
        Configured Memory Speed: Unknown
        Minimum Voltage: Unknown
        Maximum Voltage: Unknown
        Configured Voltage: Unknown

Handle 0x003C, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x003A
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 8192 MB
        Form Factor: SODIMM
        Set: None
        Locator: DIMM B
        Bank Locator: BANK 2
        Type: DDR4
        Type Detail: Synchronous
        Speed: 2400 MT/s
        Manufacturer: SK Hynix
        Serial Number: 71DB323B
        Asset Tag: 01173300
        Part Number: HMA81GS6AFR8N-UH
        Rank: 1
        Configured Memory Speed: 2133 MT/s
        Minimum Voltage: 1.2 V
        Maximum Voltage: 1.2 V
        Configured Voltage: 1.2 V
** MUST match: CAS latency, timings, and voltage
** search term
SK Hynix SODIMM DDR4 8GB 2400MHz
SODIMM, DDR4, SK Hynix, 2400, 8192 MB
** chip properties via `sudo dmidecode -t 17`
type: DDR4 ("Synchronous"?)
Form Factor: SODIMM
Locator: DIMM B
width (total & data): 64 bits
voltage: 1.2 V
size: 8192 MB
Speed: 2400 MT/s
Configured Memory Speed: 2133 MT/s
Manufacturer: SK Hynix
** latency: 13.750 ns
$ sudo modprobe eeprom
$ decode-dimms
Minimum CAS Latency Time (tAA)                   13.750 ns
