:PROPERTIES:
:ID:       23121d2c-476e-4894-a67e-51e395fe0514
:END:
#+title: Helen Falk Brown : early life
* sent to Cliff, Jamie, Matt, Christine and me, <2024-01-23 Tue>
  https://mail.google.com/mail/u/0/#search/benita/FMfcgzGwJmPkbtMNZQwHSnhlfsTvDbKp
* Benita's foreword
  I have been wanting to type up this account by Mom that she created for my birthday many years ago, and I finally did it. Thought each of you might enjoy reading it. I think, Cliff, that you have a copy of her handwritten document. I wish she had included much more about her time with the Red Cross, and continued it through the years on the Skagit, but I am glad to have what she did write. I tried very hard not to make any changes, and to just transcribe it exactly as she wrote it.
* what Helen wrote
  My first recollections of life are brief episodes that occurred during my first 3 years when my folks were ‘proving up’ on 360 acres in s.e. Montana, 60 miles s.e. of Miles City. Daddy had built a tarpaper covered shack for our home. There were no interior walls nor any kind of insulation despite the bitter, sub zero winters & howling winds that blew across the barren prairies. On one such morning I recall Mom holding a tiny puppy over the cookstove, trying to thaw it out. Our shepherd dog, Peggy, had delivered puppies during the night. I don’t remember if Mom’s efforts were successful, but the scene lingers in my mind.
The little house was very sparsely furnished. Apple boxes served as cupboards and storage units and also chairs. Other apple boxes served as toys for Harris & me. We could stack them or play in & on them, wut were not allowed to put our feet on the ones that were chairs–our first lesson in respecting furniture.
We had 2 horses, Bill & Shrimp. Bill, our favorite, was a very patient, gentle creature that we kids could play with & run around and under him, as well as ride bareback & he seemed to enjoy the activity as much as we did. The horses were used to pull our buggy to the nearest village called Pineal. Dad had a blacksmith shop there, & later moved it to our homestead, near the house.
On Saturday nights Mom & Dad hitched the horses to the buggy. With coats, blankets and a kettle of beans, we went to a dance at the school in Pineal. Kids were always bedded down on the floor of the coat room, & surprisingly, we slept through all the music & noise.
Dad had a  garden that he watered by carrying pails of water from the well. Harris & I helped by carrying jars of water. However, vegetables were a scarce item. Our diet consisted mainly of beans, pancakes & biscuits. After the necessary 3 years of residence, we moved to Spokane where Dad soon found work with the railroad during the r.r. Strike. Kids used to taunt Harris by saying “Your dad is a scab” (a name given strike breakers). When Harris asked Mom what they meant, she knew, but explained to him that a wound needs to form a scab before it can heal. Thereafter, when he was taunted about our dad, he replied, “Your dad is a raw sore, don’t you wish he’d heal up?”
The folks paid taxes on the homestead for about 20 years, expecting gas or oil to be discovered. It finally happened, but after Harris, who had the title to the land, had forfeited it rather than pay taxes.
In 1925, Dad & Mom bought 4 wooded lots between 33rd and 34th Ave. A 2 room house sat on the rear of 1022 33rd. We moved into that and Dad began digging a basement with a hand shovel on the front of the lot. His days began at 5 am when he got up, fixed his breakfast, packed a lunch and took the street car to the Northern Pacific depot where he boarded a work train to the r.r. Shops in the valley. His return home after 10 hours of work was the same situation in reverse.We didn’t get a car until about 1933 or 4. That made life easier for him, but he always worked on the house after returning home. Our collie dog helped dig
that basement. When the digging and the foundation for the new & enlarged house were complete, he and some of his railroad buddies rolled the little house on some poles up and over the new foundation. Harris & I were spending that summer in Minnesota with our Grandma Falk & our 2 uncles, so we weren’t around to witness the house moving. That was the only help Dad had building the house except for hiring someone to plaster the living room. The framework and subsiding for the house were obtained by tearing down old box cars. He even made the furnace, utilizing scrap metal. First it burned coal, then was changed to burn match blocks, later sawdust & finally rebuilt for oil.
On Dec. 29 in 1928, Doris Mae was born. She was only 5 lbs at birth and critically ill all of her short life. Mom and Dad fretted over her both at home and while she was hospitalized and also worried about the medical expense, especially when the hospital rates went from $5.00 to $10.00 a day. Soon after her death came the fall of the stock market. Dad’s work days were cut from 6 days per week to 5. I’m not sure he was cut later to 4½ days, but I recall them worrying about it, but he never lost his job as did so many others. In the early 30’s, he began having serious health problems which required trips to the railroad hospital in Missoula Montana. There was no health insurance in those days, nor paid sick leave. These events and situations slowed down & often stopped progress on the house, which wasn’t completed until I finished the 8th grade. Despite all their problems, Dad usually sang or whistled while he worked. He also taught himself to play the violin & chord the piano.
We always had music at home. Mom played the piano until I learned to play, then she seldom touched it, but we all sang together. Despite money shortages, the folks managed to give me piano & dancing lessons, but they were curtailed during Daddy’s hospital visits & recovery periods, but after I was in high school I learned to play the French horn at no expense & the band soon became an important part of my life. Big name bands often came to Spokane & played at a large ballroom (The Nat). My dates were always band members and we gathered around the band podium to watch and listen, as well as to dance.--great memories!
After high school graduation & still depression years, I  was able to attend college because educational colleges, as teachers colleges were known, didn’t charge tuition. We also had railroad passes thant  enabled me to live at home and commute to Cheney. By catching a city bus near home, I rode down to the depot and boarded a work train that stopped at Cheney on its was to Grand Coulee dam which was under construction at that time. The train arrived in Cheney in time for us to get up the hill to the campus in time for an 8 o’clock class. It was supposed to return from the dam to Cheney about 5 pm, but was often late. It carried dam equipment going, & often crates of chickens or caskets, often casualties from the dam on the return trip, but it had about 12 passenger seats in the car also next to the freight.
During the 2nd and 3rd winters I earned enough money playing the piano for dancing & gym classes and also by “hashing” in the dining hall that I could live in a dormitory. Surprisingly, my grade point improved and I enjoyed college life, too.
So far, this chronicle sounds as tho my childhood & youth were quite bleak, but that wasn't at all the case. Despite not having much money, living on 33rd was a wonderful place to grow up. The pine trees were great for tree houses & for wire slides fastened in the top of the tree and sloping to the ground with a short pipe to hang on to. The neighborhood boys dug many clubhouses on the vacant areas. Before a sewer was installed on 33rd, the entire area between 32nd & 33rd, which was quite low, flooded after the snow melted and made a lovely pond. We took the rectangular sement mixer Dad had made & daddled around in it. The boys also made numerous rafts to paddle both there and on Perry pond at the end of 33rd. They also diked perry pond, then the fire dept. Flooded it regularly for ice skating. They also kept Manito duck pond flooded frequently so it was always smooth ice. They furnished firewood & maintained bon fires at Manito park which was also our favorite sledding area.When we were teenagers, we liked to skate down on Hangman creek where we could go for many miles. Perry pond was also fun in the spring with many spring flowers on the surrounding areas & polywogs, or tadpoles to catch and take home to watch them develop into frogs.
Dad used to make crystal sets before radios became affordable. We took turns wearing headphones to listen. When radios became common household items, on a summer evening when everyone’s door was open, we could walk from our house up to Grand Blvd. and seldom miss a word of Amos & Andy, a radio comedy that the entire country would turn to. The same situation occurred on Sunday evenings when everyone tuned into “One Man’s Family,” a popular radio soap opera. Many of the radio programs were local broadcasts. We sometimes went to the downtown studios to watch the live broadcasts, which were usually local musicians or orchestras.
After dark, the neighborhood kids got together to play kick the can, Washington Punch & etc. Without t.v. or much money, kids were very creative and seldom bored, so it was a happy childhood.
My first teaching job was at Steptoe, Wa. where I taught 5th & 6th grades plus music. On December 7 that year, Pearl Harbor was bombed. The following morning we 4 grade school teachers took our classes upstairs, which was the high school. The entire school listened to the radio together as Franklin D. Roosevelt announced to the nation the attack and declaration of war. What a sad time that was, and one by one all the boys I knew left for the military.
The next year and ½ I taught at Deer Park, north of Spokane. I terminated my contract mid year after being accepted by the Red Cross. After a training course at American University in D.C. I became a hospital recreation worker at Baxter Hospital. The staff lived over the rec hall and that was my home until the end of the war. I resumed teaching in Aberdeen for 1 year and then in Seattle which had always been my dream. It was there that Ben & I met in a boarding house. We were married nearly 7 months later and bought a house near Green Lake where we lived for just 1 year until he was hired by Seattle City Light to work as an operator at Diablo on the Skagit River. That would be another lengthy chapter that I won’t include in this chronicle. So far it’s been a happy life & I believe a productive one. My blessings still outnumber any problems.

Helen Falk Brown
January 1996
