:PROPERTIES:
:ID:       d5a5a3ff-977a-405b-8660-264fb4e974a3
:ROAM_ALIASES: Hode
:END:
#+TITLE: Hode (application)
* TODO : merge with
** [[id:9c5619e5-81ad-4a67-9705-e4761bdd6839][shareable knowledge gardens]]
** [[id:41844d8a-f352-4e2d-8ba3-3c83b2dd2ac3][oscillable generations view for org-roam]]
** the TODO items in [[id:63f366e6-b768-4f3f-9093-a776f2b4e069][org-roam]] (inc. extend)
** [[id:9e45ccd9-d6e0-4870-8f13-cc11135334d0][how to use a knowledge graph]]
** [[id:55dae027-0053-4557-ba7e-2a36ef679cb4][SmSn]]
** [[id:adb6d4a3-e7db-4880-b757-67bbe4fb425a][features I want]]
* see also
** [[id:b37024f7-716b-4748-9a33-d35e75f4ede1][epistemology]]
** [[id:e2b7487d-7cdd-4a8d-b9ce-26f941ae05ec][information theory]]
** [[id:e7c3c0cb-4db7-4a4c-89b9-666e91ec67ae][networking minds]]
* u
** "bootstrap" would be a cool name.
** build [[id:5346e42f-5cf6-4af9-8efa-564cd350e104][Hode with TypeDB and Emacs]]
** [[id:d674bf8d-cd41-47aa-8418-36a74cedd561][build Hash for TypeDB]]
** [[id:8c609b95-5f55-4d88-b0fa-b43227577ee7][I want a record of the (org-roam) files I read]]
** Each topic is a perspective. Each subfile is a sub-perspective.
** Should read the git diff and make it possible to see easily where a node was moved of it was deleted from a file
** Are any of the relationships more than binary in a way that could not be easily handled by making the third and other members of the relationship into properties instead?
** A view of a relationship
*** Would look like a file with two top-level headlines equal to the two members of the relationship, and below each, a view child indicating its relationship to the other from its point of view
* Private additional notes on a topic ought to explain how to modify the public view of it.
  This way the public view would not need to be cluttered with (potentially suspicion-inducing) links to private notes.
  But in this case changes to the public note become more difficult to integrate into one's mixed public-private view of it. For instance, what if your view includes a private grandchild and they remove its grandparent? Maybe they accounted well for all the other contents of the change but not yours. You ought to be able to see that their change affects private nodes they could not have taken into consideration. That said, their change is likely to suggest a way to resituate the orphaned private node.
* TODO [[id:02216718-4464-4017-93ec-942545f7376c][make the org-mode diff easier to read]]
* [[id:3ddd4a73-22df-4df2-a004-1a0a5d8be27e][Einstein's Olympian Society]]
* [[id:2a1c0d5e-81ac-46a8-a349-f3715428ac4e][promote "_ feels _" notes : a generalization of trigger warnings]]
* [[id:dc937226-1a31-4d76-b4c2-702c28a43482][sharing org-roam notes , both reading and writing]]
* probing capabilities
** DONE URI schemes' robustness to huge popularity.
*** The org-roam URI scheme is quite robust.
    Each URI has 32 hex characters,
    so 16^32 = 3.4e38 unique values.
    If each of the 8e9 people on earth had 100,000 notes,
    there would be 8e14 notes.
    The probability (use the birthday formula) of a collision
    would be about 1 in a billion.
*** The SmSN URI scheme is not.
    It only (52*2 + 10)^16 = 4e28 unique URIs.
    If everyone had 100,000 notes as above,
    there would almost certainly be a collision.
** DONE Do TypeDB from Rust in Docker
   TypeDB has no C++ driver yet.
** DONE Call C++ from Emacs
   [[/home/jeff/code/emacs-ffi-to-cpp]]
** DONE Read the org-roam db from C++
   [[/home/jeff/code/cpp-for-org-roam-db]]
* naming the app
  "Why"
* minimal hode building on org-roam and smsn
** capabilities
*** Make visible a count of each node's descendents.
*** Links have two kinds of descendents: in this file and in the linked-to file.
*** Parent relationships can also traverse multiple org- (within-file implicit tree) links.
*** Order is hard.
**** Disagreements about order might be hard.
** data model
*** Links can be used as relationships by preceding with a keyword likee ~via.
*** Notes can have non-headline text.
*** Any node N can be used as a relationship.
    by making it an org-roam mid-generation,
    and prefixing the link to N (after the bullet) with "~".
*** Have different views of the same nodes.
*** Perhaps in one file (i.e. view from a topic) one should be able to link to a path descending in another file.
    e.g. under "humility", might link to "courage > thinigs that require it"
    this link could be written "things that require courage", and indeed that could be the default name of the path "courage > things that require it". The link might appear from the view of the "humility" file as a single headline, but with some symbol indicating it is a path in another file, rather than a file itself
*** ? For order, each note should have, for every POV from which it might be seen, a list of children.
    arguments for and against
**** PRO: Makes diffs highly readable:
     If a top-level headline is moved, its children stay fixed.
     There is only a one-line insertion and a one-line deletion.
     This is particularly important if users receive pull requests:
     they won't want to read complex diffs.
**** CON: Makes files hard to read without special software.
** things to be able to see
*** From file F, if F links to node N, see that N also links to F.
*** nah
**** From link L in file F, if L links to node N, and L has children in F, show that N has children not shown in F.
* methods + demo code
** [[id:66a0b19d-a524-4ad0-b920-65fc701f78c4][exploring the org-roam db]]
** Emacs org-mode column view
   https://www.gnu.org/software/emacs/manual/html_node/org/Column-View.html
* pitching it
** Don't mention hypergaph v. graph. Just call it a graph. The important thing is to be able to connect stuff as if in space rather than on a line.
* capabilities
** join SmSN, org-roam
*** make a minimal model that can support them, plus the (untyped) user-defined relatinoship on n items and a label
** permit someone online to judge your notes
*** This would require identity management.
    The simplest form would simply be "choose a name nobody else will choose".
* There should be bubble actions.
  Nested circles of "I think this word is like that word", so that someone could filter what they see that way.
  They could be as vaguely personal categories as negative/positive. Different peoples' could differ a lot, with perfect validity. One could choose to see an equivalence class [on (term)] the way the majority see it, once (if you wanted) there was a sufficiently large majority who had voted.
* [[id:3ffa3b8d-64b4-4805-9a10-4f3db3d9f56c][Who is where to me? What information do I [share, have in common, ?associate ..] with who?]]
* [[id:119cd4eb-25a8-41fd-a763-0368bb2e53e6][graph voting]]
* share subcategories useful for a topic
* [[id:562876f3-9608-4ebe-9ab1-f119188ffa32][Define relationships using ordinary org-roam syntax.]]
* [[id:3cc52030-7085-4633-9158-88b6c92872a8][cold email advice]]
* [[id:f8a53f00-6a18-4c44-b318-bdd411466005][Write the app data-first.]]
* [[id:49a03bb3-7d57-4e38-89a5-93074d8fd152][Information (all of it) is truth ,, if properly qualified.]]
* [[id:37f7be50-9b2c-4426-b288-e83225b6d5d8][expressivity voids , observed]]
* share git history views
  motivation : Use TypeDB to make something simple but useful.
  Haven't figured it out yet.
** for smsn
** for org
** for plain text
** for code
* [[id:af35bd7c-4d89-4af9-9706-a884792609ed][mind map merge , Josh]]
* [[id:ac81d8d8-4a61-4a38-ba3c-981a2148d484][in-tree promotion]]
* [[id:29903b27-2b73-4a1b-a8d8-257c219fe70e][an introductory sketch of Hode]]
* Golden Retriever would be a funny name.
* [[id:ec977e2d-46b9-455f-8be0-fb3eaba4c2ca][problems Hode might help]]
* [[id:97c7fdde-181b-4a9e-b210-cc380b8afb8b][Hode usage and gameification]]
* [[id:fb83f180-cb75-4180-ab9c-eb555f8ecc1b][relationships worth recording]]
* [[id:e2911eb2-2d2f-4f8b-9de8-31356bb89df1][things Hode would enable]]
* [[id:1369d33e-8671-40ed-8401-4bf7597202c1][outcome goals for the coommunity]]
* [[id:1c1415bc-64d2-4cb3-9c65-b9b617d0777e][feature goals for the technology]]
* [[id:663aa255-2dc7-4fdc-89bf-43e392d7cdc1][instructional videos for software, how to make]]
* [[id:3b8d3bb0-b32d-41c5-a548-ce93bea8d150][Hode & TODO]]
* unsolved
** [[id:4770a0d4-1932-403c-a57a-9ae803e8372e][gameifying knowledge base curation]]
** [[id:bc0ba15e-6be8-4c0a-851c-0660c70de2b4][information sharing and cryptocurrency]]
* art about it
** [[id:2faccb5e-d642-4d15-83fa-9d4b7b315880][Hode not as app but as perceptual lens]].
* DONE
** [[id:fbb345d3-1e65-414a-8e68-23c225d51f4d][problems I saw in Hode when I quit the version I was working on in 2021]]
** [[id:2b735c4f-b4d9-4d7d-9155-b650d90a2c4a][abandoned : coding Hode in Haskell]]
