:PROPERTIES:
:ID:       d5a5a3ff-977a-405b-8660-264fb4e974a3
:END:
#+TITLE: Hode
* u <2024-09-02 Mon>
** Cancel culture exploits the internet. It would be good if hod were difficult to exploit in similar ways.
** ForcEd mixing of political views?
** Breadcrumbs: starting from
        nothing, what can you believe?
*** Make paths through subjects (math, etc.), explaining how to check each claim.
** Be able to make queries like "does this person only produce content with a political slant?"
** Twitter tried deemphasizing followed count and letting people subscribe to tópica rather than people
** Facebook tried the oversight board.
** Along with like button, true/false buttons
** Warn friends, appointed as one of their editors, if a joke seems dangerous
** A private dislike button
** Belong to multiple communities, each with their own currency, and you can exchange one for the other. In this way communities can gobble each other, in a way that enables algorithms that people enjoy more to dominate.
** Pull your resources with friends to scour the internet in a particular way.
** Intimacy is permissions
** For people to record "you seem to believe _" could be helpful to you, as well as to them.
** The resources available for contribution are computation, memory, data transfer (to and from their own systems) and maybe money. And owning a share of the network means owning exactly those. Maybe there should be multiple currencies for each network, e.g. a memory one, a computation one, etc.
** Someone should be able to say how they honestly feel
** Can a bot lens the discussion into Spanish? I know smart Spanish speaking lawyers, journalists, etc.
** Diversity of opinion makes objectivity easier.
   For instance, when psychology was more homogeneous, it was widely accepted that homosexuality was an illness.
** [[id:4bf9081d-e4f6-497d-b80d-34bf28bb6e6a][Wikipedia's governance principles]]
** [[id:3a301def-9a9b-4c2c-8bcd-aa55ae98b650][The Constitution of Knowledge, by Jonathan Rauch]]
* Hode development & social
** [[id:7863cf17-0940-4663-82b2-2a22b3878f1c][funding Hode]]
* tools for Hode
** WordNet seems useful.
   "where nodes represent words, and edges represent relationships like synonymy, antonymy, hypernymy (is-a relationships), hyponymy (type-of relationships), and meronymy (part-whole relationships)." -- ChatGPT 4o, <2024-08-31 Sat>
** [[id:42458f39-c09a-4af4-82da-1bd74967b046][Yi is a Haskell library for building text editors.]]
** ? someone wrote a tree editor
https://cs-syd.eu/posts/2019-06-28-microsmos
and then a forest editor:
https://cs-syd.eu/posts/2019-08-28-millismos
* context | thinking about \\ Hode
** [[id:f511db82-1ecb-457e-888f-e5dbe149eff8][Our tools mediate our understanding of the world.]]
** [[id:9d074ed1-9683-448d-8041-b14364c6a6b2][notes from Eli on "fractal democracy", Eos, Cardano]]
* [[id:2b735c4f-b4d9-4d7d-9155-b650d90a2c4a][defunct : coding Hode in Haskell]]
* non-technical problems with Hode
  :PROPERTIES:
  :ID:       78f08663-9236-486e-8343-2d1798bc5994
  :END:
** Hode is hard
I got a lot of interest on Reddit Haskell (at least 85 net upvotes),
but no follow-up. I think the documentation scared them away.
*** TODO Add a quick-start guide to Hode.
    :PROPERTIES:
    :ID:       16331ee3-3b35-4cc0-8a21-5ee56e814c61
    :END:
** It's hard to judge without an interesting graph.
*** would help: smsn
** Am I stumped as a user?
The number of ways to represent something is huge. Paralyzingly huge.
* Who cares?
** Library and Archival Sciences
   Offray suggests:
   https://mail.google.com/mail/u/0/#inbox/FMfcgzQVxtrHThcSnZcsdhQnSnCRxqrT
** TODO Projects with extremely similar goals
*** "Knowledge Representation" research community
https://en.wikipedia.org/wiki/Knowledge_representation_and_reasoning
*** Agora
Extremely similar goals, envisioned user experience.
https://flancia.org/agora/
*** Perkeep
Extremely similar goals.
https://perkeep.org/
*** Cyc
knowledge base for AI
https://en.wikipedia.org/wiki/Cyc
** TODO websites for announcing stuff
https://app.ryeboard.com/card/92672dba-a4a8-4be0-88db-b4feca771afa
https://news.ycombinator.com/item?id=21812786
** "convergence"
https://link.springer.com/article/10.1007/s11051-019-4638-7?wt_mc=Internal.Event.1.SEM.ArticleAuthorIncrementalIssue&utm_source=ArticleAuthorIncrementalIssue&utm_medium=email&utm_content=AA_en_06082018&ArticleAuthorIncrementalIssue_20191108&fbclid=IwAR08OarPih1ava0yDKrM_PK07xLSZ2ZSV_bzmvukc7RpNzQQHNzvRa8qxs8
** fake news
https://www.fakerfact.org/about
** "navigating digital information"
https://www.youtube.com/watch?v=M5YKW6fhlss&list=PL8dPuuaLjXtN07XYqqWSKpPrtNDiCHTzU&index=11
** distributed search
* [[id:663aa255-2dc7-4fdc-89bf-43e392d7cdc1][instructional videos for software, how to make]]
* TODO collect use cases
** view notes from a text ordered by source text or topic
** collective note taking
https://blogs.agu.org/geoedtrek/2016/12/28/collaborative-note-taking/
** google isn't that great
https://news.ycombinator.com/item?id=21515181
https://stratechery.com/2019/the-google-squeeze/
