:PROPERTIES:
:ID:       9e45ccd9-d6e0-4870-8f13-cc11135334d0
:ROAM_ALIASES: "how to use a knowledge graph" "how to knowledge graph"
:END:
#+title: using a knowledge graph
* "How to use knowledge"?
* responsibilities
** Responsibilities to yourself
*** If you (habitually) write to it, revise it.
**** A note accreted to and then observed as a collection might reveal itself to be a bad idea this way.
     How that happens is fun, and probably worth understanding.
*** Write diverse things.
**** topic
**** kind of analysis: goal, methods, consequence, level of abstraction
*** Qualify your opinions.
    Some things you believe. These can go without a herald.
    If it's a suspicion, or something you doubt, etc. make that clear.
*** Employ atomicity.
    in Andy Matuschak's sense
*** Provide enough context.
    Many (most interesting?) two-member labeled relationships illuminate more than three concepts.
*** Aim for universality, at least sometimes.
    More universal = more people who might find the idea useful.
*** Dare to record your insights.
    In short time, revising them will surprise you.
** Responsibilities to others.
*** Dare to imagine others want your insights.
*** Dare to imagine you need others' insights.
*** Download, read and link to other peoples' notes.
* Sermons repeat. Branch lists could repeat, or more generally include musical instructions.
** Scalars like "mass" or "value".
* TODO merge
** [[id:ce9e0a8d-19fa-48eb-9d0e-6cedcb0fdc99][notes, how to take]]
** [[id:7b2cd1a3-bac4-4057-90e3-a2698a2fdefb][consult your notes : why and how]]
** which one
*** There should always be a "recent, unmerged, serial as written" bucket at the end of the sorted list, to put new things without having to disturb train of thought elsewhere.
*** Always append at the end, and order from the top.
    And mark the last node to be ordered.
    More generally, keep a list of line unmbers when nodes were visited in each file. A frequent enough git commit history would have this property.
** the u bucket
*** automatically add a "new & unmerged" bucket at the {bottom for others, top for the author} of each list
**** they should be orderable by age*
     (*) and maybe by other things
* An "about the order of these branches" branch, first among them.
** technical
*** Generalization: A leading "about this tree's structure" branch.
    But I'm not sure I would use that freedom.
* A valid read technique is to read the whole file before deciding which links to follow.
* a read-write equilibrium
** good arrangement requires knowing how you read, and vice-versa
   e.g. if you know you'll read from the top down and from root to leaves, then your choices of what is how high, what is nested, and what is behind a link are all important.
* Can there be a read algorithm? To [[id:5e3a5ad9-f733-45fe-a7f1-55dcc0ce2bed][direct attention well]]?
* ? Give everything a context.
* Maybe don't start new roots.
  Rather start from inside a document,
  and then maybe add contexts and separate it.
** not sure
   Should everything new graft onto a historical context,
   even if one is always in easy reach?
* [[id:61f58054-3032-4e45-bfda-dbc278c040d7][graph writing = priority choice]]
  When (on average) working on this topic I want
  these ideas visible in this order.
* [[id:84a8e1b0-baa5-4435-a564-a921e45e24de][the collector's fallacy (for information)]]
* more reasons to classify a node once created
  In the class you might have a synonym.
* [[id:b3783193-5288-4336-8a99-d58a545bb4b2][mindmapping can usefully be compared to improv]]
* processing
** TODO How should your knowledge graph prompt you to read?
*** That is, outside of it, other people's work
* seem to help
** When lost, look back at your reading history.
* [[id:1989f694-7acc-433f-aae6-7e7146abd9cc][how to file a note]]
* Don't worry about losing conscious track of any note -- losing track is, in fact, critical to successful usage of a knowledge graph.
  Even if you perfectly anticipate and curate the set Y when you create the new note, it's possible that you won't look up anything in Y for a long time. That's fine! Continuing the above example, suppose the note you wrote was about love and how to avoid burnout at work, and you put it under those two things, and then never looked at those two things. That means those two things weren't an issue for you.
reading and rewriting my notes
* Be clear on the purpose.
  Shuffling mindmaps is not something I do for the mindmap's sake!
  It is how I think.
* Remember that I like rewriting my notes.
  :PROPERTIES:
  :ID:       2597d25f-e6f5-488e-aa52-277dd287526b
  :END:
  For some reason this is hard.
  I learn the lesson repeatedly, and it surprises me each time.
** Maybe the question is *when* do I like it?
   :PROPERTIES:
   :ID:       99721b37-30b0-4475-81fa-42b6f67e6ec8
   :END:
   Do I like it when it's productive?
   Do I know when it's productive?
   Do I like reading/organizing a topic when I've been procrastinating the topic? (I think so.)
* [[id:28f244af-3876-4302-8aa6-4e2306024149][Hegelian synthesis is a fun knowledge graph trick.]]
* [[id:2a1c0d5e-81ac-46a8-a349-f3715428ac4e][promote "_ feels _" notes : a generalization of trigger warnings]]
* how to read a knowledge graph
  :PROPERTIES:
  :ID:       7b2cd1a3-bac4-4057-90e3-a2698a2fdefb
  :END:
** Read like a [[id:5498fb6a-fcf2-49e4-a6d0-aa30a615301d][rushing paleontologist]].
** Know when to read it. Treat them like Google.
   When you have an itch to do anything, part of scratching it should be to look in your notes for anything you've already written on it before.
** Consult the upper onotology, too.
*** the idea
    Check out notes that link to what you're reading.
*** why
    When you visited the current file -- say, "how to program in Python" -- it's likely not because doing that was your motivation per se, but rather some bigger project was, like "programming". And the latter probably links to the former. Looking "upward" will bring it into view, and thereby both remind you of your larger purpose(s) and of context and methods relevant to those purposes.
* learn to search your notes
  If the note exists, usually it's not hard to find -- even if you didn't curate its parents well, you can grep your folder for relevant terms.
* [[id:5cfb00c4-3302-4b47-8ee0-1814d5869937][Don't restart from scratch.]]
* [[id:5b7900ff-1792-47d1-a55a-8435f8766baf][Don't build premature structure when mapping knowledge.]]
* [[id:23f40301-92d8-48d5-9c5a-d28b334acf02][Random, motivated, "generous" note navigation seems promising.]]
* [[id:05a84243-9dcf-4492-b81e-a48fd2f53b3c][knowledge graphs and/or meditation]]
* [[id:514fe55a-d22c-4e6a-9b0f-3a01a89742db][Review notes before any high-pressure situation.]]
* [[id:d283b6a3-205b-4a7c-9338-aa458f091691][Use my "prefix-date-uri" script.]]
* [[id:30478629-506c-4acf-aec8-b74e977a2234][how to take notes on people and communication]]
* [[id:9e45ccd9-d6e0-4870-8f13-cc11135334d0][how to avoid losing notes in a knowledge graph]]
