:PROPERTIES:
:ID:       57c6f456-dfd1-4797-a4ce-db2d82cb726e
:END:
#+title: HTTP requests
* "get" methods encode the submission as plain text
  """
  GET is suitable for things like a web search form, because
  the URLs that represent a GET request can easily be bookmarked, shared, or
  resubmitted.
  """
* PITFALL: "get" actions are insecure
  """
  GET would also be unsuitable for a password form, because the password
  would appear in the URL, and thus, also in browser history and server logs, all
  in plain text. Neither would it be suitable for large quantities of data, or for
  binary data, such as an image. A Web application that uses GET requests for
  admin forms is a security risk: it can be easy for an attacker to mimic a form’s
  request to gain access to sensitive parts of the system. POST, coupled with
  other protections like Django’s CSRF protection offers more control over
  access.
  """
* If a submission modifies the data on the server side it should be post.
* "form-encoded" requests
  :PROPERTIES:
  :ID:       96705fe3-b12f-4068-8ff4-5349e2b2e115
  :END:
  https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
** I think that encoding is specified in the header, thus:
   Content-Type: application/x-www-form-urlencoded
** how keys and values are encoded
   "in key-value tuples separated by '&', with a '=' between the key and the value"
** Non-alphanumeric characters in both keys and values are "percent encoded"
   https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding
   "this is the reason why this type is not suitable to use with binary data (use multipart/form-data instead)"
