:PROPERTIES:
:ID:       5333d0f7-f7dd-459c-a2c9-b195ad71c961
:END:
#+title: intelligent channel manipulations in Reaper
* refs
** I asked the forum about this.
   https://forum.cockos.com/showthread.php?p=2641443#post2641443
** [[id:c9734ff4-b0a0-4132-9f84-87e78eb67246][bigger piano roll in Reaper, I asked for a]]
* SOLVED, mostly
** the solved problems
*** There are builtin "show channel" shortcuts
    for channels 1-10, and one can define one's own for channels 11-16, and for all channels at once.
*** Increment/decrement channel for selection is called "set channel lower/higher".
*** To draw on a different channel, use "set channel higher/lower for new events".
** unsolved : show more than one but not all channels
   The one thing that's not possible from the Actions menu is setting the view to show a number of channels greater than 1 and less than all of them. I only see how to do that by clicking around in the Filter window from the MIDI editor. If I really need that I'll look into ReaScript but I suspect I won't bother for a long time at the least.
* features required
  Be able to do any of these quickly, i.e. from the keyboard.
** Filter the view by channel
** Change the channel on which notes are drawn (by the mouse).
** Inc/decrement the channel value of every selected note.
* some of it is already possible
** show channel : Shift + number (see Actions menu from MIDI editor)
** increment channel : "set channel lower/higher"
   I gave them the shortcuts C-S-M-+ and C-S-M--
   (that is, every modifier and + or -).
* but changing the draw channel does not look possible
** the closest I find is this
   Set default mouse modifier action for "MIDI piano roll left click" to "Set draw channel higher/lower"
