:PROPERTIES:
:ID:       650e028b-8662-472f-a81a-437592442862
:END:
#+title: Internal Family Systems (Ed 2), book, by Richard Schwartz and Martha Sweezy
* notes from it
** "The chattering mind denotes a nonunitary, relational mind."
** "looking at these personalities caused the entities to distinguish themselves"
   That immediately follows this:
   "Although these young women were disturbed to ricochet helplessly among contradictory personalities, "
** "Identifying parts caused my clients to find them less overwhelming and intimidating"
** "their descriptions reminded me of families."
   This immediately follows that:
   "Each inner voice was idiosyncratic in character, complete with temperament, desires, and a distinct way of communicating. Moreover, parts had alliances and polarities. We discovered that those who were vulnerable got locked away, or, as I came to speak of it, “exiled.” Others managed the client’s life, while yet others distracted from controversy and pain."
   ...
   "most parts we met did not trust the client to lead"
** "family therapy concepts such as homeostasis, triangulation, and scapegoating looked [relevant]"
** The pyschic parts said they would prefer to do helpful, positive things, but only could once doing so was safe.
** "When we try to have two people dialogue in a family, other family members often chime in, take sides, and escalate the conflict."
   "Sometimes we had to ask two or three voices not to interfere before the client could ..."
** The parts seem to have their own feelings.
   """
   I guided Cora to ask her pessimist why it kept insisting she was hopeless. It replied that it didn’t
   want her to take risks and get hurt. This answer seemed promising. If the pessimist really had a
   benign intent, maybe Cora could help it find a new role. But Cora was not interested. She was
   mad at the pessimist and told it (rudely) to leave her alone. When I asked why she was being
   rude, she went off on a long diatribe about the ill effects of this voice, which had erected major
   hurdles at every step of her life. As I listened, it dawned on me that we were actually hearing
   from another part, one who fought with the pessimist. In an earlier conversation, Cora had
   described an ongoing war between a voice who pushed her to achieve and another one who
   insisted she was hopeless. This seemed to be the pushing part.
   So I guided Cora to focus on the pushing, angry voice and to ask it to stop interfering—to “step
   back” in her mind. To my amazement, the part cooperated and Cora’s attitude suddenly shifted
   again. When I asked how she felt toward the pessimist now, a completely different person
   answered. In a calm, caring voice she said that she was grateful to it for trying to protect her, and
   sorry that it had felt so alone while working so hard.
   """
** "I asked my clients who was being so calm and compassionate inside [after having asked the agitated interferers to step back]. Their replies were something like the following: “That’s not a part like those other voices, that’swho I really am, that’s my self.”
** "Maybe our psychologies, philosophies, and religions had radically underestimated what we call human nature."
** "noticing parts in my body and asking them to step back instead of using a mantra. Amazingly it worked, and this is how I continue to meditate today"
** The Self does not need time to develop.
   """
   After watching scores of clients embody qualities of the Self with total spontaneity as
   soon as their parts separated, I finally embraced the idea that there is more to us than we usually
   let ourselves dream. And whatever this was (in calling it the Self, I was following my clients’ lead),
   it clearly did not need to develop over time. It was always right there if our parts let it in.
   """
** "Beyond being a peaceful state from which to witness and transcend the world, this mindful state of Self was also healing, creative, and performance enhancing."
** what parts needed
   """
   Parts like Cora’s pessimist struck
   me as inner trauma victims, stuck in the past and frozen at a time of great distress, often in
   childhood. They were activists, and they needed the client to understand their motivations. Otherparts mostly needed to be heard, held, comforted, and loved.
   Most amazing of all, once clients were in that Self-state, they seemed to know just what each
   inner personality needed.
   """
** homeostatic (bad) responses
   """
   Emboldened, I helped my clients separate from their parts, find the ones who were in pain, and
   love them up. The good news was that my clients felt better by the end of a session in which they
   had been able to embrace and comfort their childlike personalities. The bad news, to my dismay,
   was that they would return the next week having had horrible experiences shortly after leaving
   my office. One client had a car accident on the way home. Another spiked a fever of 103 degrees.
   Still another got the worst migraine of her life, which kept her in bed the whole week.
   """
** "I learned that in order to feel fully witnessed and understood, some parts need to take over in the body temporarily. Now whenever I see signs, even subtle signs, of a somatic takeover, I encourage clients to stay with or even exaggerate that experience. If some of their other parts feel self-conscious or frightened, we stop first to help them feel safe so they are willing to step back and let us proceed."
** "I have found that I can train other therapists to notice the signs of an embodied Self, and also to notice their absence. In this way I discovered that we could all become aware of activated parts as they manifest physically"
** "the language of parts helps because we do not have to say, I feel angry or afraid orimpatient. Instead, we can say, A minute ago a part of me felt ... "
   "the language of parts helps clients and therapists disclose strong feelings that might otherwise be embarrassing or controversial"
** I'd use the term "agentic parts" rather than "parts".
   At least from where I am now, 1/16th through the book.
** "• Protectors deserve to be understood, appreciated, and comforted before the client tries to approach vulnerable parts."
** protectors "are more knowledgeable than the therapist about the delicate ecology of the client’s inner system and the possible negative consequences of going too fast."
** "Extreme protectors usually will not change until the system is less vulnerable. Consequently, we do not pressure protectors to change, even ones who are involved in destructive symptoms. Instead, we suggest that they can be liberated from their protective roles if they allow the client’s Self to help, and we invite them to consider what role they would prefer after the exiled part no longer needs protection."
** "Restoring trust in the Self is the quickest route to improved leadership and inner harmony."
** "4. We invite clients to notice that parts have “blended” with the Self, or we help parts notice that the Self will be available when they separate or “step back.” ... By the same token, the IFS therapist continually scans inside herself for blended parts and asks them to separate so she can return to Self-leadership."
** "Protectors fear one another, which keeps them in extreme positions. Each part believes that relaxing will allow a polarized part to take over, with catastrophic consequences. Therefore in IFS we continually notice and attend to polarizations. Just like family therapists, we work with conflicted inner family members, inviting them to face each other and talk about how they can get along better. The difference is that, whenever possible, the client’s Self moderates these inner dialogues, aiming to ensure that parts are respectful and able to listen to each other."
** "IFS therapists are always asking about the network of internal relationships in which parts are embedded and the extreme beliefs parts may carry."
** goals
   """
   This relationship with the Self can bring a great measure of inner peace along
   with the ability to relate to life’s challenges and to other people with clarity, calm, confidence,
   courage, and compassion. Self-led individuals have the great pleasure of recapturing all the
   energy their protectors used to expend on inhibition, containment, distraction, and rebellion.
   They also gain access to the creativity, delight, and innocence of childlike parts who had been
   exiled so they are free to play again.
   """
** "People organize to maintain a range of homeostasis in any number of areas, from proximity to other people to levels of conflict with other people"
   "In addition, each person contains a multitude of cybernetic subsystems, from those that regulate blood sugar levels to those that regulate the expression of feelings."
** "A basic premise of IFS is that people have an innate drive toward and wisdom about their own health."
** Every part, every impulse, the text suggests, can be found a proper, helpful, harmonious role.
** "When we feel obliged to deny one truth in favor of another (e.g., I love you, I’m mad at you), we sign on to an unceasing project of denial and self-constraint. In contrast, accepting the mind’s ability to encompass many perspectives at once means that we can acknowledge the truth of two apparent opposites and move forward creatively"
** prior art for internal agentic parts
   """
   Other therapeutic approaches have also observed and worked with psychic multiplicity, calling
   parts variously subpersonalities, subselves, internal characters, archetypes, complexes, internal
   objects, ego states, and voices (Jung, 1969; Rowan, 1990; Stone & Stone, 1993; Watkins & Watkins,
   1997)
   """
** "When clients are uncomfortable with the word part—or, more likely, with the concept that we have parts—we can simply follow their word choice: aspect, thought, subpersonality, character, feeling, place, person, etc."
** "we encourage clients to label their parts"
   but "it is a mistake to assume that the part’s label or role (the sad part, the angry part, the captain, the caretaker, etc.) captures its essence. "
** what a part is
   "a part is not just an emotional state or a habitual thought pattern. Rather, parts are discrete, autonomous mental systems, each with their own idiosyncratic range of emotion, style of expression, abilities, desires, and views of the world"
   "same. When we view a part as a child or teenager who is shy or angry in a certain context, we are more likely to be curious about who it would be in other circumstances than we are to believe it is defined by this one attribute. "
** "Just as children get forced into extreme roles that they don’t want and for which they are ill-suited, parts get forced into extreme roles. "
* reading it (mechanics)
  ~/ifs.txt
** 8130 lines (exclding glossary, etc.)
** continue at line 665
   "Chapter 2, Individuals as Systems"
