:PROPERTIES:
:ID:       a04c2b66-35bd-45f6-8dfa-5513ffe36a9c
:ROAM_ALIASES: reprogram
:END:
#+title: introspect & reprogram
* TODO ? Would these notes be better in SmSn?
* objects
** TODO ? After exercise I want to meditate
   :PROPERTIES:
   :ID:       506d431f-c5ac-486a-a7e6-6dfa6c09d69b
   :END:
** [[id:24169b3e-6d41-48dd-9367-6df7a3565bed][my priorities]]
** [[id:776b4780-a8b8-42af-ba5a-b3703a2fc248][Creating can take courage.]]
** [[id:d63a84ca-2d5a-46c7-867d-02ff9ec8edaf][Trivial inconveniences can be good or bad.]]
** things I wish about myself
*** Don't get mad fast.
    Before yelling, state that someone is making me mad,
    and state what they are doing to do it.
*** When I see an ethical challenge, chew doggedly on it.
    I was trying to avoid sunburn,
    and ducked under the water, rather than push back
    against the two kids as they excitedly shared their plans
    of one day carrying firearms.
    I tried to think of a good response,
    but it did not come quickly,
    and once I was underwater I stopped trying.
** [[id:73e229ee-a416-41db-a23a-4d960b2e559f][systematic socializing]]
** on personal change
*** At 42 I acclimated physically (and behaviorally) to Villavo.
    The first and maybe the second time I was here, I was somewhat useless.
    The heat was opressive, and I got sick a lot.
    This time I have a fan on me most of the time,
    I'm working like normal or more,
    I can exercise,
    and while I got a stomach bug for a few days at the start,
    I've been fine for the four weeks since.
*** paraphrased: "Nobody comes back changed from an amazing vacation in Hawaii. It's suffering that does that."
**** -- David Brooks, on Tyler Cowen's podcast, circa 2019?
** Counting words depends on what I'm reading.
*** If I'm really into it, I don't.
*** I ?never do when reading my own notes.
