:PROPERTIES:
:ID:       c869b6f1-1ebe-419c-a3b8-afd6bcfdff97
:END:
#+title: It's probably not Covid?
[I posted this to Facebook, <2022-06-15 Wed>.]

It's probably not Covid? But the medical system isn't trying very hard to know.

I had a doctor come over today to evaluate me. I wanted a Covid test. No dice. Sandy explained that I didn't act sick enough. Those tests cost the government money, and they're expensive, and word has come down to be stingy about them.

I was into a weird little video game (https://vladimirslepnev.itch.io/zigzag) for a while a few months ago (attached), which provided a handy way for me to test the hypothesis that I was experiencing brain fog. I got my usual high score, 49 seconds, on the first shot, so that's good. Weak test but better than nothing, at least psychologically.

It only feels like an ordinary cold. But I've heard horror stories about people whose minor colds then led to long Covid, and I'd like to get upset about that, if appropriate, as early as possible.
