:PROPERTIES:
:ID:       2e99f9b7-5784-4e04-a277-9e6e734d1dd2
:END:
#+title: JACK (audio connection software)
* [[id:f3700976-96b6-4917-9aa5-83903c0c2de5][QJackCtl having no effect on `jack_bufsize`.]]
* TODO
** TODO (someone responded) : I asked online
*** TODO (someone responded) : on Reddit
    https://www.reddit.com/r/jackaudio/comments/uqex1x/pkgconfig_is_not_recognizing_jack_it_might_matter/
*** on the JACK Audio mailing list
    https://lists.linuxaudio.org/archives/jackaudio/2022-May/002404.html
** the Haskell JACK library on my computer
   /home/jeff/code/haskell/libs,tools/jack
** pkg-config seems not to recognize my JACK
   jeff@jbb-hp17:jack$ jackd --version
   jackdmp version 1.9.19 tmpdir /dev/shm protocol 9

   jeff@jbb-hp17:jack$ cabal repl
   Build profile: -w ghc-9.0.2 -O1
   In order, the following will be built (use -v for more details):
    - jack-0.7.2 (lib) (first run)
   Configuring library for jack-0.7.2..
   cabal: The pkg-config package 'jack' version >=0.118 && <1 || >=1.9.8 && <2 is
   required but it could not be found.
* [[id:fe42e9f1-0611-445b-8891-d3a7d603b921][MIDI via JACK in Python]]
* questions
** How to get the name of the JACK server?
   needed by Sound.JACK.newClient
* keeping JACK happy
** Killing SC before the GHCI process makes Jack err.
** don't leave Spotify open (even if not playing) when turning Qjackctl
   not sure but maybe bad
* leaving Qjackctl on seems to work
  I left it open, not running, for days and I can play the synth with it today.
