:PROPERTIES:
:ID:       4b331835-f66c-4ffa-8d05-97fc16497810
:END:
#+title: Kraken (cryptocurrency trading platform)
* coins of interest on Kraken
  :PROPERTIES:
  :ID:       3f468a87-63c8-4b78-90c2-fb4d4a86dbfb
  :END:
  BTC, BTC cash, Litecoin, Ether
    all trade on Buda.
  Could sell any of those on Kraken.
  In each case, sell in US.
** abbrevs
   ADA = ADA
   BCH = bitcoin cash
   ETH, XETH = ethereum
   SETH = short ethereum
   XBT = bitcoin
   LTC = litecoin
** pairs to track
   BCHETH
   BCHUSD
   BCHXBT
   XETHXXBT
   XETHZUSD
   XLTCXXBT
   XLTCZUSD
   LTCETH
   XXBTZUSD
** currency pairs I did not google
   SCXBT
     altname: SCXBT
   SNXAUD
     altname: SNXAUD
   SNXETH
     altname: SNXETH
   SNXEUR
     altname: SNXEUR
   SNXGBP
     altname: SNXGBP
   SNXUSD
     altname: SNXUSD
   SNXXBT
     altname: SNXXBT
   STORJETH
     altname: STORJETH
   STORJEUR
     altname: STORJEUR
   STORJUSD
     altname: STORJUSD
   STORJXBT
     altname: STORJXBT
   TBTCETH
     altname: TBTCETH
   TBTCEUR
     altname: TBTCEUR
   TBTCUSD
     altname: TBTCUSD
   TBTCXBT
     altname: TBTCXBT
   TRXETH
     altname: TRXETH
   TRXEUR
     altname: TRXEUR
   TRXUSD
     altname: TRXUSD
   TRXXBT
     altname: TRXXBT
   UNIETH
     altname: UNIETH
   UNIEUR
     altname: UNIEUR
   UNIUSD
     altname: UNIUSD
   UNIXBT
     altname: UNIXBT
   USDCAUD
     altname: USDCAUD
   USDCEUR
     altname: USDCEUR
   USDCGBP
     altname: USDCGBP
   USDCHF
     altname: USDCHF
   USDCUSD
     altname: USDCUSD
   USDCUSDT
     altname: USDCUSDT
   USDTAUD
     altname: USDTAUD
   USDTCAD
     altname: USDTCAD
   USDTCHF
     altname: USDTCHF
   USDTEUR
     altname: USDTEUR
   USDTGBP
     altname: USDTGBP
   USDTJPY
     altname: USDTJPY
   USDTZUSD
     altname: USDTUSD
   WAVESETH
     altname: WAVESETH
   WAVESEUR
     altname: WAVESEUR
   WAVESUSD
     altname: WAVESUSD
   WAVESXBT
     altname: WAVESXBT
   XBTAUD
     altname: XBTAUD
   XBTCHF
     altname: XBTCHF
   XBTDAI
     altname: XBTDAI
   XBTUSDC
     altname: XBTUSDC
   XBTUSDT
     altname: XBTUSDT
   XDGEUR
     altname: XDGEUR
   XDGUSD
     altname: XDGUSD
   XETCXETH
     altname: ETCETH
   XETCXXBT
     altname: ETCXBT
   XETCZEUR
     altname: ETCEUR
   XETCZUSD
     altname: ETCUSD
   XETHXXBT
     altname: ETHXBT
   XETHXXBT.d
     altname: ETHXBT.d
   XETHZCAD
     altname: ETHCAD
   XETHZCAD.d
     altname: ETHCAD.d
   XETHZEUR
     altname: ETHEUR
   XETHZEUR.d
     altname: ETHEUR.d
   XETHZGBP
     altname: ETHGBP
   XETHZGBP.d
     altname: ETHGBP.d
   XETHZJPY
     altname: ETHJPY
   XETHZJPY.d
     altname: ETHJPY.d
   XETHZUSD
     altname: ETHUSD
   XETHZUSD.d
     altname: ETHUSD.d
   XLTCXXBT
     altname: LTCXBT
   XLTCZEUR
     altname: LTCEUR
   XLTCZJPY
     altname: LTCJPY
   XLTCZUSD
     altname: LTCUSD
   XMLNXETH
     altname: MLNETH
   XMLNXXBT
     altname: MLNXBT
   XMLNZEUR
     altname: MLNEUR
   XMLNZUSD
     altname: MLNUSD
   XREPXETH
     altname: REPETH
   XREPXXBT
     altname: REPXBT
   XREPZEUR
     altname: REPEUR
   XREPZUSD
     altname: REPUSD
   XRPAUD
     altname: XRPAUD
   XRPETH
     altname: XRPETH
   XRPGBP
     altname: XRPGBP
   XRPUSDT
     altname: XRPUSDT
   XTZAUD
     altname: XTZAUD
   XTZETH
     altname: XTZETH
   XTZEUR
     altname: XTZEUR
   XTZGBP
     altname: XTZGBP
   XTZUSD
     altname: XTZUSD
   XTZXBT
     altname: XTZXBT
   XXBTZCAD
     altname: XBTCAD
   XXBTZCAD.d
     altname: XBTCAD.d
   XXBTZEUR
     altname: XBTEUR
   XXBTZEUR.d
     altname: XBTEUR.d
   XXBTZGBP
     altname: XBTGBP
   XXBTZGBP.d
     altname: XBTGBP.d
   XXBTZJPY
     altname: XBTJPY
   XXBTZJPY.d
     altname: XBTJPY.d
   XXBTZUSD
     altname: XBTUSD
   XXBTZUSD.d
     altname: XBTUSD.d
   XXDGXXBT
     altname: XDGXBT
   XXLMXXBT
     altname: XLMXBT
   XXLMZAUD
     altname: XLMAUD
   XXLMZEUR
     altname: XLMEUR
   XXLMZGBP
     altname: XLMGBP
   XXLMZUSD
     altname: XLMUSD
   XXMRXXBT
     altname: XMRXBT
   XXMRZEUR
     altname: XMREUR
   XXMRZUSD
     altname: XMRUSD
   XXRPXXBT
     altname: XRPXBT
   XXRPZCAD
     altname: XRPCAD
   XXRPZEUR
     altname: XRPEUR
   XXRPZJPY
     altname: XRPJPY
   XXRPZUSD
     altname: XRPUSD
   XZECXXBT
     altname: ZECXBT
   XZECZEUR
     altname: ZECEUR
   XZECZUSD
     altname: ZECUSD
   YFIAUD
     altname: YFIAUD
   YFIETH
     altname: YFIETH
   YFIEUR
     altname: YFIEUR
   YFIGBP
     altname: YFIGBP
   YFIUSD
     altname: YFIUSD
   YFIXBT
     altname: YFIXBT
   ZEURZUSD
     altname: EURUSD
   ZGBPZUSD
     altname: GBPUSD
   ZUSDZCAD
     altname: USDCAD
   ZUSDZJPY
     altname: USDJPY
** TODO why do some pairs also end in .d?
   see the file `kraken-pairs`.
* the Kraken API
** HTTP libraries to use
*** `requests` library is better than `urllib`, per someone
**** who says
     https://www.reddit.com/r/learnpython/comments/4io9f6/how_can_i_use_python_to_fetch_bitcoin_eur_price/d2zpqjx/?utm_source=reddit&utm_medium=web2x&context=3
*** `krakenex` library is broken
    This file from their examples won't run.
    https://github.com/veox/python3-krakenex/blob/master/examples/generate-trades-history-csv.py
** use the API key somehow
** put a "user agent string" in my header
   https://www.kraken.com/features/api
*** could this be the same as the API key?
