:PROPERTIES:
:ID:       e4a8cea1-c2ed-4948-87c1-a8a545a78fa5
:END:
#+title: lessons from getting banned from Microtonal Guitarist
= Facebook group moderated by Ron Sword
* in brief
** know who has power
*** mods have power
** remember my purpose, don't get sidetracked with arguments
** people offend and escalate silently and quickly
** social harm is invisible to both parties
* in detail
** Arguing online is not just wasteful, but dangerous.
*** remember the meme
    guru: "Arguing is never worth it."
    pupil: "I disagree."
    guru: "You are right".
** Remember your purpose in a group.
   It would help to remember my purpose in the group. If it is to debate, great. If it is to extract information about microtonal guitaristry, though, then advancing some other point that someone else disagrees with does not advance my own interests.
** Social injuries can be invisible to the injured.
** Social injuries online can be invisible to the aggressor.
** Some people will react in surprisingly negative ways to what I view as ordinary or even interesting discussion.
** Good-seeming people online can give very little warning before blocking someone who has made them uncomfortable.
   for both Ron and that trans metal girl,
   it was very little but nonzero
** Know who has power. Find who they are.
*** Recognize that the mods of groups have power.
