:PROPERTIES:
:ID:       52b1118f-05ee-42a7-b999-ebf2a378a4c1
:END:
#+title: letter to Shorenstein Center re. a Hode-like project
* similar projects of theirs
  Samesource
* email
** to
   Max Boland <maxboland@hks.harvard.edu>
** subject
   Looking for people building a social hypergraph database, or who would want to
** body
Dear Mr. Boland,

I'm writing to ask whether you or someone else in the lab might know about a project along the lines of what I've been working on, or barring that, people who would be interested in joining one.

I, like many, consider our recent epistemological crisis the most serious problem humanity faces. We can't agree on basic facts like, say, whether Biden or Trump directed more money at infrastructure. Evidence can be found for the most insane beliefs by anyone with a search engine and a flexible mind.

I believe a sufficiently expressive, queriable database could help. Currently it is relatively easy to find much of what a person has written. In social media it can also be easy to see what writings they have responded to. But for more complex queries -- e.g. "Show me things X has said about Y that contradict things said by people X cites" -- it's not feasible. But that's not because the technology doesn't exist; it's just a question of encoding the data and making it queriable.

Such a database would share some of the spirit of the Tech Lab's SameSource, which makes me hopeful. Are any of you trying to do something like that? Or do you know anyone who is? Would someone at Harvard want to hire someone like me to work on it? If I have to, I'll sign up again for a PhD somewhere, but I'm hoping for a quicker route.

Thank you for reading this,
Jeff
