:PROPERTIES:
:ID:       0b6321e4-d215-489c-8cd6-067baf9eb1ce
:END:
#+title: NAH - Make pasting modify the copy of the pasted text that's still in the kill ring.
way too hard
* PITFALL: Don't assume there's just one IDs involved.
  Multiple bullets may have been copied/pasted/etc.
* cases
** copy
   Easy. If copying, don't copy the IDs.
** paste
   If pasting, remove the IDs from the copy that remains in the kill-ring, if it had one.
   Don't assume the top kill-ring entry was pasted.
** kill
   No modification needed.
   Properties remain intact in the kill-ring.
** undo
*** of paste
    Restore the IDs of the copy in the kill-ring,
    if it ever had one.
*** of kill
    Strip the IDs from the copy in the kill-ring,
    if it had one.
*** representation
    Deletion in the undo stack
    is represented as `(BEG . END)`.
    Insertion is similar but with text too.
** query-replace
   copying once into the replace field would be cheating
** org-mode "tree cloning"
* if needed
** change the `id` property to `voided-id`
   This way if someone gets confused,
   they can find that property,
   and then find the bullet that's using that ID.
** for speed
   Maintain a map from IDs to kill-ring items.
   This would prevent ever having to look through the entire ring.
