:PROPERTIES:
:ID:       24eaa5b0-164b-4701-9518-74c4c46eb4b3
:END:
#+title: Mercatus Center, short essay on Shyg for
This brief essay includes hyperlinks to sections of [[id:c7f3da3a-4a8a-4e1a-b6ee-aebe11bc86d6][a more in-depth (5,000 words) project description]].
* Who am I
I am a programmer, data scientist and economist. I've worked for the Congressional Budget Office and a similar think tank in Colombia, among many others. For decades I have been an enthusiastic user of software for knowledge mapping, and have written and contributed to open source projects in that area.
* A mainstream belief I hold
Our chief institutions for determining what is true are science, journalism, law and government. It is critical that they function well, and that they be widely understood and trusted.
* What Shyg would be
Shyg ("Shared HyperGraph"), would be a federated index of content online, and some software for building it, querying it and displaying the results. Users would run Shyg in the background on their computers to create a map of what information can be found online where, and how it relates to other information. They would query it to find data.

Shyg will use a hypergraph database, which permits greater expressivity than traditional graph databases.
* why make Shyg
Shyg will be valuable even at small scales, so it will not need a huge advertising push like social media sites do. I will address its value at large scales first, because it is fantastic.
** Shyg at large scales
*** Search better.
Proprietary search engine providers keep most of their data a secret, and benefit if the user must see a few ads before finding their answer. Moreover, with no formal grammar, search engines simply guess the user's intention, limiting the potential complexity of a query. Shyg would overcome all of these problems.
*** Write your own social media feed.
Many users want a feed they control, ad-free and devoid of engagement-maximizing manipulations.

Programming your own social media feed in Shyg would be trivial. For instance the query, "Show me everything anyone on [list] has posted, ordered by recency, omitting anything about sports," would do it. Moreover a Shyg-powered social media feed could incorporate content from many sources -- traditional social media, blogs, news, quarterly shareholder reports, etc.

Programming your own social media feed in a system like Mastodon is already possible for programmers. But the query language Shyg will use, Hash -- [[https://github.com/JeffreyBenjaminBrown/hode/blob/master/docs/hash/the-hash-language.md][which already exists]], although I intend to extend it -- is simple enough for non-programmers to express detailed queries in.
*** Defend against misinformation.
Some of the fight against online misinformation involves tracing its origins. This is tedious manual labor, and need not be. Simple NLP could recognize citations even before LLMs. By including citation relationships in the index, and using the ontology to recognize equivalent forms of the same statement, a Shyg user could trace the history of a claim backward. A single query would suffice, whereas today one must make a separate query for each link from one domain to another (e.g. one query for the newspaper, another for a social media site the newspaper had quoted, then a new query when that site refers back to the newspaper ...)
*** Recognize bot networks.
Social media platforms, cybersecurity firms, academics, media watchdogs and others frequently try to identify bot networks, by analyzing timing and coordination, linguistics, interactions with users, and more.

Shyg will permit users to choose the kinds of information to index. Storing citation relationships, and relationships like "[author] claims that [different author] is human" will facilitate the recognition of bots, by providing a unified public database and query framework for the information.
*** Provide simplifying views of complex information.
Extracting the substantive information from discussions on social media can be made difficult by irrelevant noise, especially hostility. By indexing those discussions in Shyg, and viewing them through an appropriate query -- perhaps something like "filter out all ad-hominem statements, and for equivalent statements, show only one representative" -- an otherwise unwieldy and unpleasant river of feedback could be made helpful.
*** Improve how society determines truth.
Shyg will be agnostic about which community is correct on which issue. It will simply index their work -- but all of it in the same way, permitting queries that traverse them all at once. Every epistemic community will become more trasnparent. To the extent that communities of "alternate facts" arise from a sense of alienation from traditional instutitions, this integration should help.

But beyond that, argument within and between the communities will become more effective. Queries like "what kinds of evidence has been provided for [statement]", together with [[id:e185e848-ea55-4eec-9dba-d0cf9d893731][ontology-enabled uniqueness constraints]], will reveal otherwise hopelessly extensive fronts of argument to consist of a small number of ideas. And with fallacies and distractions easier to filter out, their effectiveness will fall, and with it the incentive to use them.
** Shyg at the scale of a single user
Shyg will permit users to traverse their data batter.

For instance, I have a note about traveling to a lower elevation as a strategy for temporarily enhancing one's immune system. I cannot search for "strategies for dealing with illnesses" and find it, because the note includes neither the word "illness" nor the word "strategy". Instead it includes "a way to fight infection". If it were indexed in Shyg, that search would work.

As another example, one could issue a query to "identify passages in the indexed documents that mention any chemical in the blood of any mammal". Shyg's [[id:0f4c43f7-2a52-4a2c-97b1-93a2cdf5e108][ontology]] will permit the user to sidestep the prohibitively tedious step of listing every chemical and every mammal.
** Shyg at the scale of a handful of people
A small group of non-programmers indexing their shared data in Shyg could process their data in ways not currently possible. One could, for example, "list everyone who was at [meeting] and has viewed [document]", or, "fetch every question addressed to me in any of the documents whose incompleteness is blocking anyone else".
* Path to sustainability
Shyg is sustainable if and when people find it sufficiently valuable to keep using it. If it gains widespread adoption, its usefulness to epistemic institutions (law, government, journalism, academia) will, I believe, guarantee funding for what little changes are needed. Getting to that point will require convincing people to try it at a small scale.

Pioneers in the aforementioned epistemic institutions will have reason to try it, because it will permit them to query their data in ways they currently cannot.

Productivity enthusiasts who already use knowledge mapping software like OneNote, Notion or Roam will have similar motivation. They already keep a body of hyperlinked notes, and Shyg will enable them to get more value from it.

AI developers are interested in graphlike representations of knowledge -- see, e.g., recent developments in GraphRAG. They want data for their models, in a structure that both those models and humans can understand. The hypergraph database underlying Shyg will be even more expressive than traditional graph databases. I therefore expect interest from this camp.

Last, many ordinary internet users are so dissatisfied with traditional search and social media that they seek out alternatives. Anyone concerned with open data, data sovereignty and decentralization is an ideal target user, as Shyg plays to all three interests -- it is massively open and decentralized, but also allows people to keep separate private indices.
* Budget requirements
A grant or a fellowship would both be helpful.

In a year working alone, I think I could make an offline prototype sufficient to attract other open-source contributors and/or funding from other organizations. Ideally, I would begin with funding for myself and two others: a web backend developer and a specialist in natural language processing, probably via AI. In that case I think we would still take a year to make something interesting, but it would be much more interesting.

I could live on $40,000/year in the US, or $30,000 in Latin America. I am a US citizen currently living in Colombia without residency. I could bounce around between Latin American countries for years. I'm hoping I could find two bright recent graduates willing to do the same. Legal employment in Colombia has an overhead of about 40% after taxes and social security contributions. So my ideal budget would be around 30k * 3 * 1.4 = 126,000 USD.

But any help would help. So far I have none.
