:PROPERTIES:
:ID:       9989f701-d223-4775-bcf6-337333063a40
:END:
#+title: microtonal harmony
* RESUME reading these notes [[id:86ec614c-4e4d-4ded-8e11-60caef7ad4c8][here]]
* about the intervals
** the three low-JI whole tones are roughly evenly spaced
*** the two lowest are 27c apart, the two highest 22c
> x = map (round . cents) $ [7/4,16/9,9/5]
> x
[9688,9961,10176]
> tail $ zipWith (-) x (undefined:x)
[273,215]
*** in both 41- and 46-edo they're consecutive
** 24-edo : [[id:1cfa5cfb-c951-4483-bb7a-9f87c908a026][quartertone-free, cluster-free ways to divide a fourth]]
* interval math
** in 41-edo, two vm6 = octave + ^m3
   :PROPERTIES:
   :ID:       6ab89e63-8ba0-4d16-8603-6bb58d7e30c0
   :END:
*** why that's weird
    two ordinary m6 = octave + vM3
      that is, a major 3rd rather than a minor one
*** that's the octave inverse of [[id:32205cdb-6e91-4e70-bba5-1336e119559c][this]]
** in 41-edo, two ^M3 = vM6
   :PROPERTIES:
   :ID:       32205cdb-6e91-4e70-bba5-1336e119559c
   :END:
*** why that's weird
    Two ordinary M3 = ^m6
      That is, a minor sixth rather than a major one.
*** that's the octave inverse of [[id:6ab89e63-8ba0-4d16-8603-6bb58d7e30c0][this]]
* chords
** in 31-edo
*** 0 18 5' 14'
*** 0 25 40
*** wide whole tone: 0 6 11 17 22 28
 subset: 0 11 17 28
*** 17_ 23_ 0 8 14
 This is symmetric -- -14 -8 0 8 14.
*** using 0 11 22 as an extension
 0 18 25+[0,11,22] = [0,18,25,5',16']
   In 12ET that would be a 7#11.
   Works with a 3rd of 7 (m3) or 10 (M3).
*** (0 18 25) + (7' + (0 8 18 28))
 The second chord is a min major 7th starting at 7,
 that is a short minor 3rd above the octave of the power-7 chord below.
 (where a power-7 chord is 0 18 25, i.e. it's got harmonics 3 and 7).
*** maj 7 under a min 7
 in 12et it would be:
   (0 7  11)  (3 7  10)'
 In 31et:
   (0 18 28)  (7 18 25)'
*** (0 11 18 5')
 creates a 25 relationship from 11 to 5'
** reasons to drop the 3:2
   :PROPERTIES:
   :ID:       4eb0545a-ac36-4a74-bd12-c429019e231a
   :END:
*** do that and the 10:9 sounds great.
*** root against a triad rooted somewhere else
    often sounds much more consonant than root + fifth against non-root triad.
*** Micro changes to the root are likely to sound better.
    Better than they would if the 3:2 moved in parallel with the root.
** "Dorian-French": 12edo: (-0.5) 9 3' 5'
   It's halfway between Dorian and French.
** 5/6, 1, 5/4, 11/8 : the (?) 11-limit min 6 chord.
** dom 7 vvb9 with no root, then dom 7
*** in JI
    dim 7 using 7/6 and 11/8 at 1/1, then just dom 7 at 4/3
*** in 41-edo
    24: 0  9 19 30
    0:  0 13 24 33
*** in 46-edo
    0: 0 10 21 37
    19: 0 15 27 37
** bond ^^root : deeply strange yet not grating
*** the idea
    like 12et (0 7 3' 9pythag' 2''), but pull the root and fifth up 50 cents
*** in 41-edo
    0 24 29 9' 5"
*** in 46-edo
    0 27 10' 33' 6''
** put three equal-spaced notes between 1/1 and 11/8
*** and keep going
    stack more such intervals above the 3/2,
    for something like a major 7th but denser
*** in 41-edo
      7 6  6  5  6  6  5
    0  7 13 19 24 30 36
** 9 11 13 = diminished
   A little wider than 5 6 7 = 10 12 14
   For both, the first interval is wider than the second.
** maybe special but not in 41-edo
*** 1, 7/4, 11/4, 11/4 * 6/5, 11/4 * 5/3
    :PROPERTIES:
    :ID:       86ec614c-4e4d-4ded-8e11-60caef7ad4c8
    :END:
    41-edo (I believe) equivalent:
      0 33 19' 30' 8"
*** (1/1: 1, 3/2) + (2*9/7: 1, 3/2, 16/9)
    That is, concurrently
**** In 46-edo
 (0: 0 27) + (17: 0 17 38)
* scales
** some ways to build scales
*** a stack of the same interval
*** multiple misaligned stacks
**** e.g. a stack of fifths built from the root, and another from the 13th harmonic
*** the harmonic series
*** modes
*** two nonoverlapping chords
** in 46 edo: 0 27 8' + (32: 0 10 27 37)
   = a stack of two fifths from 0 +
     a septimal min 7 from the 13th harmonic
   It has way more chords with a P5 than one might expect,
   and a 5-limit maj7 from 27.
** in 31-edo
*** too many notes: 0 2 6 10 14 18 20 24 27
 How to remember: it includes two stacks of four,
   one starting at 2, the other at 20.
 It's weird because it sounds like a familiar scale with an extra note
   between the root and fifth, and another between the fifth and the octave,
   but it's not clear which one is extra,
   because they're all pretty evenly spaced.
   (The intervals that aren't evenly spaced are from 0-2 and from 18-20,
   but for both pairs, the second clearly represents a distinct degree
   from the first, because 0 and 18 are such salient notes.)
*** 9 notes, evenly spaced and harmonic: 0 4 7 11 14 18 21 25 28
* changes
** 31-edo: two minor chords, descending 4/31 from one to the other
but holding the fifth degree (18/31) from the first,
and between them play the dominant (major starting at 18) chord of the first.
** 22-edo: start from septimal min maj 7, then raise 3rd and lower 7th by a microtone many times
   That is, start with 0 5 13 20
