:PROPERTIES:
:ID:       15b14255-32f5-4e44-bc38-0ee0353e07d2
:END:
#+title: moishoid vortex <2024-11-12 Tue>
At the concert today I wandered away from Diego, Monica, Alejandro and his sister for a bit to check out the ...  moshoid vortex? People were walking around in sort of pkayful aggressive circles, bumping into each other on purpose. They'd sort of swagger in a relaxed but muscular way during the relaxed parts of the song, and then they'd sort of trot during the faster parts.

I got halfway around the circle, got pucnhed from behind a little, and then decided to join the wall of crowd watching them again. The wall was a little reluctant to accept me. On that other side of the vortex this guy who looked for all the world like Jesus, with his shirt off, scraggly, wiry, with facial hair, I guess not like a 40-day beard or anything but that's not the point -- he stopped, still facing in the direction of the swirl, put his hands on his knees like an NFL player waiting for the whistle, and tried to stop the people behind him.

Which first of all, I wish NFL players blocked backward, with their asses.

But second I keep imagining not-Jesus was trying to stop the circle of reincarnation and give the people around him eternal life. And everyone just ignored him, because running in lightly violent circles is fun.
