* TODO Audacity damaged alsamixer
As soon as I installed and ran Audacity,
auto-mute stopped working for my headphones and builtin speaker.
* ET synth monome idea
** Some rows correspond to the harmonic series
1 is at the far left, then 2, 3, etc.
Pressing buttons on most harmonic series rows results in audible pitches.
** Each harmonic series extends below unity.
The 1/1 button can be shifted to the right,
revealing 1/2, 1/3, etc. to its left.
** The top harmonic series row, inaudible, can create shifts of the others.
For instance, press "1/2" on the top row, then (some modifier button)
to create a new bottom row next to the first, shifted an octave down.
** Shift-modifier-row commands
In each of these cases, one selects a shift amount from the top series,
then a modifier button, then a target row.
*** Shift current row
*** Insert copy of current row above or below
*** Shift current row and everything above or below
** Row configurations can be saved.
** Scales can be selected, saved.
Just highlight a bunch of notes and declare it a scale.
Instead of using the harmonic series, now rows can hold it instead.
** TODO ? Chords can be selected, saved, played.
Can this be unified (in feel) with the scale-selection mechanism?

* ET guitar fretboards, cheap
https://www.lmii.com/179-pre-slotted-pre-radiused-fingerboards?fbclid=IwAR3pjg9Y6USPEBdkohuvIPPRoRgGk1GVcjUanh4PeDn6yqawiOXNAe_nhdU
