:PROPERTIES:
:ID:       b8ca4165-8c30-40ab-9c18-b3930503f135
:END:
#+title: my aborted attempt at divorcing Sandy
From the start of our relationship -- three years as of the time I tried to end it -- I had thought we were intellectually incompatible. We would eat meals largely in silence if I didn't push to keep a conversation going. She's a devout evangelical Christian, I'm an atheist. I read the news, she watches action movies. I want to work all the time, she wants to travel. (I think travel's cool, but it's not a high priority.) The lack of conversational topics seemed to indicate a tragic mismatch to me.

But we think we can work on that. Indeed we've been a lot more talkative since the breakup.

And good god I cannot live without her. Within 36 hours I was an emotional wreck. I was afraid she would take revenge, break my stuff or something. Instead she prayed -- along the lines of, "I can't do anything about this, God, so I'll just leave it up to you," -- and suffered, and tried to get on with her life. I'm tearing up now writing the story.

I called her, bawling, practically unable to speak, before 48 hours had passed, and asked to come back. She wasn't angry, didn't try to extract any concessions, just asked me to calm down and asked if I wanted her to come over. I did. I packed up. We left the hotel 2 days into the 7 I had purchased. I'll go back tomorrow to get the yogurt I left.

People talk about being married to angels a lot. Maybe marriage brings out angelicism in a lot of people. I don't know. But I really feel that way. I didn't understand how much I loved her, and now I love her way more.
