:PROPERTIES:
:ID:       04b961f6-ed58-4bbb-b50b-d06eb542fc38
:END:
#+title: my first impressiosns of Thrill of the Fight on the Oculus Quest 2
2022 04 26 (the day after my first use)

I bought a VR headset* to do virtual boxing for cardio, after a WaPo article said it really works. I can confirm. It really works.

It's not comfortable, because my head is bigger than their maximum expected head. The setup process is involved. Often the headset got lost and would go blank until it could reorient. (Maybe it'll do better on a full charge, or with software updates.)

Despite all that I am overjoyed with this thing.

I immediately bought Thrill of the Fight ($10, not a subscription) and played it. I haven't sweated like that since the last time Sandy and I climbed a mountain. I was so tired by the end (30 minutes, tops) that I could barely hold my hands in front of my face like boxers do. I didn't dance like boxers do. I don't know why they do that. I intend to read about how boxing works.

For some reason -- maybe the brevity of the workout? -- I'm not uselessly dead today, like I usually am the day after really intense cardio.

I'm excited. I've lifted weights but never had a particularly regular cardio habit, and I've always thought the reverse would be better. Too sore (neck and shoulders from throwing punches, traps and biceps from decelerating them because you're punching the air, lower back from ducking to the sides) to play it again tonight, but tomorrow for sure.

 * I got the Oculus Quest 2, because it costs $300 whereas a comparable headset would be like $1000 more. Now Facebook knows how I move my head and hands. There is a dystopian future where that matters -- namely, the one in which I try to escape the system by replacing my entire social network and my face -- but I don't think it's likely.
