:PROPERTIES:
:ID:       339f3f3a-49c2-4dfd-a66c-de482ccec92a
:END:
#+title: my introductory microtonal music recommendations
Sevish makes danceable electronica, largely in 22-edo; Gleam from Harmony Hacker might be my favorite track of his.
Brendan Byrnes, a guitarist-singer-songwriter in LA, makes rock, mostly 22- but lately also 27-edo.
Tarek Yamani makes Arabic-flavored progressive (i.e. lots of drums) piano jazz in 24-edo, at least on one of his albums (I think it's Peninsular).
Tolgahan Cogulu is a wonderful Turkish guitarist who uses a *crazy* guitar with frets that aren't even straight lines.
Cryptic Tree is work by two metal bands (Cryptic Ruse and Mercury Tree) that's disturbing if you pay attention to the lyrics but full of beautiful sounds.
Easley Blackwood wrote my favorite album of classical microtonal music, so far only rendered electronically; I always find it by googling Blackwood Microtonal.
James Mulvale, a Canadian guy who makes TV and video game music for his day job, makes some fantastic microtonal music. Much of it is pop. My favorite is impressionistic piano: https://soundcloud.com/jamesmulvale/sets/impressions
