:PROPERTIES:
:ID:       cc06cc2e-b6a7-4110-98d7-0adf9a75b170
:END:
#+title: my work at the Observatorio: informal, for the new boss
I was hired as Chief Technical Officer, or Chief Technology Officer, I can never remember. Javeriana calls me a professor, but so far I don't teach. (Andres has offered classes but I don't really want to do that.)

My biggest job has been to write the microsimulation and put it online. It costs us $3 USD / day to run, and is currently online; you can find it here:

http://www.ofiscal-puj.org/microsim/run_make/manual_ingest

Currently the sim models the IVA, the personal income tax, the social security taxes, and a few smallish taxes like the predial, a special tax on big motorcycles, etc. (Actually it just reports the predial, which is reported directly in the ENPH.) The microsimulation uses the ENPH -- Encuesta Nacional de Presupuestos de Hogares -- for data about people. It uses a data set built by the Observatorio -- first David Suarez, then Juan Manrique, and most recently Daniel Duque and Valentina Herrera -- assigning tax rates and categories (e.g. "pink", "unhealthy", "environmentally damaging") to goods. Very soon it will also crudely model the corporate income tax, by assigning it proportionally to people according to their dividend income.

The website lets people assign their own IVA and income tax rates. In the next few months I hope to get to where someone can also specify social security tax rates.

The second biggest job I did was to automatically generate finance reports for every (about 1100) municipality in Colombia, showing where they get their money from, what they spend it on, and how they compare to their department average and to what had prevailed under the previous administration. Here's a list of those:

https://github.com/ofiscal/cities-output/tree/master/reportes

I try, with varying success, to keep all my work online and public. Here's the Observatorio's Github repo:

https://github.com/ofiscal

I'm the only one with access to it, I think. Were I to die and fail to give someone else access, though, it could simply be forked, since it's public.

In our first few years I spent a lot of time handling requests from people in Congress. The online system is supposed to take that load off of me. It won't, but it might help. To a first approximation, the online model only allows users to change numbers. In particular they can't define new taxes. I have to fork the model to do that.

I help with random technology-related stuff when needed. I use Linuxm so when people have a Windows-specific problem I'm often no help, but for other problems I can be. I figured out some of how to use Wix -- a platform we came to dislike but are now married to -- although I don't remember any of that any more. I set up a mailing list which ran for a while, but I don't think it does any more. I was going to help Juan Oviedo understand how to generate "diffs" to compare two text documents, but then decided to see if our volunteer Sebastian could do it. Oliver, have you met Sebastian?

LC expected me to be leading other programmers within a year of onboarding me. That's still not happening, and I imagine budget won't allow it for a long time yet. But it would be nice. I'm currently a mix of system administrator and software engineer. I can't say there's quite enough sysadmin work to warrant hiring someone who specializes in that, but it's certainly a big component of my work. We run the microsimulation on AWS. The machines I'm in the same room with sometimes run NixOS, a flavor of Linux. On both kinds of systems I'm usually using Docker, which creates virtual environments, allowing me to ensure that two systems are identical even though their hardware and host operating systems are different.

A lot of the tricks I use are unfortunately only in my head, but I've also collected an extensive body of notes on how things work, and they are public. Observatorio-specific topics are here:

https://github.com/ofiscal/knowledge-graph

The rest of my public notes include a lot of information on programming and system administration, and can be found here:

https://github.com/JeffreyBenjaminBrown/notes-in-org-format-on-tech

(That repo is called "notes on tech" but it evolved to include everything I make public except Observatorio stuff.) Those notes are easier to read with org-roam, but they're plain text.

There's also a body of early notes taken in Semantic Synchrony, which are public but Semantic Synchrony is so hard to run that I'm afraid they're effectively private -- nobody but me and Joshua Shinavier (a friend who works for LinkedIn) are ever going to know how to read them:

https://github.com/JeffreyBenjaminBrown/observatorio-fiscal-smsn

Fortunately they're probably mostly stale.

There's an incomplete paper with Luis Carlos's and my names on it on Overleaf describing the microsimulation:

https://www.overleaf.com/project/5e595b989b19b0000110cfbe

That documentation suffers from the dreaded Single Source of Truth problem: the model evolves, and passages in the paper grow stale. The model is full of README files, which suffer the same problem but less so. So far Daniel has managed to run the model successfully on his own machine. Sebastian tried but couldn't. Nobody knows how it all works, not even me -- before I modify a part of it that I haven't looked at for a while, I have to first study how that part works.
