:PROPERTIES:
:ID:       201e303a-dcc0-4e88-acd1-9329182af5a3
:END:
#+title: neck exercises
* ref
  https://powerliftingtechnique.com/how-to-get-thicker-neck
* general tips
** Rest 2 or 3 days between neck workouts.
** Don't use too much weight,
   especially if doing a neck exercise that isn't the standard shrug
   (reverse shrugs are not standard).
* the exercises
** for the neck traps : barbell or dumbell shrug
*** how
    Lift up and back, squeeze.
    Guy in video likes to hold for 5 seconds.
    Seomeone else said 3.
    Lighter weight + more reps = greater range of motion, more mass.
*** variations
    dumbell
    behind the back
** for the sternocleidal mastoids : SCM crunches
*** general tips
    Lie flat.
    Should shorten the SCM at both ends.
    Do not "embrace the double chin like in other exercises".
*** alternatives
**** chin to sky
     Try to raise the chin as high as possible.
**** rotated lifts
     Rotate head to either side as far as is comfortable.
     Lift head off the floor as high as possible.
