:PROPERTIES:
:ID:       52b7a722-8591-4f9b-a290-cccd1639e565
:END:
#+title: NixOS packages: create, build, install, publish
* refs
** u
   https://nixos.wiki/wiki/Nixpkgs/Create_and_debug_packages
   https://nixos.org/nixos/manual/index.html#sec-custom-packages
** NixOS manual / quick start to adding a package
   https://nixos.org/manual/nixpkgs/stable/#chap-quick-start
** NixOS manual / writing modules
   https://nixos.org/manual/nixos/stable/index.html#sec-writing-modules
* PITFALL: My nixpkgs branch should match my nixos channel.
  The latest master branch of nixpkgs, I think,
  corresponds at least roughly to nixos-unstable.
  nixos-stable corresponds to, IIRC,
  the latest release tag of nixpkgs.
* how to do it
** PITFALL: These notes overlap
   and most were written while ignorant.
** [[id:0398d7c0-5ec1-4fe7-9303-74c0c6308643][writing and using Nix expressions]]
** to build
   serial
*** 1 - write the package
**** after manually downloading the source for it
     In a clone of nixpkgs:
       Put the package somewhere in pkgs/.
	 Model it after nix pill 8 section 2, at
	 /home/jeff/nix/pills/08/2-generic/
	 NOTE: Requires manually downloading the source code.
**** with automatic downloading of the source
  rather than define src = the name of some file that I put there myself,
  define
    src = fetchurl {
      url = ...;
      sha256 = ...;
    };
  To compute sha256, download from the desired URL (but only once)
  and run sha256sum on it.
*** 2 - add an appropriate line to pkgs/top-level/all-packages.nix
    e.g. hello-test = callPackage ../development/libraries/hello-test { };
*** 3 - commands to build it
    :PROPERTIES:
    :ID:       c15685f2-54d8-40dd-a49c-d87ec0bd5034
    :END:
    At the root of nixpkgs, test whether it builds with
      nix-build -A <package-name>
    To add it to my user profile, run
      nix-env -f . -iA <package-name>
** using nix-fetch-git with subumodules
   nix-prefetch-git --fetch-submodules https://github.com/monome/serialosc
** nixos-rebuild with a nixpkgs fork
   nixos-rebuild switch -I nixpkgs=/home/jeff/nix/nixpkgs
   /home/jeff/nix/nixpkgs/pkgs/development/libraries/hello-test
* BLOCKED : response pending, my waf issue
** TODO With an answer, awaiting response
https://stackoverflow.com/questions/59805975/nix-building-waf-produces-a-file-but-i-seem-to-need-a-folder/59809635#59809635
** with only a comment
https://stackoverflow.com/questions/59806776/nix-write-a-package-that-uses-waf-instead-of-make?noredirect=1#comment105758423_59806776
