:PROPERTIES:
:ID:       41844d8a-f352-4e2d-8ba3-3c83b2dd2ac3
:ROAM_ALIASES: "osc-gen" "osc gen"
:END:
#+title: oscillable generations view for org-roam
* refs
** systems ,, favorite | relevant
*** [[id:572d6341-4aa9-4d8e-9a28-11d8fc527f25][Emacs programming for knowledge graphs]]
*** [[id:46d56f38-e6a8-43aa-8c74-efccddfb0770][TypeDB]]
*** [[id:63f366e6-b768-4f3f-9093-a776f2b4e069][org-roam]]
*** [[id:55dae027-0053-4557-ba7e-2a36ef679cb4][smsn]]
*** [[id:d5a5a3ff-977a-405b-8660-264fb4e974a3][Hode]]
** projects, adjacent
*** [[id:3da96e05-1bfc-4034-8be6-ff9ed4534bca][make git commits of org-roam data easier]]
** [[id:1f76cbed-d2c5-4522-89e2-1de946d5dc99][knowledge graphs, some connectivity demos for]]
** functions of latest interest
   get-the-in-file-ancestor-path ()
   disguise-org-headline ()
   org-roam-db-query (query &rest args)
   insert-graph-parents-as-subheadlines ()
* rebuild the ddatabase in TypeDB
  The DB does not have to understand everything about the file.
* [[id:66df35f1-5cd7-4c3f-bfc8-26ea873b1fc2][shuffle branch list]]
* Are wishes interesting?
  I have a lot of wishes in a few files:

oscillable_generations_view_for_org_roam.org
shareable_knowledge_gardens.org
hode.org
* [[id:2dfb86be-9eb5-4262-a9b7-a48fa0f9ac58][merging in a knowledge graph]]
* Sort by product of accumulated unsorted notes and last time sorted.
* to get a sense of the mass of a content tree
  out-links in contents
  number of contents
* Contribute to org-roam.
** preserve frames when following link
   Splitting a buffer and then following a link should let you visit only from that view, not both.
* Can group the ancestries and the in-this-path to a node under a "contexts" view-branch.
* Indicate an intermediate heading is optional.
  That it describes the relationship,
  and does not stand on its own.
  (In most cases I expect the latter to be,
  more specifically, that the elements are more interesting
  than (except perhaps the first time)
  the relationship label without members.)
* TODO first MEP: [[id:7d610433-1fb7-4a84-8903-1a7f9212a4a7][backlinks in forward-view]]
* remember
** This is so feasible!
** List future features to verify extensibility.
   Before implementing a feature F,
   verify that for every future feature G,
   the path from F to G is clear.
** Don't implement [[id:217a4c60-458b-4a06-8627-6eeb2bc1771e][save-terminality]].
** Cut myself some slack.
*** It's okay to release it with unused info.
    For instance the screen could include info about how to reconstruct it even though it doesn't permit saving.
* problems
** [[id:c48a9e5c-24c4-430e-9f75-ae8848387f71][glyphs could be redundant to properties]]
** [[id:58ffe371-fdf8-427f-a462-4f674315b9b5][osc-gen: conflicts from external edits]]
** language choice
*** AI might be even better at Haskell.
    It's quieter, easier to reason about.
*** Use Python to get help.
    I can keep others' submissions functional.
*** Use Rust for extensibiilty to TypeDB.
**** query the org-roam db with Rust
     so that it becomes extensible to TypeDB
**** DONE talk to a Rust server from Emacs
     ~/hodal/serve-rust-to-emacs
*** NOPE Generate Python with Haskell.
    Nothing good comes up fast
    on Hackage, Google or ChatGPT.
** Separate the model from the controller.
   Keep as much logic out of Emacs as possible.
** architectural choices
*** Use a JSON server to query the org-roam db.
* primitives
** path to host file
** link set
   :PROPERTIES:
   :ID:       15bcbd93-f639-4c41-a123-593209f861bd
   :END:
   = links in heading, body, descendents
   or any subset thereof
** link relationship
** content relationship
** [[id:29673a41-5ac5-4058-af3a-0868ff7b2573][glyphs]]
** vocab, not entirely obsolete
*** (graph-)leafward, (graph-)rootward
    seems preferable, given org-roam context, to these alternatives
**** leafward = from titles to headlines, headlines to subheadlines
**** alternatives
***** contents, containers
***** children, parents
***** forward, backward
*** screen-leafward, screen-rootward
*** leafward in-file path (LIFP)
    is the path from a title to a node,
    if that node is in that file.
* features, immediate
** [[id:162be6d0-208c-4eec-9886-aa0f368fdda2][backlinks in forward-view]]
** native ancestry in forward-view
   Very similar to [[id:7d610433-1fb7-4a84-8903-1a7f9212a4a7][backlinks in forward-view]].
   The only difference is that
   those are paths in other files,
   whereas this is in the current file.
** hide ordinary file-content from view
*** Indicate that it was hidden
    either with a glyph in its parent,
    or with a single branch that replaces
    the many that were hidden.
*** Obviates a harder feature: [[id:217a4c60-458b-4a06-8627-6eeb2bc1771e][save-terminality]]
** [[id:e6e855d9-f2e8-456e-87d7-e82379ead9f1][show cotargeters, coancestors]]
** [[id:f2e39601-d7a2-46e1-b18f-a1287aa94262][Make duplication in a buffer visibly obvious.]]
** [[id:09302ec4-f993-4b1c-bc1e-633f47274c7a][content context switching]]
** ancestry context switching
   :PROPERTIES:
   :ID:       d7ba0584-6df0-4c75-96c8-5758b9934e35
   :END:
*** what it would look like
    * grandchild
      * } child ;; "}" indicates reverse containment
        * }I parent ;; I indicates has ID but is not file.
          * } more of the ancestry
            * }F The "F"ile containing them.
              ;; Here begins the "recursion".
              ;; Give this the ID "f1".
              * R references to it ;; R indicates this is an intermediating relationship heading, not itself a heading in any .org file.
                * a heading with a [link to F1]
                  * } bla ...
                    * }F a file
                * another heading with a [link to F1]
                  * } bla ...
                    * }F another file
** prevent [[id:5a749f75-cfab-4a80-9413-bd877e18f6bd][conflicts from external edits]]
** save views
   That is, don't just save to each file in the view,
   but save the view itself.
   Try to make the view robust to changes
   in the files it views.
** indicate repo in link
* features, later
** toggle ancestry between full and only nodes with IDs
   When the ancestry is "collapsed",
   any hidden (that is, without IDs) headings
   are represented as an ellipsis prefix
   in the first displayed node that file-contains them.
** Make a new PROPERTY, "comments on".
*** definition
    If N comments on M, then Ms content displays
    an addition "comments from [author]" branch.
** Make a new PROPERTY, "overrides".
   See skg. This seems hard.
** Links to foreign headings with no ID.
*** Awkward but doable.
*** how
    Link should include the repo, commit, file, line number, and (ordinary) label. Would be a new link format.
    If the commit is old, that should be announced visibly, and user can follow to old or new.
    If new has a heading with the same text, jump to it. If not, can search the text of new by similarity (in the embedding sense) to the now-disappeared heading.
** Show [[id:15bcbd93-f639-4c41-a123-593209f861bd][link set]] nieghbors.
*** = Show nodes containing subsets of or overlapping the link set.
*** Maybe don't show all overlapping sets.
    Start from subsets of size n-1,
    maybe then show n-2,
    but stop before reaching 1.
** [[id:8f3c4737-c315-40b3-935e-b8f205cb7601][enable sharing]]
** [[id:562876f3-9608-4ebe-9ab1-f119188ffa32][Define relationships using ordinary org-roam syntax.]]
** view traversal history
   Integrate with Git?
** [[id:9b247ad4-a606-4bd4-a5a6-df297d91e262][Each node could [order, structure] its parents.]]
** Introduce Hash into how nodes are tabled.
   e.g. if a title was "a & b", they would be associated with a
   relationship, undefined but someone can write about it
   (giving the relationship the title "_ & _").
   Upon exploration you could see generic things that apply to your accreted definitions of &, as well as to specifically "a & b".
** [[id:54cd30f3-b696-4017-a02e-4e5b17ab1553][a format friendlier for reading diffs than org-roam's]]
** attach disambiguating arrows to pronouns
   "it" could have an up-left arrow,
   "these" could have a down-right arrow,
   etc.
* [[id:eb54aa0e-a503-44f8-a8a5-8e0ab30e6994][rename it]]
