:PROPERTIES:
:ID:       69f10222-f0ed-43a8-867a-81a7ff23022d
:END:
#+title: Otherlands (book) by Thomas Halliday
* 20k to 10 million years ago, IIRC
  These are the notes from at least two different chapters.
** 3 million years ago, Italy had places that reached 80 degrees Celsius.
** Some geologic event filled the Mediterranean with the ocean. When it happened, there was briefly a salt waterfall 1.5 km high.
** Only 20k years ago (IIRC), as the ice age ended, there were bears 4 meters high, and mastodons.
** Animals on islands tend toward a middle size. There aren't enough resources to be huge, and being small makes it hard to store fat, which is necessary because there are for some reason periods of scarcity.
** Antlers -- defined by being shed and regrown every year -- require enormous amounts of calcium. Male deer like to position themselves where baby chicks have to cross to get to whatever, so they can eat them.
* 32 million years ago
** Grass on the world is a recent development.
** Plants developed a more efficient way to photosynthesize -- C4 photosynthesis? -- around 3 (10?) million years ago, and animals had to adapt (how?).
** The Andes are only 1000 meters high.
