:PROPERTIES:
:ID:       69f10222-f0ed-43a8-867a-81a7ff23022d
:END:
#+title: Otherlands (book) by Thomas Halliday
* 20k to 10 million years ago, IIRC
  These are the notes from at least two different chapters.
** 3 million years ago, Italy had places that reached 80 degrees Celsius.
** Some geologic event filled the Mediterranean with the ocean. When it happened, there was briefly a salt waterfall 1.5 km high.
** Only 20k years ago (IIRC), as the ice age ended, there were bears 4 meters high, and mastodons.
** Animals on islands tend toward a middle size. There aren't enough resources to be huge, and being small makes it hard to store fat, which is necessary because there are for some reason periods of scarcity.
** Antlers -- defined by being shed and regrown every year -- require enormous amounts of calcium. Male deer like to position themselves where baby chicks have to cross to get to whatever, so they can eat them.
* 32 million years ago, Chile
** South America was an island continent.
** Grass on the world is a recent development.
** Plants developed a more efficient way to photosynthesize -- C4 photosynthesis? -- around 3 (10?) million years ago, and animals had to adapt (how?).
** The Andes are only 1000 meters high.
** Grasses tend to populate places with middling rainfall and evaporation.
   Too little water => desert, scrub. Too much => there's enough water for trees too. But in the middle, the grasses can exploit the water first.
** Sloths used to be very diverse (in South America then), and most of them on the ground. Their curved claws are good for hanging or gripping without expending energy.
** "Island rafts" took animals, notably monkeys, from Africa to South America.
   They are chunks of dirt full of roots, held together, sometimes sporting multiple trees.
*** TODO Why do they separate from the continent and launch into the ocean?
* 66 billion years ago, Appalachia (island?) and Florida
** just after the meteor that killed 3/4 of all species
** Species with many "cheap" offspring have an advantage in highly variable, unpredictable environments
** Kangaroo rats only 50 cm from the surface of the earth could survive atomic tests in Nevada in the 60s
*** TODO How far from the blast center?
* u (from phone)
** 225 m years ago, tanystropheids were "walking fishing rods", 6 m long in total with next up to 3 m long. This let them surprise fish by keeping their heads far away from their bodies which were giveaways.
*** They did that while swimming. But they could also walk around on land
** Shipworms developed in the Cretaceous. Before that, a floating log in the ocean could last 20 years. Particularly because animals and plants would attach that somehow sealed it.
** A sponge would survive being put in a blender. It would just come out a different shape.
*** The cytoplasm that is in other map animals only within cells floats between cells in a sponge, making them blur the line between colony and single-celled organism. Also, somehow, it allows them to send electrical signals throughout the body, took coordinate operations even without having a nervous system as such.
*** And most sponges, though not glass sponges, can shut off their plumbing when the water gets silty, to avoid becoming clogged.
** At some important site in china, it was a lake at the bottom of a crater. It was fertile because of a nearby volcano, or maybe it's the volcano that the crater is in, providing minerals and the climate was the right temperature, I guess temper it all year round? And then there was some kind of eruption, and poisonous gases settled into the crater, suffocating everything including animals in the lake. And then Ash settled on top, preserving them in silt. Hair, feather, and even the melanosomes ( chemical structures that dictate color ) were preserved.
** Rotting plant matter piled over eggs keeps them warm. That is, the rotting activity itself generates heat.
** Jeans, comparable to muscles, appear to go bad if disused for long enough. While there were dinosaurs, mammals exploited the fact that they could operate at night, and needed to collect as much light as possible but did not need to distinguish color. As a result we were for a while merely dichromatic, being able to detect red and blue, whereas the things we had come from were quadrichromatic. Birds and lizards still are. We eventually duplicated and modified the red detector to get a green detector, so now most of us are trichromatic.
** Unlike lizards, mammals can be active at night, because they don't need sunlight to be warm.
** Trash bugs collect whatever is on the forest floor as camouflage when young
** Animals use coloration not just a single danger, but also to signal that they taste bad
** The meteor destroyed 3/4 of all plant and animal species. After a million years, biodiversity had recovered to the point before the impact
