:PROPERTIES:
:ID:       4caa77ca-9934-413c-a0e3-d98af96a837d
:END:
#+title: Outlive (book) by Peter Attia
* [[id:e2f424e1-f27a-45c2-8d41-cbe212b164dd]["In the late 1970s, the average American adult male weighed 173 pounds. Now ... [it's] nearly 200[.]"]]
* sugar metabolism
** tests Attia rec's
*** DEXA: to know about fat
    Even in a lean person, visceral (between-organ)
    fat can be high and dangerous.
*** "I test my patients’ levels of uric acid"
**** because high levels may promote fat storage.
**** because it is linked to high blood pressure.
*** "I monitor several biomarkers related to metabolism ...
    elevated insulin
    elevated uric acid
    elevated homocysteine,
    chronic inflammation
    even mildly elevated ALT liver enzymes
    the ratio of triglycerides to HDL cholesterol (it should be less than 2:1 or better yet, less than 1:1)
    levels of VLDL, a lipoprotein that carries triglycerides
** insulin
   is a signal to remove excess glucose from the blood
   and put it into cells as fat,
   and also impairs the release of fat-stored energy.
** [[id:dcf53cef-1bb8-4fe0-a995-02fcabc137d2][Diabetes grew by almost two orders of magnitude in 82 years.]]
** [[id:17d80aa8-0cbf-4d6d-b923-ec9e19257231][Among animals, fructose is uniquely bad for humans.]]
** The uric acid we produce from fructose (causes?) our body to store lots of fat, and has (other) harmful effects.
** Liquid fructose -- even healthy smoothies -- can overwhelm the gut.
   "[T]he excess is shunted to the liver, where many of those calories are likely to end up as fat."
* heart, veins and cholesterol
** cholesterol
*** in food, doesn't matter
    """
    “There’s no connection whatsoever between cholesterol in food and cholesterol in blood,” [Ancel] Keys said in a 1997 interview.
    """
*** Is a lipid (a fat)
*** Cholesterol is used by the body to build many things
** HDL cholesterol is carried by apoA particles, which can cross the endothelium in both directions easily. LDL is carried by apoB, which tends to get stuck in the arterial wall. That's bad, because they get oxidized there, which makes them toxic. This causes atherosclerosis. The oxidation causes them to clump together and stick around.
** High blood pressure damages the endothelium.
** Macrophages (immune cells, "big eaters") come to help, eating the LDL. If they eat too much they "blow up into a foam cell"; enough of them that do that will leave a fatty streak visible without a microscope.
** "cholesterol efflux" : HDL can suck lipid out of a foam cell, cross back into the vein, and deliver the cholesterol to where it's useful.
** HDL seems to do other good stuff against atherosclerosis.
   "maintain the integrity of the endothelium, lowering inflammation, and neutralizing or stopping the oxidation of LDL, like a kind of arterial antioxidant."
** LDL-C is a useful marker for risk, but HDL-C is not so useful for good.
** Foam cells become the core of atherosclerotic plaque. Smooth muscle cells from the artery go there to secrete a fibrous matrix to contain the foam, like a scar.
** on tests
   "a CT angiogram, which I much prefer to a garden-variety calcium scan[*4] because it can also identify the noncalcified or “soft” plaque that precedes calcification.)"
** stenosis = narrowing of the arterial wall due to plaque
   First, plaque goes outward, but later it goes inward, blocking traffic.
** Plaque is only visible on a regular CT scan when it becomes calcified. Calcium goes there to stabilize it -- "like pouring concrete on the Chernobyl reactor"
** Noncalcified plaques are more dangerous, because they can clot, blocking passage or breaking free and causing heart attack or stroke.
** An apoB test is more useful (and rare) than an LDL-C test.
   "(Don’t be waved off by nonsensical arguments about “cost”: It’s about twenty to thirty dollars.)"
** High Lp(a) ("l p little a") is very bad, and easily tested.
   It's a weird lipoprotein with tennis rackets sticking out that collect bad stuff and get stuck in the endothelium.
   It only needs testing *once*, because it's genetic.
** "I think you can’t lower apoB and LDL-C too much, provided there are no side effects from treatment."
   "Many doctors, and in fact many of you reading this, might be shocked to see such a low LDL-C target: 10 to 20 mg/dL?"
   but there are "scores of studies showing no ill effects from extremely low LDL concentrations."
** "[W]hile having very low HDL-C is associated with higher risk, it does not appear to be causal. This is why drugs aimed at raising HDL-C have generally failed to reduce risk and events in clinical trials."
** Keto is chancey.
   "In my clinical experience, about a third to half of people who consume high amounts of saturated fats (which sometimes goes hand in hand with a ketogenic diet) will experience a dramatic increase in apoB particles" which is bad.
** cholesterol drugs
*** what they all do
    serial
**** "are typically thought of as “cholesterol-lowering” medications, but I think we are better served to think about them in terms of increasing apoB clearance, enhancing the body’s ability to get apoBs out of circulation. That’s really our goal."
**** "Mostly this is done by amplifying the activity of LDL receptors (LDLR) in the liver, which absorb cholesterol from the bloodstream."
*** statins
    "inhibit cholesterol synthesis, prompting the liver to increase the expression of LDLR, taking more LDL out of circulation."
**** TODO why would inhibiting cholesterol synthesis prompt the liver to make more LDLR?
*** which he prefers
**** a statin or something like it
     serial
     "I tend to start with rosuvastatin (Crestor) and only pivot from that if there is some negative effect from the drug (e.g., a symptom or biomarker)."
     Barring that, "I like to use bempedoic acid (Nexletol)", which is newer.
**** and pairing with that
     or both?
***** either Ezetimibe
      "Ezetimibe pairs very well with statins because statins, which block cholesterol synthesis, tend to cause the body to reflexively increase cholesterol reabsorption in the gut—exactly the thing that ezetimibe so effectively prevents."
***** or a PCSK9 inhibitor
      "statins plus PCSK9 inhibitors is the most powerful pharmacological tool that we have against apoB. Alas, statins do not reduce Lp(a), but PCSK9 inhibitors do in most patients,"
**** and for triglycerides
***** "dietary interventions are aimed at reducing triglycerides, but in cases where nutritional changes are insufficient, and in cases where genetics render dietary interventions useless, fibrates are the drug of choice."
***** "Ethyl eicosapentaenoic acid (Vascepa)" also works
** "Nearly all adults are coping with some degree of vascular damage, no matter how young and vital they may seem, or how pristine their arteries appear on scans."
** "When we say LDL or HDL, we are typically referring to a type of particle; when we say LDL-C or HDL-C, we are talking about a laboratory measurement of the concentration of cholesterol within those particles."
** Why the CT angiogram is worth it
   "While the CT angiogram costs a bit more, requires IV dye, and exposes the patient to slightly more radiation, I struggle to find credible arguments against its use. Approximately 15 percent of people who have a normal calcium score (0) are still found to have soft plaque or even small calcifications on CT angiograms, and as many as 2 to 3 percent of people with a zero calcium score are found on CT angiogram to have high-risk plaques."
* cells and cancer
** screen early
** “liquid biopsies"
   "can detect trace amounts of cancer-cell DNA via a simple blood test."
   "cell-free DNA"
** how cancer cells differ from ordinary ones
*** they don't stop growing
    "cancer cells don’t grow faster than their noncancerous counterparts; they just don’t stop growing when they are supposed to"
*** they metastasize
    going to where they shouldn't be
*** they use glucose up to 40 times faster
    :PROPERTIES:
    :ID:       4f4f837c-0299-46d1-9a43-882e7599de59
    :END:
    and they use it to create energy anaerobically ("anaerobic glycolisis") which is inefficient -- yielding only 2 ATP molecules instead of 36 -- and appears unnecessary since there is plenty of oxygen available to them. But it produces lots of other molecules, whereas aerobic glycolisis only produces ATP, and because cancer has to build new cells, those other byproducts may be the point.
** chemo & collateral damage
*** some of the earliest chemotherapy agents, some of which are still in use ... attack the replicative cycle of cells, and because cancer cells are rapidly dividing, the chemo agents harm them more severely than normal cells. But many important noncancerous cells are also dividing frequently, such as those in the lining of the mouth and gut, the hair follicles, and the nails,
** Metabolic diseases are correlated with cancer.
*** This is likely related to [[id:4f4f837c-0299-46d1-9a43-882e7599de59][cancer's metabolism]].
*** Non-subcutaneous fat is a big cancer risk.
    Dying fat cells secrete inflammatory cytokines,
    which damage DNA. Many other pathways too.
*** Insulin enables cancer to grow faster.
** Muscle doesn't get cancer.
** Caloric restriction
*** is effective in mice.
    Those mice died of cancer at "far lower rates".
*** Fasting improves chemo targeting.
    "fasting, or a fasting-like diet, increases the ability of normal cells to resist chemotherapy, while rendering cancer cells more vulnerable to the treatment."
*** "This flies in the face of traditional" cancer treatment
    "which is to try to get patients on chemotherapy to eat as much as they can tolerate, typically in the form of high-calorie and even high-sugar diets. The American Cancer Society suggests using ice cream “as a topping on cake.”
** immunotherapy
*** one kind
    "taking T cells from a patient’s blood, then using genetic engineering to add antigen receptors that were specifically targeted to the patient’s tumors."
*** another: "checkpoint inhibitors"
    "Instead of activating T cells to go kill the cancer, the checkpoint inhibitors help make the cancer visible to the immune system."
*** when immunotherapy works, "it really works"
    "Between 80 and 90 percent of so-called complete responders to immunotherapy remain disease-free fifteen years out. This is extraordinary—far better than the short-term, five-year time horizon at which we typically declare victory in conventional cancer treatment."
** early detection
*** why
    "The ten-year survival rate for patients with metastatic cancer is virtually the same now as it was fifty years ago: zero."
*** only five kinds of cancer have agreed-on screening methods
    "Out of dozens of different types of cancers, we have agreed-upon, reliable screening methods for only five: lung (for smokers), breast, prostate, colorectal, and cervical."
*** False negatives => use multiple kinds of tests.
*** "blood testing for PSA, prostate-specific antigen, in men"
**** use multiple kinds of test
     [not just the level, but also] "PSA velocity (the speed at which PSA has been changing over time), PSA density (PSA value normalized to the volume of the prostate gland), and free PSA (comparing the amount of PSA that is bound versus unbound to carrier proteins in the blood)."
*** Recommends colonoscopy every 2-3 years.
    The AMA recommends 10.
    But they can appear in as little as 6 to 24 months after a normal colonoscopy, and they are unusually easy to treat if caught fast, and are exceptionally deadly -- third out of all cancers, just after lung and breast/prostate for men/women.
*** ask the doctor before getting a colonoscopy
    "ask what your endoscopist’s adenoma detection rate (ADR) is. The ADR is the proportion of individuals undergoing a colonoscopy who have one or more adenomas (or colon polyps) detected. The benchmarks for ADR are greater than 30% in men and greater than 20% in women. You should also ask your endoscopist how many perforations he or she has caused, specifically, as well as any other serious complications, like major intestinal bleeding episodes (in a routine screening setting). Another question you should ask is what is your endoscopist’s withdrawal time, defined as the amount of time spent viewing as the colonoscope is withdrawn during a colonoscopy. A longer withdrawal time suggests a more thorough inspection. A 6-minute withdrawal time is currently the standard of care.”
* TODO Alzheimer's, chapter 9
