:PROPERTIES:
:ID:       c0465799-391d-446f-a957-28ff65d72e10
:END:
#+title: parsing initial super-indented org-children in org-roam data
* a surprisingly equivalent problem
  pre-content: more faithful representation of org data
  for when the first branch to read is not the top branch in the view,
  because a previous branch explains the order
* incomplete
* paragraph
  The sequence of contents from any branch actually goes in both directions. We usually only count in the positive direction, but if the first heading contained is deeply indented, it can be a negatively ordered "pre-content" of the later bigger brother which is still not as big as the original branch point.
* examples & riddles
** pre-brothers
   :PROPERTIES:
   :ID:       be010589-7246-45de-a895-29363be86e56
   :END:
   What is the relationship between b and c here? Should b and c both be considered pre-content of d, with b coming first?
   * origin
   **** a
   *** b
   *** c
   ** d
** Giving each first brother an optional pre-content list would preserve the topology.
   Each pre-content could be an unfoldable tree, just as org-mode permits.
   The display always shows the pre-content (at least folded) if it shows the content.
* purpose
  My purpose when I indent a first branch too far
  is to clarify that it should be read ahead of everything else.
* does this preserve all the info
* what pre-content is in org-mode
  Let "top-level" among a set of subheadings with a common parent heading P
  mean being indented one more space than P.
  Even if P has descendents, there need not be any top-level ones.
  Let the higheset among a set of descendents of P
  be those with the fewest number W of asterisks.
  If there are descendents of P,
  then there is a first highest descendent of P.
  Call it F.
  If any descendent of P comes before F,
  then the series including F and all its highest-level siblings
  has pre-content.
* and what about the origin's body?
  From org-mode to skg, the body of a container is also effectively pre-content to all its descendents, even the pre-content.
* how to parse an org file
  From the top, repeat this:
** Find the next heading, H.
* Very explicit
** enough, I think, to infer the algorithm
   Each(this "each" is more general than necessary) node
   may have, in addition to content, pre-content.
   The order the pre-content displays is the same one org-mode shows (see [[id:be010589-7246-45de-a895-29363be86e56][pre-brothers]] example).
** It captures the topology but not the measure.
   The exact number of asterisks in an org-mode bullet will not be reconstructible, because (at least as I use it) pre-content indented slightly means the same thing as pre-content indented a lot.
* to get the measure too
  Could treat the level of indentation of pre-content as
  the importance of reading it before the content,
  an integer >= 1.
