:PROPERTIES:
:ID:       eb5b3bb1-891b-4a2c-a861-474a311e7275
:END:
#+title: Philosophy seems useless to me.
  I had tried a number of philosophers before I got to Nietzche. I never felt like what they were talking about was useful, but I thought the problem was mine. I've tried reading philosphy since Nietzche too, but ever since Nietzche I've been under the impression that there really isn't anything there for me.

  The interesting questions for philosophy to answer are how to be ethical. "What is stuff?", "What is a mind?", etc. just don't seem to me to be questions you can say anything useful about without experimental data, and once you're doing experiments it's not philosophy, it's science (physics, cog sci, etc.).

  And while I would love to see someone provide an irrefutable, Principia Mathematica-like derivation of the correct way to be ethical, it just doesn't seem to be on the cards.

  Clearly (to me), one should care about everyone, and which species to include in "everyone" is not obvious. Clearly (to me), one should value both happiness and rights. Clearly (to me) consequentialism makes sense and deontology is dumb.

  I don't know how to justify those beliefs. But I also know in my bones that my mind is not going to change, so philosophy becomes an exercise in justifying my own beliefs or trying to change someone else's mind. Neither of those is valueless propositions, but as a matter of hourly return, I'd expect to gain more from washing the dishes.
