:PROPERTIES:
:ID:       6e357bfc-6b14-4696-b6e6-6d470398f616
:END:
#+title: sc3-plugins (SuperCollider tools)
* I packaged it for NixOS and submitted it to nixpkgs.
  https://github.com/NixOS/nixpkgs/pull/142626
* PITFALL: On NixOS, using SC with plugins requires some configuration.
  :PROPERTIES:
  :ID:       b45a1d6d-3cef-472e-9c4f-44b8296bd17e
  :END:
** why
   Installing SC and SC3-plugins is not enough
   to use the latter in the former.
   That's because SC still doesn't *know* about SC3-plugins.
   The non-NixOS remedy involves changing the installation.
   NixOS requires something else.
** how
   serial
*** create symlinks in the local SC user extensions folder
**** what those links should look like
     jeff@jbb-dell:Extensions$ pwd
     /home/jeff/.local/share/SuperCollider/Extensions

     jeff@jbb-dell:Extensions$ ls -l
     builtin-plugins -> /nix/store/aggfx5237n4w92rfjlxcdgxk0i2rwq90-supercollider-3.12.1/lib/SuperCollider
     sc3-plugins     -> /nix/store/jfpar7cfahcc2464q3fs37pf5lmdk63n-sc3-plugins/share/SuperCollider/Extensions/SC3plugins
     sc3-plugins-so  -> /nix/store/jfpar7cfahcc2464q3fs37pf5lmdk63n-sc3-plugins/lib/SuperCollider/plugins
**** if the `builtin-plugins` link breaks
     run
       ls -l $(which scide)
     to find the latest location of scide,
     and then replace bin/scide -> lib/SuperCollider
**** if the `sc3-plugins` link(s) break(s)
     That's never happened before.
     But it probably happens if I rebuild sc3-plugins in a new place.
     Find all the places called sc3-plugins,
     and (probably) use the most recent.
*** start the SC server in an extensions-aware manner
**** If starting SC from the command line
     then specify where to fetch extensions with the -U option.
     Here's what I'm doing lately:

     export SC_JACK_DEFAULT_INPUTS="system"
     export SC_JACK_DEFAULT_OUTPUTS="system"
     scsynth -u 57110 \
             -m 1000000 \
             -U /home/jeff/.local/share/SuperCollider/Extensions/
     # The -m option allocates (roughly?) 1GB of memory for it.
**** If starting from SCIDE, specify `ugenPluginsPath`
     // Execute these in serial.
     s.options.ugenPluginsPath = "/home/jeff/.local/share/SuperCollider/Extensions/"
     s.boot;
