:PROPERTIES:
:ID:       ac9caea1-3d84-41eb-afc9-16018c542f16
:END:
#+title: sermons
* the pastor fantasy
  One would like to regularly broadcast a message that many people found useful in their lives.
** Depends on the pastor knowing more than many, about things they want to know, and being able to make it digestible.
* teaching, study and research
  In knowledge, one can either push its frontiers, study (not just the frontier of) it, or share. If you believe in simple population numbers -- the number of people who have demonstrably not understood values and principles that you at least understand somewhat -- and you can teach at scale, teaching is clearly valuable.
* A good person learns, and can change their mind and explain it.
  Especially about important things.
  One would like to both teach and study. And the most important principles deserve being revisited. The teachings of an honest researcher, therefore, can legitimately contradict their own earlier contradictions, at least to the degree that learning can explain such a difference.
