#+TITLE: smsn
#+ROAM_ALIAS: "Semantic Synchrony (software)" SmSn
* refs
** handy files/folders
*** ~/Encfs/kb-no-encfs/
*** ~/smsn+/smsn-mode/lisp/smsn-commands.el
*** ? latest data
 ~/_stale/pre-2019-07/smsn,maybe-latest-data/kb-not-encfs/neo4j
   dec 15, 2018
 /run/media/jeff/shuttle/smsn/kb
   (encrypted)
   dec 15, 2018
 ~/home/jeff/smsn-resurrect/kb/neo4j
   dec 10, 2019 -- IMPOSSIBLE
 ~/_stale/pre-2019-07/smsn+/kb
   june 15 2018
** online
*** smsn command reference
 https://github.com/synchrony/smsn-mode/wiki/Command-reference
*** installing smsn
 https://github.com/synchrony/smsn/wiki/Installation
* TODO rebuild docker image with iproute2
Dockerfile is already modified (but not committed) for that.
* TODO get metadata working too
It should include list-of-repositoroies.txt.
I should move files on each cycle so that it includes activity.log.
* TODO clean SmSn for others
** update docker-smsn repo
** update docker image(s)
** document how to [[id:ba1a3e6f-0407-4004-8aa0-7333b0673b42][build the Dockerfile]]
* TODO change smsn
** the RH column should be on the left instead
because in a long list of short items it's hard to see how they line up with the RH
* smsn / how to do stuff
** outside smsn
*** build the Dockerfile
    :PROPERTIES:
    :ID:       ba1a3e6f-0407-4004-8aa0-7333b0673b42
    :END:
**** build the .jar natively, copy it to docker-smsn
  Run this from the root folder of the smsn/ code:
    gradle :smsn-server:shadowJar
  Somehwere, that will build a file that matches this regex:
    smsn-server-*-all.jar
  Copy that to be a sibling of the Dockerfile.
*** launch SmSn
**** sequentially
***** docker run
docker run -it --name smsn \
  -v ~/Encfs/kb-no-encfs:/mnt/smsn-data \
  -p 8183:8182 -d -h 127.0.0.1 \
  jeffreybbrown/smsn-develop:gs_3.2.5
***** PITFALL: then enter the Docker container and run `start`
**** TODO PITFALL: Docker won't mount an Encfs sink
    :PROPERTIES:
    :ID:       8ed67ee7-e7ec-453d-a40e-283105c7fe8f
    :END:
That is, a folder that Encfs is funneling data into.
*** the Git cycle
**** Edits:
     File this somewhere:
       * :JNakrwxcuXNnQ7HS:
**** PITFALL: DON'T PULL until committing.
**** Write to VCS.
**** Run "lost-nodes.sh"
**** Delete things.
     cd /home/jeff/Encfs/kb-no-encfs/vcs
     grep "^@title \[delete" -r .
** inside smsn
*** set-source
**** The move mode command is "s".
**** How I fixed it
 (It wasn't working for a while.)
 It started working once I fixed smsn.yaml and updated smsn-mode.
*** visit note by id
    C-c o
    smsn-open-note-prompt
*** Write vCs: C-c C-w c
