:PROPERTIES:
:ID:       9ac5ebd7-ad3b-414f-a9e4-9c3cd0c4616a
:END:
#+title: some principles some mindmappers visit regularly
   https://twitter.com/michael_nielsen/status/1615093198808027137
* http://www.paulgraham.com/vb.html
** TODO RESUME
   at first instance of the phrase:
     you can probably find employers that will waste less of your time.
** "[bullshit is] the junk food of experience"
   "addictive but unrewarding pastimes."
   "Unnecessary meetings"
   "it's either forced on you, or it tricks you."
*** [jbb] Awareness ought to solve this.
    Ask frequently whether something is necessary and/or rewarding,
    and adjust behavior accordingly.
** "[A]sk yourself whether you'll care about it in the future.
   Fake stuff that matters usually has a sharp peak of seeming to matter"
** Enthusiastic impatience is the converse of mortality-hyperawareness.
   "it doesn't seem the right answer to be constantly reminding oneself of the grim reaper hovering at everyone's shoulder. Perhaps a better solution is to look at the problem from the other end. Cultivate a habit of impatience about the things you most want to do. Don't wait before climbing that mountain or writing that book or visiting your mother. You don't need to be constantly reminding yourself why you shouldn't wait. Just don't wait."
** Savoring life slows it down. FLow states lack savoring.
