:PROPERTIES:
:ID:       a5b74e88-c524-4f89-b29d-1bc324a77369
:ROAM_ALIASES: remember memory internalize
:END:
#+title: spaced repetition
* In Emacs, [[id:73882d3f-fe8a-437c-964c-c34144cca759][`C-x space` is a better way to delineate rectangles.]]
* It's better to call someone than have them call me.
  If they're late to call me it's annoying.
* I lost 2 days of work to a duplication style mistake.
  :PROPERTIES:
  :ID:       9b727e69-2e92-4159-9f04-68be6d40d5d6
  :END:
  If two functions look very similar,
  that should smell bad for yet another reason:
  Once I'm using one of them and not the other,
  I might edit the other (unused) one thinking I'm editing the one in use.
  Then when it doesn't work, I'll look for a solution elsewhere at length.
* Ask people about their life stories, decisions
** Normally they talk about the recent.
* Does meta awareness stop pointless behaviors?
* TODO I have a few notes like this; join them.
  search for "internalize", "spaced repetition", maybe "to learn", "remember"
* When LCR invites me to something (e.g. with journalists).
  Make sure I know who's coming before responding.
* When I receive something from someone, do what?
  Write it down,
  because I might need to know that they can provide that.
* why to format notes-to-learn as flashcards
  That way I can hide the answer when reviewing,
  which lets me know when to discard the flashcard.
* how to estimate (e.g. duration)
  Estimation (e.g. of duration) is best done via indepedent chunks, rather than a wholistic intuition. (per Daniel Kahneman)
  Then subdivide a different way and estimate again. (per some guy quoted by Steve Levitt in his podcast interview with DK in 2021).
* I wrote down some [[id:4e3cfc01-d528-49d9-bf3d-858c1979d71c][Microsoft Teams shortcuts]].
* coding
** re. choosing type names
   make sure they are sufficiently complete.
   For instance, Action turned out to be a worse name than ScAction,
   and renaming took me like 15 minutes.
** git hygiene
*** what is fragile?
     an unindexed file
It's dangerous to leave files I want in a clone of a git repo without adding them to the repo.
 That's because I might copy a file of the same name into the folder from elsewhere.
*** DONE make git diffs readable by doing what?
Include empty lines where appropriate.
 Because when you change one paragraph, the changes will not bleed into changes of the next paragraph; the unchanged empty line continues to separate them.
* macroeconomics
** The special international status of the US dollar is not important to the US.
   https://mail.google.com/mail/u/0/#inbox/FMfcgzGkXctVmLFSxwJThvtnzflnqFML
*** maybe the biggest benefit
    The dollars held outside the US do represent a 0-interest loan, which in times of high interest rates can be meaningful -- about 0.25% of GDP.
*** some non-existent benefits
**** The US current account deficit is less than Britain's or Australia's.
**** The US borrows at a higher interest rate than Britain or Japan.
**** The British pound, which was only overtaken by the US dollar in 1955 and not special at all by 1975, has only increased in value against the dollar since.
** Countries might not give the widest coverage as units of news analysis.
   There's something repetitive about "this country's got a tyrant ... and this other country's got a tyrant ... and here's what the tyrant over there's doing ..."
* reviewed, still no insight
** (Aspirational) mimicry can substitute for rationality.
   It's in SmSn, at id
   BSPkZvDjoUqhzm0Z
** Maybe give ownership to the shy
   paraphrased: "Children feel less in control than we realize, so hang back a bit, let them own the conversation." --Tyler Cowen
** on wonder, fear, and creativity
    "If the world seems to be getting bigger and funnier all the time, your intelligence is steadily increasing. If the world seems to be getting smaller and nastier all the time, your stupidity is steadily increasing.”

     — Robert Anton Wilson
** befuddling: links in knowledge graphs
*** link labels vs. link contexts
    [[id:46b695c5-617e-47a8-b699-ef2b7ec29e81][the context of a link matters]]
*** [[id:3305442a-e435-4f84-a403-9509963497b7][Note titles should be complete sentences.]]
*** [[id:edca15b1-37f9-46ec-bb32-8a3090242b0d][? Use backlinks to define notes extrinsically]]
* DONE internalized
** Why to keep my earpbuds in their cardboard box.
*** Protect the spongey parts from getting ripped off in a tight pocket
*** Hear when they fall out of pocket
** In python, what's a terse way to repeat a list?
[1]*3 = [1,1,1]
