:PROPERTIES:
:ID:       953797b4-486c-4563-9c1e-9c6294f26890
:END:
#+title: The Meiji Restoration was a blistering industrialization.
* source
  [[id:55dd37d6-32d3-445d-a389-298db33178bc][The Knowledge: How to Rebuild Our World from Scratch (book), by Lewis Dartnell :: link for references]]
* quote
"perhaps the most impressive feat of leapfrogging in history was achieved by Japan in the nineteenth century. During the Tokugawa shogunate, Japan isolated itself for two centuries from the rest of the world, forbidding its citizens to leave or foreigners to enter, and permitting only minimal trade with a select few nations. Contact was reestablished in the most persuasive manner in 1853 when the US Navy arrived in the Bay of Edo (Tokyo) with powerfully weaponized steam-powered warships, far superior to anything possessed by the technologically stagnant Japanese civilization. The shock of realization of this technological disparity triggered the Meiji Restoration. Japan’s previously isolated, technologically backward feudal society was transformed by a series of political, economic, and legal reforms, and foreign experts in science, engineering, and education instructed the nation how to build telegraph and railroad networks, textile mills and factories. Japan industrialized in a matter of decades, and by the time of the Second World War was able to take on the might of the US Navy that had forced this process in the first place."
