:PROPERTIES:
:ID:       aedc10e0-dfdd-4459-9fb1-cae55462cdef
:END:
#+title: The World of Yesterday (book), by Stefan Zweig
* The Jews who believed most in Germany were the slowest to try to leave, and therefore the least successful at it.
* Before a disaster, almost nobody believes it will be a disaster. Covid was like this. World war II also
* Riders, poets, and clergy who had been admired only weeks before for their humanity, once the war started, became crazed fountains of propaganda. That, at least, was what Zweig saw in Germany in 1914
* In Germany in 1914, as the war started, people were jubilant. In 1939 it was not like that.
* The onset of political authoritarianism coincided with a moral revolution. People were repressed before then, sexually, and women were basically caged, an absurd costumes that prevented movement and looked after by Nanny's who made sure they would not leave the house until they were married. Prostitution was rife, and young men needed that outlet because it was the only one.
* As shcoolkids they would sneak poetry and philosophy into their textbooks on other stuff, nesting book in book
* What your peers become interested is an extremely strong influence
* Zweig's tyrannical experiencie of school gave him a lifelong hatred of authoritarianism, and he almost forgot where that hatred came from.
* They didnt know kids need exercise and fresh air
* In Vienna circa 1900, everyone trying to get ahead tried to look older. It was scandalous when they gave Mahler control of the conservatory at age 38.
* Hitler promised so much to so many that when he gained power, diametrically opposed groups were simultaneously happy.
* [[id:423db924-54ca-4edf-8a91-36c606c5fd9f][inflation's weird effects in Austria post-WWI]]
* War made the young distrust the old.
* Germany went through a brief period of "loose morals" and cultural upset during the hyperinflation immediately following WWI that, Zweig believes, set the stage for authoritarianism.
  Promiscuity, transvestite balls.
  Boys who found a box of soap at the dock could sell it, one bar at a time, and live well for a month, while their parents working their normal jobs were destitute.
  Everyone tried to seem young. Writers with previously perfect grammar became intentionally sloppy.
