:PROPERTIES:
:ID:       14cb4309-9afa-405a-942f-a743e5a9fd9f
:END:
#+title: The Knowledge: How to Rebuild Our World from Scratch (book), by Lewis Dartnell
* TODO RESUME at
  The post-apocalyptic world is therefore likely to experience a rise in sea level of several meters
* agriculture
** threshing
*** is separating grain from the rest of the plant
*** the simplest way is to [beat it]
    lay the harvest out on a clean floor and beat it with a flail—a long handle with one or more shorter sticks attached at the end with leather or chain hinges
** after threshing, winnow
*** "his threshing process leaves all the grain mixed in with the empty husks, and you must now separate the wheat from the chaff"
*** "your low-tech option is to simply toss the threshed material into the air on a windy day—the lighter chaff and straw are carried a short distance away on the breeze and the dense grain falls more or less straight back down. Modern machinery creates its own artificial wind"
** we’ve distorted their biology so much that they are now as reliant upon us for their survival as we are upon them for our own. Every crop we grow today ...
** cereal crops are all grasses
   even corn
** Legumes, unlike other crops, put nitrogen back into the ground.
   And they include alfalfa, clover and peanuts.
** "a crop rotation [of] several stages" "breaks the cycle of diseases and pests"
   In Britain, the cycle
     legumes, wheat, root crops, barley
   worked best. This is the "Nortfolk four-course rotation".
** "with a root vegetable, you can plant a crop and still be able to rip out weeds between the rows"
** "the adoption of the humble turnip and other root crops for fodder heralded a revolution in medieval agriculture. Not only are these more effective than grazing for fattening up livestock over the summer, but they also provide a reliable energy-rich feed throughout the winter."
   Before their introduction, every late autumn medieval Europe witnessed the mass slaughter of livestock, as there was simply insufficient food to keep the animals from starving before spring.
** human waste as fertilizer requires treatment
   "you can’t start gleefully smearing untreated sewage across crops you intend to eat later: you’ll simply complete the life cycle of numerous human pathogens and trigger widespread outbreaks of disease."
   Urine should be separated from feces, as it "is sterile and so can be diluted and applied directly to the land."
** Composting produces heat that kills parasites.
** bioreactors are not high-tech
   "In a compost heap the objective is to keep everything well aerated so that oxygen-needing bacteria and fungi can readily decompose the matter. But if instead you hold the waste in a closed vessel, blocking oxygen from getting in, anaerobic bacteria thrive and partly convert the organic material into flammable methane gas."
   This was common in Europe in WWII.
* An inverter converts DC to AC
* An alternative design of rechargeable lead-acid battery, known as a deep cycle, discharges at a much slower rate and can have almost its entire capacity repeatedly drained and recharged without problems
* A car alternator provides a steady 12v across it's terminals no matter how fast it spins.
* Car batteries "are easily damaged if persistently allowed to discharge by more than about 5 percent."
* Although the potency of a pharmaceutical will decline as the active ingredient in the tablet chemically degrades, there’s no great risk that it’ll harm you.
* [after cleaning it] pull the lips of the injury together and administer the superglue only along the surface to bridge the gap and hold it closed.
* Antibiotics marketed for farm and pet animals, and even for fish aquariums, are exactly the same as for humans
* Gasoline goes bad! Oxidation makes a gummy residue, and condensation permits mold to grow. These can be filtered.
* [not exposed to] moisture and oxygen), so unmilled whole wheat grains remain good for decades
* Just a few drops of a 5 percent liquid bleach solution that has sodium hypochlorite listed as the main active ingredient will disinfect a whole liter of water in an hour.
* some plastic can be re-molded
  "thermosetting plastics and thermosoftening plastics (or simply thermoplastics). Thermosetting plastics are nigh on impossible to recycle: when heated they decompose into a complex mixture of different organic compounds, many pretty noxious. Thermoplastics, however, once cleaned, can be melted and re-formed into new products."
  "the quality of plastic products degrades with exposure to sunlight and the oxygen in the air, and they become weaker and more brittle each time they are recycled."
* Without light, algae won't grow in water.
* steel expands as it rusts, rupturing the concrete from the inside
  as mildly acidic rainwater soaks through, and humic acids released by rotting vegetation seep into the concrete foundations, the embedded steel begins to rust inside the structures
* Freezeing and thawing wears down mountains.
  just like pavement -- water gets into cracks and freezes, expanding to make more cracks
* Genetic analyses suggest that the Maoris and (more interestingly) most Native Americans descend from a founding population on the order of 140 people, around half of them female.
* "the observation that first hinted at the deep coupling between electricity and magnetism [was] the twitching of compass needles left next to a wire carrying current
* "One of the major catalysts for the Renaissance in the fifteenth and sixteenth centuries was the trickle of ancient learning back into Western Europe."
  "Much of this knowledge, lost with the fall of the Roman Empire, was preserved and propagated by Arab scholars carefully translating and copying texts; other manuscripts were rediscovered by European scholars."
* [[id:953797b4-486c-4563-9c1e-9c6294f26890][The Meiji Restoration was a blistering industrialization.]]
