:PROPERTIES:
:ID:       dec78208-aed2-4c2d-b23a-d7af870b91a7
:END:
#+title: the adventures of bread and bucket
* [[id:56837324-188f-4639-8adc-e1a2e58765a2][David Suarez]]
* Tender, challenging and insane.
* panels
** "A heavy chihuaha sat on Bucket."
   Bread is lying on her back, hands behind her head, very near and looking in the same direction as Bucket.
   Bread was imagining circles. Bucket interrupted: "Help! This chihuahua is heavy!"
** hard work
   two images, one panel
*** "Bucket strained under the chihuaha's butt."
    Bucket is sweating.
    Bucket flexes and strains against the weight of the butt.
*** "Bread began to think hard."
    She is sweating, too.
    "Bucket and the chihuahua are made of atoms. The chihuhua's atoms are bombarding Bucket's. The problem is atomic bombardment."
** "The Delights of Hyperfast Awareness drifted past them."
   The sun's warmth. The truth of self and other, being and stillness, reality and imagination. (((Milk in coffee) in time) in numbers), and the reverse. Metaphors of every sort, enjoyed as a balanced whole.
   [Text, no image.]
** "Bread, thinking, ignored the Delights."
   "Bread thinks using chemical reactions like drying and decomposition."
   Bread is not anthropomorphic now, but accurately a piece of dessicating bread.
** solution
*** top left: "Bread engineered a new strain of yeast."
*** image: sciencey fun
    a protozoa holding a beaker
*** bottom right: "Bucket asked how the yeast would help."
** 'Bread explained, "Will it help? Have you forgotten about time travel, again, already?"
   Image: A man standing in a box of mirrors, his hands raised, his facial expression one of sudden recognition.
** they change
   "Planted in history, the new yeast had uncountably infinite effects. The universe Bread and Bucket had known was lost forever. Now they were Tortilla and Telescope."
   The two of them stand in a spotilight, leaning back, pointing their fingers at the camera. Their smiles are knowing, relaxed, sexy.
** "Rewriting time sent them to outer space."
   It has stars, a mop, a banana, and a pentagram among some of the stars.
*** Bread, proudly: "Now we are bombarded by almost no atoms at all!"
** "Bucket, though grateful to Bread, wondered whether physical integrity was worth freedom from gravity and the wind. Bread heard Bucket wonder. Bread promised Bucket, "I'll let you know. My own physical integrity will not survive vacuum and intense UV bombardment for long."
** Indeed, their physical integrity did end. Billions of years later, they are now two very diffuse, partially overlapping gas clouds.
   alternatives
   Aren't we all?
   So really just a change in degree, not in kind.
** [no text: remain best of friends]
   Image: Both still have physical integrity. They hold hands and skip along one of Saturn's rings. Bagel and Bucket.
* adding background jokes feels lower-value
** example
   [[id:22bed39b-f45b-4f51-991b-d1480bc6e466][NAH ? In the background an adult rides a child's go-kart.]]
* encourage
** humility
** optimism
** honor
** hard work
** charity
** gratitude
** a completely left-field idea can have an epic payoff
** being damaged by someone else's assumption
** sacrifice
