:PROPERTIES:
:ID:       cf3d9e97-2c7a-4c2c-a6d3-33ea4dab2654
:ROAM_ALIASES: karma
:END:
#+title: There is no time outside of karma.
* defining , attempts at
** More precisely, karma is more fundamental.
** [[id:865222da-06c9-4714-8b22-72ffd3187993][Karma is inseperable from population details.]]
*** [[id:5f647d47-1610-4e3c-8b2a-9b3b251eb351][Causation is who?]]
** karma ~ consequences
* technical
** [[id:e54b0669-aa26-45cf-a5fa-6bb41f871790][Time is time's initial/foundational conditions.]]
* [[id:63b8cda1-44f2-433d-8691-f27075d133cd][far out]]
** evil-looking benevolent paternalistic coincidence
   :PROPERTIES:
   :ID:       2048d60f-627f-4768-ae73-0832612f96df
   :END:
   You might have a simple economic story for why someone did something {selfish, stupid, malevolent}. Their "higher self", meanwhile, chose those actions benevolently for you, bearing in mind its inifinitely complex ramifications -- who you would meet, what concepts and feelings you would encounter -- while making a face like "take that you little bastard".
** karma > [[id:0a6dcf44-6c2c-432a-90a7-babfbb3e0b7d][justice]]
   There might be no justice but there is karma. The way it feels, to who, and the strange resulting inequality, the biggest winners having the hollowest existences, and those with the fullest often not recognizing it.
** Rather than redistributive justice, compositional.
*** elaboration
    Justice being something one recognizes, rather than achieving --
    each being's conditions somehow an outgrowth of its nature.
*** counterargument
    Potentially harmful idea,
    both for its quietist (de-motivating) implications,
    and for justifying injustice.
