:PROPERTIES:
:ID:       62d4071a-c7d5-4671-baa5-94b620fe2a77
:END:
#+title: TidalCycles, installing and updating
* PITFALL: There are numerous pieces to update.
  https://tidalcycles.org/docs/getting-started/upgrading
  Tidal, the SuperDirt quark, the Emacs extension, maybe more.
* TODO Did I need to run `cabal install`?
  I want to hack the source.
  Does this mean I'll be duplicating code on my machine for no reason? Is it a lot?
* TODO Change the location of BootTidal.hs
  see the bottom of this page:
  https://tidalcycles.org/docs/getting-started/editor/Emacs
* TODO run from my own fork of the source
* BLOCKED asking : specify `ugenPluginsPath`
   https://club.tidalcycles.org/t/tidal-on-nixos-can-i-specify-ugenpluginspath-to-supercollider/3581
* TODO to test TidalCycles in Emacs
  In a file called "something.tidal",
** start Tidal: C-c C-s
** write this line
   d1 $ brak $ sound "bd sn/2"
** evaluate it: C-RET
* how I installed it for Emacs
** I downloaded tidal.el to a new folder.
   mkdir ~/.emacs.d/elisp/tidal
   cd    ~/.emacs.d/elisp/tidal
   wget https://raw.githubusercontent.com/tidalcycles/Tidal/master/tidal.el
** I told my .emacs config about it.
   (add-to-list 'load-path "~/.emacs.d/elisp/tidal/")
   (require 'haskell-mode)
   (require 'tidal)
