:PROPERTIES:
:ID:       6338f677-2e09-4202-96bb-d5444247bf7a
:END:
#+title: to watch
* Bullets over Broadway, black comedy, Woody Allen
  Brian Florian rec's
* Photographing Fairies, scifi film
  Brian Florian rec's
* sci fi, Brian Ragazzi recommends
** Rick and Morty, many worlds
** Invader Zim
** The Orville
* Tyler Cowen on Adam Smith and Colombia
  https://www.youtube.com/watch?v=41CGc47MraY
  Resume at 8:22
* Love death and robots
  5-10 minute scifi shorts, very high-quality animttion.
  Adrian rec's highly.
  On Netflix.
* Scott Pilgrim vs. The World
  Weird.
  (Andres?), who I met that day, recommended after watching "Everything Everywhere ..."
* Kingsman
  Weird.
  Grace, who I met that day, recommended after watching "Everything Everywhere ..."
* Undone (series, Amazon Prime)
  Rabidly rec'd by Dominique Lewis on Facebook.
* The Americans (series, Netflix)
  Russian spies
* Ellen sends how to make a smokeless wood stove
  https://mail.google.com/mail/u/0/#inbox/FMfcgzGpFgqmWWJBrNjjXstgfpLncrhV
* [[id:cbaf750e-4098-45bc-9e66-b7d00092faff][Mary Queen of Scots]]
* Patria, movie about Mexican revolution
** Cliff rec's
** There's also a series, probably something else.
* Cliff on USAID, 53 min
  https://mail.google.com/mail/u/0/#inbox/FMfcgzGlksCTlffBqjLhQfjmbjKsrSvZ
* Cliff rec's historical dramas
  Bolivar
  The Red Queen
  The White Queen
  The Normans
* Bran rec's Bojack Horseman
  """
  It's definitely bleak, but the quality of being amused with its own bleakness starts to change as they develop Bojack's character and he starts realizing that he's been hurting everyone around him and starts to seek redemption. In a nutshell, it's basically about how we must break the cycle of generational trauma and heal so we can stop hurting the people around us...punctuated by animal puns.
  If I could recommend you watch 3 episodes, they would be in order: The Old Sugarman Place, Time's Arrow, and Free Churro. The first 2 are in season 4 and the final one is in season 5.
  """
* Hanna Gadsby: Nanette
* James Acaster: Cold Lasagne Hate Myself 1999
* math on Youtube
  3blue1brown
  Mathologer
  Numberphile
* Sidney's mostly sci-fi TV rec's
  All 1 season unless noted.
** Amazon Prime
*** Electric Dreams, 2015
    10 PKD stories.
    Like Black Mirror but more weird, less dark.
*** Tales from the Loop, 2020
    The "kids on bikes" genre.
** Netflix
*** Dark
    3 seasons. German. Time travel.
*** Queen's Gambit
    About a young chess prodigy in the 80s. Not sci-fi.
** Hulu
*** Steven Universe
    Happy.
* Uncle Boonmee Who Can Recall His Past Lives
** not available on Amazon Prime in Colombia
** description
   Thai film, weird, complex.
   Tyler Cowen said maybe the best movie of the last 20 years (in Dec 2021).
