:PROPERTIES:
:ID:       46d56f38-e6a8-43aa-8c74-efccddfb0770
:ROAM_ALIASES: "Vaticle makes TypeDB"
:END:
#+title: TypeDB
* TODO RESUME
** reviewing my notes at
   working downward
** reading the docs at "TypeQL"
   https://typedb.com/docs/typeql/2.x/overview
* refs
** getting started
*** TypeDB Core, installing and launching
    https://typedb.com/docs/typedb/2.x/installation.html
*** client, installing a
    https://typedb.com/docs/clients/2.x/clients
** TypeDB
   https://typedb.com/docs/typedb/2.x/overview.html
** TypeQL
   https://typedb.com/docs/typeql/2.x/overview
** Console
   :PROPERTIES:
   :ID:       c091cef4-e8d0-4880-96a5-6239c7e07604
   :END:
   https://typedb.com/docs/clients/2.x/console
** Python client
   :PROPERTIES:
   :ID:       2e5e9f7f-69af-46c0-8998-c1d224d205a7
   :END:
   https://typedb.com/docs/clients/2.x/python/python-overview
   See sidebar for tutorial & API reference.
* PITFALLs
** Docs use "query" to mean more than read ops.
* [[id:f027e52d-db16-4f2b-9b71-d904901a38a2][getting started with (i.e. running) TypeDB]]
* [[id:8b6e8ffc-e7ec-4c17-946b-23a73b51f3bd][TypeDB model and language]]
* TODO experiments to run
** If you delete an entity, what happens to the relationships it was in?
** Test: are attributes unique per owner?
   This suggests they aren't:
   "A person can have more than one attribute of type full-name. Every instance of attribute will get to the results."
   https://typedb.com/docs/typedb/2.x/development/best
** Is the optional [[id:fd190477-3cd2-4d53-b9fd-b4b31047bdd4][regex]] part of an attribute definition a constraint?
** Try [[id:5a099383-736c-47a3-927b-11390ff0dd9e][defining (schema) a standalone]] ownership or role membership.
   after having defined the relevant types.
*** then try a parallel insertion
    (for the data, not the schema)
** Try [[id:4470f10a-a037-4c02-98ac-24a0c7299c5c][defining new variables]] in a constraint on an earlier variable.
* TODO questions
** [[id:74db29a4-a21e-467c-8aa4-3cb62e393f41][Can a user define their own types?]]
* TODO report errors and maybe-errors in docs
** Unfinished sentence: "The first instance og the"
*** where
    https://typedb.com/docs/typedb/2.x/fundamentals/patterns
*** the quote
    Then the match clause returns all matched combinations, including all permutations: 20 results in total. The first instance og the
    [and then a new section titled "Variables" begins)
** Should the "or" clause in the image at the link end in a semicolon?
   https://typedb.com/docs/typedb/2.x/fundamentals/patterns#_complex_example
** The syntax laid out for undefining rules makes it appear that the "sub" clause is mandatory, but it is not.
   :PROPERTIES:
   :ID:       149fcd59-17f1-4b4d-9f3b-18f8cb66e406
   :END:
   https://typedb.com/docs/typedb/2.x/development/schema
*** For instance, the following undefine query, with no "sub" clause, is valid according to that page.
    undefine

    item owns tag;
