:PROPERTIES:
:ID:       bc4c06c2-10d3-4efd-8287-1482c1d97574
:END:
#+title: UFOs
* 1
** source: The Rest is Classified podcast:
   the four part series ending <2025-07-01 Tue>
** my notes
   The Roswell sightings in 1947 coincided with a secret US military program, Project Mogul, to send high-altitude balloons into the upper atmosphere, 100,000 feet, to take pictures of the USSR and look for sonic evidence of nuclear tests. They tested them in the New Mexico desert. Later, similar programs also included crash test dummies to test ejection systems. Some of the dummies separated from the equipment and landed separately, in at least one case implanting head-first in the sand.
   In 1948 a pilot in the Kentucky Air National Guard chased one of the balloons. His team did not follow, because they knew they did not have the equipment for high altitude adventures. He passed out around 25,000 feet, and his plane crashed, killing him.
   The balloons were not successful. Their trajectories were impossible to control, the vast majority were not recovered, and of those recovered most of the photos were of clouds. Eventually they realized seismic equipment was far more effective for detecting nuclear tests.
   In the 50s the US government suspected the USSR was using UFOs to subvert American public opinion.
* 2
** source: ChatGPT, <2025-07-14 Mon>
** my notes
   The CIA actively encouraged UFO confusion as a way to cover for spy plane flights, including U-2 missions. The agency admitted in a 1990s report that a significant percentage of 1950s UFO sightings were actually U-2s.
   Project Blue Book was the Air Force’s public investigation into UFOs, but internally, officers were told not to dig too deeply. One directive emphasized that too much inquiry might cause unnecessary public attention, fear, or press scrutiny.
