:PROPERTIES:
:ID:       2e0188f7-dde5-4503-be97-3d1fecf060fc
:END:
#+title: Voodoo | West African Disapora religions
* "where African deities are hidden behind Christian iconography"
  https://en.wikipedia.org/wiki/Orisha <2025-07-21 Mon>
  on a syncretic synchronization in Lucumi Voodo
  of the orisha spirits "with Christian iconography".
* "allowed* enslaved Africans to preserve their traditions under colonial religious persecution."
  the Lucumi synchronization allowed
* spirits
** Orisha
   began powerful, from a prior=spirit world
   here to teach humans
** Lwa
*** The number of them is 1 more than the biggest number one can conceive of.
*** Are associated with specific colors and objects, and paired to Christian saints by sharing those associations.
*** Speak to humans through dreams and divination.
*** Humans give them [[id:c893b584-5741-4987-876f-52bfa6c399b1][sacrifice]].
*** They possess human practicioners known as "chwal" (horse).
    :PROPERTIES:
    :ID:       c3cb293e-5848-4b97-8aba-fa367a544c2c
    :END:
    I like how this compensates for the pride of being priestly.
* "Aye" = Earth
