:PROPERTIES:
:ID:       fea64283-c47b-4a3d-b252-c9e5f728b774
:END:
#+title: What "to be a woman" means seems irrelevant. \ transgenderism
* I almost shared this to Facebook
  but thought all I would gain is enemies. Even putting it here seems potentially not in my interest.
* my thoughts
  I'm seeing a lot of posts along the lines of "trans women aren't women". It's irrelevant. Obviously trans people -- at least of the sort that transition as far as is now possible -- are a new kind of person. The definition of "is" is not important; what's important is how to treat them. And the answer is, obviously, with kindness.

  If that means using a different pronoun, and it makes a huge positive difference to how they feel, then unless it makes a huge negative difference to how you feel, you should do it.

  Regarding sports, on the other hand, I don't know.

  The thing about "being a gender" is it conveys a bundle of behaviors that we have accepted as appropriate ways to treat someone in many circumstances. Trans people force us to unbundle those packages. Which would have been good even a thousand years ago.
