:PROPERTIES:
:ID:       126658ea-185a-43a7-b688-577c42d84c5e
:END:
#+title: what I saw in La Guajira, 2023-04-09 Sun
* Beauty, poverty, diesel fumes and more
** The ride
Sandy and I woke at 3:15 to catch the bus at 4:15. It arrived at 4:50. Narrow seats, two on each side, holding a total of maybe twenty. Sandy and I could not fit shoulder to shoulder without twisting, overlapping or other contorting. Inside it was freezing. The old woman next to me wrapped herself in a blanket from head to toe. It must not have been thick because I believe she kept breathing the whole time. We would ride until 2:30 pm, with two stops to it and a few short bathroom/store breaks.

Leaving Santa Marta, the terrain is first forest, then woody scrub, then very sparse scrub with some patches of classic barren sandy desert. We were within a few miles of the beach most of the time, often right against it. Reminded me of Kenyan game parks circa 1990. On the ride back we were on the beach side, which had these weird patches of skeletal maybe-alive trees sticking out from a few feet of saltwater.

For a long while we followed a prominent railroad, tidy, on a long, straight, artificial hill, I imagine to avoid flood damage. Sandy said a foreign mining company had long ago deviated the river, leaving the indigenous without water, ruining whatever their prior economic model was. Goats picked at the scrub, presumably someone's property, but we saw no sign of their owners, or even that the land around us was owned.

At some point the children we passed started holding out their hands as if they expected to receive something from the bus. Sometimes they would run alongside. THat was not a costless act, as the bus belched foul smoke, smoke with something more and worse-smelling than the usual diesel byproducts.

** Sweets
Our first stop, our guides recommended buying sweets for the kids we would encounter later. Someone bought a bag of bags of water, which I wrongly thought the kids would not be interested in.

I bought some, left the store, and was immediately mobbed by indigenous children and a few women, some (all?) of them holding babies. I gave out a third of a bag of lolipops. Sandy said the mobs would be bigger later and I wanted to be able to appease each one so I cut them off there. Nobody said thank you. A few kids grabbed violently. I didn't give to everyone. I may have given to someone twice by accident; it was hard to remember so many faces so fast.

** Our Wayu guide
On the bus, he told us how to say a few things. Insufficient repetition; nobody remembered any of them. He said he would talk about his culture. Maybe there was more but I only remember two discussions. One was of polygamy. It used to cost a thousand goats to buy a bride, and a man could have four. (I imagine the price wasn't constant and was on average less than a thousand, but have been unable to investigate.) Someone asked about polyandry. Nope, he said women couldn't. He didn't specify whether that was due to lack of buying power or legal prohibition.

The other story I remember was of people who would toss a dead body onto the railroad and then sue the railroad company.

** The town we stayed at
is right on the beach near the north tip of La Guajira, which is the northmost part of Colombia. Sandy was there in 2018, and had prepared me for otherworldly beauty -- silent, at the intersection of (small) mountains, desert and ocean, with stars unmasked by artificial light (after midnight at least -- the power went off every night at midnight).

It's not like that now. There's been a lot of construction -- wood, tin and brick -- right up to within a few meters of the beach. "Hotels", far more than demand could meet, offer hammocks against the beach. Young (20s) and we think drunk Colombian tourists pumped music from their parked cars, fighting volume wars with each other. All the same music, too: "vallenato", which to me mostly sounds like variations on nursery rhymes and/or Bobby McGee, plus accordions.

They told us music is prohibited after 11. It didn't stop. Sandy and I went walking at midnight carrying pillows and a few other things, found a hotel where the neighbors were still loud but not as loud, and stayed there instead. She ate at the second hotel, I ate at the first, so we ate or stashed four breakfasts between the two of us.

** The cliffs on the beach
were beautiful. With some work I found a spot where I couldn't hear music. On the sand I didn't escape beer cans, plastic cups or a pair of panties, but the water was clean and the waves were fun.

** We left the next day.
On the way back we stopped at a place where they make artisanal salt. Some company does that, but right next to them are small landholders who dry out ocean water and then collect it into big mounds and sell it to the company, for 60 US cents for a bag bigger than a baby. They tried to sell us skin care products made from salt, and started putting the stuff on my skin. I had to say no with more force than I was comfortable with to stop them.

Sandy wanted pictures of us on a swingset. A Wayu girl offered to take the picture. Sandy asked if we would have to pay her. She said no, how could you even ask that. She asked where we were from, and we talked about that a bit. She asked if we were going to have kids. No, actually trying not to, thanks. Too much responsibility. She agreed, said she was a single mother. She looked 25 at most. She was eloquent, cheerful, dignified. That brief conversation was delightful.

To my knowledge all of our tourmates except us had stayed at the first hotel they paid for. They looked sleepy.

When we got back to Santa Marta the crowds had left. It's a lot more relaxing here now. This morning I  to the corner store, bought water and came back without anyone offering me a tour of anything.
