:PROPERTIES:
:ID:       31341f45-3d93-4f9c-88c6-70990e0f05e4
:ROAM_ALIASES: "write, why to"
:END:
#+title: why write
* [[id:a5ad5ac9-287e-4e0a-a564-64f82a72d5f5][Writing things somewhat satisfies the desire for objectivity.]]
* Writing something you will read moves your life path.
* Writing makes us immortal, in two ways.
** know where you are
   A thousand, a trillion years could have the information content of one night of focused thinking and observation. There are only two things to change, the sensations and the ideas in one's experience. And of those we can see farther, be infinitely more, in the ideas. Deeply knowing the nature of (your) experience, by having written about and studied it. And that can go unpredictably, inconceivably farther still by sharing the project with even a few interested seekers.
** Join the eternal body of human writing.
   Einstein will outlive Lincoln, Caesar and anyone like that, because those dramas will repeat, eventually, on even bigger scales, but there is only one first discoverer of a good idea.
   Try to be like Einstein. Tag (as in graffiti) the world with something that will last -- which requires it to be useful insight, because all else will be overwritten (if humanity survives long enough).
* It requires {humility, confidence, patience,}
  Don't think you've reached your final form of wisdom.
  Recognize you are capable of learning more about deep, high things.
  Be imaginative about how different a long-term payoff in ideas is.
* To write, to ask "what just happened" with open eyes, is to step outside of time, to at long last observe it, and to some extent determine what it is.
* Writing is psychedelic.
  :PROPERTIES:
  :ID:       80faf0cd-804c-49e9-b799-57a2515d742d
  :END:
** [[id:890fc33b-1247-459a-980f-6b3163f9bc1d][To focus on feelings feels paychedelic.]]
