:PROPERTIES:
:ID:       59e80c44-dec3-4dd7-bdbd-49c92118fb0e
:END:
#+title: Your Inner Fish , book by Neil Shubin
* Some of the bones in the inner ear of a mammal where once the jaw bones, or rather part of the jaw at the back, in reptiles. Our three bone structure allows us to hear higher frequencies than lizards
* We can turn on an eye gene in any weird place on a fly and get an eye there. Some of them even respond to light.
* The smell genes in dolphins are defunct because they use what used to be a nasal passage for a blowhole now.
  Whales too?
* 3% of the DNA is for smell receptors
** We have a lot of them, and smells "play" like chords in music -- multiple signals for one smell
* Bodies developed fast and slow
** Bodies didn't develop until the earth had enough oxygen to support them.
** It took algae only 200 generations after the introduction of a flagellate predator to become a creature of 8 cella rather than 1.
* Maybe the "rivets" that hold our cells to each other came from predators trying to hold prey.
* Someone used baby hair to split an embryo, maybe a blastocyst which is a very simple embryo, in two. It became twins.
* In the developing embryo there is a region called the organizer. If it is transplanted from one species to a new species, it can turn that second species into the first.
* "Talking did not come cheap."
** We use the same hole to talk, eat and breathe.
*** => choking hazard
** Apnea only happens in humans (and pugs?).
   Stuff in our throats got soft in order to permit speech.
* Returning blood from the feet is somewhat elaborate.
** Blood pressure is higher in arteries than in the veins.
** Valves in leg veins prevent blood going backward.
** The leg muscles move the blood back up when we walk.
** If the blood pools in the veins, it can cause the valves to fail.
   This is called varicose veins.
   They swell and take tortuous paths.
** Too much sitting can cause hemmorhoids.
   Blood pools in the veins around the rectum.
** TODO [[id:ebaee383-c333-4bd6-914e-a46c96e99651][Sitting on soft things is particularly bad?]]
* [[id:b5524772-97ee-4df6-b209-c4accb7dfe2f][Some sea mammals forgot how to smell.]]
* the common limb structure
  All vertebrates that came from (but aren't) fish have the same structure for their limbs: one bone, then two bones, then a bunch of lumpy things, and then digits. Even whales have little stubbly legs and feet, inside their bellies.
